export const records: { word: string, translation_en: string, translation_jp: string }[] = [
    { word: "قلم رصاص", translation_en: "pencil", translation_jp: "鉛筆" },
    { word: "بطاقة مرور", translation_en: "credit card", translation_jp: "クレジットカード" },
    { word: "حجر", translation_en: "stone", translation_jp: "石" },
    { word: "حصة", translation_en: "share", translation_jp: "共有" },
    { word: "تيار كهربائي", translation_en: "electric current", translation_jp: "電流" },
    { word: "نجاح", translation_en: "success", translation_jp: "成功" },
    { word: "مالك", translation_en: "owner", translation_jp: "所有者" },
    { word: "هجوم", translation_en: "attack", translation_jp: "攻撃" },
    { word: "دائرة", translation_en: "circle", translation_jp: "丸" },
    { word: "دقيقة", translation_en: "minute", translation_jp: "分" },
    { word: "انطباع", translation_en: "impression", translation_jp: "印象" },
    { word: "محكمة", translation_en: "court", translation_jp: "裁判所" },
    { word: "مقبض", translation_en: "handle", translation_jp: "ハンドル" },
    { word: "رأي", translation_en: "see", translation_jp: "見る" },
    { word: "زوج", translation_en: "husband", translation_jp: "夫" },
    { word: "درجة", translation_en: "degree", translation_jp: "程度" },
    { word: "معيار", translation_en: "standard", translation_jp: "標準" },
    { word: "كلما", translation_en: "the word", translation_jp: "言葉" },
    { word: "خريف", translation_en: "autumn", translation_jp: "秋" },
    { word: "اجتماع", translation_en: "gathering", translation_jp: "集まる" },
    { word: "اختصاصي", translation_en: "specialist", translation_jp: "スペシャリスト" },
    { word: "أذن", translation_en: "ear", translation_jp: "耳" },
    { word: "خروف", translation_en: "Lamb", translation_jp: "子羊" },
    { word: "تقسيم", translation_en: "division", translation_jp: "分割" },
    { word: "درج", translation_en: "insert", translation_jp: "入れる" },
    { word: "أنف", translation_en: "breath", translation_jp: "呼吸" },
    { word: "ضد", translation_en: "against", translation_jp: "に対して" },
    { word: "لغة", translation_en: "language", translation_jp: "言語" },
    { word: "خط", translation_en: "letter", translation_jp: "手紙" },
    { word: "شمس", translation_en: "Shams", translation_jp: "シャムス" },
    { word: "مستحق", translation_en: "deserved", translation_jp: "当然のこと" },
    { word: "طيران", translation_en: "flight", translation_jp: "フライト" },
    { word: "سلاح", translation_en: "weapon", translation_jp: "武器" },
    { word: "متى", translation_en: "when", translation_jp: "いつ" },
    { word: "طابق", translation_en: "match", translation_jp: "マッチ" },
    { word: "إيقاع", translation_en: "rhythm", translation_jp: "リズム" },
    { word: "دماغ", translation_en: "nose", translation_jp: "鼻" },
    { word: "مضخة", translation_en: "pump", translation_jp: "ポンプ" },
    { word: "أرضية", translation_en: "earth", translation_jp: "地球" },
    { word: "نظرية", translation_en: "theory", translation_jp: "理論" },
    { word: "وزير", translation_en: "minister", translation_jp: "大臣" },
    { word: "مزرعة", translation_en: "Farm", translation_jp: "農場" },
    { word: "قبعة", translation_en: "hat", translation_jp: "帽子" },
    { word: "حجة", translation_en: "Hajja", translation_jp: "ハジャ" },
    { word: "مرحلة", translation_en: "stage", translation_jp: "ステージ" },
    { word: "أنفسهم", translation_en: "themselves", translation_jp: "彼ら自身" },
    { word: "إيمان", translation_en: "Faith", translation_jp: "信仰" },
    { word: "أداة", translation_en: "tool", translation_jp: "道具" },
    { word: "طائرة", translation_en: "jet", translation_jp: "ジェット" },
    { word: "عربة يدوية", translation_en: "Handcart", translation_jp: "手押し車" },
    { word: "حرارة", translation_en: "heat", translation_jp: "熱" },
    { word: "سلطة", translation_en: "salad", translation_jp: "サラダ" },
    { word: "ستارة", translation_en: "Star", translation_jp: "星" },
    { word: "قمة", translation_en: "top", translation_jp: "トップ" },
    { word: "محطة", translation_en: "station", translation_jp: "駅" },
    { word: "وجه", translation_en: "face", translation_jp: "顔" },
    { word: "سياسة", translation_en: "policy", translation_jp: "ポリシー" },
    { word: "سيارة", translation_en: "car", translation_jp: "車" },
    { word: "رقم", translation_en: "figure", translation_jp: "形" },
    { word: "زيادة", translation_en: "increase", translation_jp: "増加" },
    { word: "تنوع", translation_en: "diversity", translation_jp: "多様性" },
    { word: "بناء", translation_en: "build", translation_jp: "建てる" },
    { word: "شراب", translation_en: "wine", translation_jp: "ワイン" },
    { word: "سائل", translation_en: "question", translation_jp: "質問" },
    { word: "مدرسة", translation_en: "school", translation_jp: "学校" },
    { word: "قفزة", translation_en: "jump", translation_jp: "ジャンプ" },
    { word: "جمهور", translation_en: "audience", translation_jp: "観客" },
    { word: "نمط", translation_en: "pattern", translation_jp: "パターン" },
    { word: "ملابس", translation_en: "clothes", translation_jp: "服" },
    { word: "منظمة", translation_en: "organization", translation_jp: "組織" },
    { word: "نفس", translation_en: "breath", translation_jp: "呼吸" },
    { word: "زواج", translation_en: "marriage", translation_jp: "結婚" },
    { word: "أنبوب", translation_en: "pipe", translation_jp: "パイプ" },
    { word: "كاتب عدل", translation_en: "notary public", translation_jp: "公証人" },
    { word: "عمر", translation_en: "Omar", translation_jp: "オマル" },
    { word: "مسافة واسعة", translation_en: "wide distance", translation_jp: "遠距離" },
    { word: "رحلة", translation_en: "trip", translation_jp: "旅行" },
    { word: "حركة", translation_en: "movement", translation_jp: "動き" },
    { word: "مستوى", translation_en: "level", translation_jp: "レベル" },
    { word: "حد", translation_en: "limit", translation_jp: "限界" },
    { word: "باقي", translation_en: "the rest", translation_jp: "残り" },
    { word: "استراتيجية", translation_en: "strategy", translation_jp: "戦略" },
    { word: "نفط", translation_en: "oil", translation_jp: "油" },
    { word: "قوة", translation_en: "power", translation_jp: "力" },
    { word: "آلة", translation_en: "machine", translation_jp: "機械" },
    { word: "جنوب", translation_en: "south", translation_jp: "南" },
    { word: "معدن", translation_en: "mine", translation_jp: "私の" },
    { word: "قاضي", translation_en: "the judge", translation_jp: "裁判官" },
    { word: "لون", translation_en: "loan", translation_jp: "ローン" },
    { word: "جسم", translation_en: "body", translation_jp: "体" },
    { word: "جوز", translation_en: "you know", translation_jp: "あなたが知っている" },
    { word: "حديد", translation_en: "Hadid", translation_jp: "ハディド" },
    { word: "سلام", translation_en: "Hello", translation_jp: "こんにちは" },
    { word: "قتال", translation_en: "Qatal", translation_jp: "カタール" },
    { word: "طبيعة", translation_en: "nature", translation_jp: "自然" },
    { word: "حبيبة", translation_en: "lover", translation_jp: "愛人" },
    { word: "صفقة", translation_en: "deal", translation_jp: "取引" },
    { word: "مذاق", translation_en: "joke", translation_jp: "ジョーク" },
    { word: "شك", translation_en: "doubt", translation_jp: "疑い" },
    { word: "سكة", translation_en: "coin", translation_jp: "コイン" },
    { word: "ظهر", translation_en: "noon", translation_jp: "正午" },
    { word: "ولد", translation_en: "born", translation_jp: "生まれる" },
    { word: "منافسة", translation_en: "Competition", translation_jp: "競争" },
    { word: "تحرك", translation_en: "move", translation_jp: "動く" },
    { word: "بيانات", translation_en: "data", translation_jp: "データ" },
    { word: "برد", translation_en: "bard", translation_jp: "吟遊詩人" },
    { word: "حمام", translation_en: "bathrooms", translation_jp: "バスルーム" },
    { word: "مطالبة", translation_en: "demand", translation_jp: "要求" },
    { word: "دجاجة", translation_en: "Chicken", translation_jp: "チキン" },
    { word: "بدون", translation_en: "without", translation_jp: "それなし" },
    { word: "اقتراح", translation_en: "suggestion", translation_jp: "提案" },
    { word: "جذر", translation_en: "root", translation_jp: "根" },
    { word: "نفسه", translation_en: "self", translation_jp: "自己" },
    { word: "حرف", translation_en: "letter", translation_jp: "手紙" },
    { word: "صديق", translation_en: "friend", translation_jp: "友人" },
    { word: "جواب", translation_en: "answer", translation_jp: "答え" },
    { word: "خارج", translation_en: "out", translation_jp: "外" },
    { word: "تعليق", translation_en: "comment", translation_jp: "コメント" },
    { word: "اختلاف", translation_en: "disagreement", translation_jp: "不一致" },
    { word: "مطر", translation_en: "rain", translation_jp: "雨" },
    { word: "مراقب", translation_en: "observer", translation_jp: "観察者" },
    { word: "عقدة", translation_en: "contract", translation_jp: "契約" },
    { word: "منحدر", translation_en: "slope", translation_jp: "スロープ" },
    { word: "لكن", translation_en: "But", translation_jp: "しかし" },
    { word: "حقيقة", translation_en: "reality", translation_jp: "現実" },
    { word: "لفافة", translation_en: "wrap", translation_jp: "包む" },
    { word: "أفضلية", translation_en: "preference", translation_jp: "好み" },
    { word: "هو", translation_en: "yes", translation_jp: "はい" },
    { word: "مسمار", translation_en: "nail", translation_jp: "釘" },
    { word: "دراجة", translation_en: "bicycle", translation_jp: "自転車" },
    { word: "معلومات", translation_en: "information", translation_jp: "情報" },
    { word: "نفسك", translation_en: "yourself", translation_jp: "あなた自身" },
    { word: "سرير", translation_en: "bed", translation_jp: "ベッド" },
    { word: "أمر", translation_en: "command", translation_jp: "指示" },
    { word: "حاجز معدني", translation_en: "metallurgy", translation_jp: "冶金" },
    { word: "لعبة", translation_en: "game", translation_jp: "ゲーム" },
    { word: "جدول", translation_en: "table", translation_jp: "テーブル" },
    { word: "اقتصاد", translation_en: "economy", translation_jp: "経済" },
    { word: "منزل", translation_en: "home", translation_jp: "家" },
    { word: "جورب", translation_en: "sock", translation_jp: "靴下" },
    { word: "سرور", translation_en: "server", translation_jp: "サーバ" },
    { word: "إطار", translation_en: "frame", translation_jp: "フレーム" },
    { word: "إنترنت", translation_en: "Internet", translation_jp: "インターネット" },
    { word: "موعد", translation_en: "date", translation_jp: "日付" },
    { word: "حتى", translation_en: "even", translation_jp: "平" },
    { word: "هيكلية", translation_en: "structure", translation_jp: "構造" },
    { word: "أرض", translation_en: "earth", translation_jp: "地球" },
    { word: "شحنة كهربائية", translation_en: "Electric charge", translation_jp: "電荷" },
    { word: "بحث", translation_en: "discussion", translation_jp: "議論" },
    { word: "معلم", translation_en: "teacher", translation_jp: "教師" },
    { word: "ميت", translation_en: "die", translation_jp: "死ぬ" },
    { word: "طاقة", translation_en: "energy", translation_jp: "エネルギー" },
    { word: "موت", translation_en: "the weather", translation_jp: "天候" },
    { word: "جزء", translation_en: "part", translation_jp: "一部" },
    { word: "وجود", translation_en: "existence", translation_jp: "存在" },
    { word: "أخت", translation_en: "sister", translation_jp: "妹" },
    { word: "قطن", translation_en: "Cotton", translation_jp: "コットン" },
    { word: "أنموذج", translation_en: "Model", translation_jp: "モデル" },
    { word: "الذي", translation_en: "who", translation_jp: "誰が" },
    { word: "حجم", translation_en: "volume", translation_jp: "音量" },
    { word: "مورد", translation_en: "mod", translation_jp: "モッド" },
    { word: "سماء", translation_en: "sky", translation_jp: "空" },
    { word: "مجموع", translation_en: "total", translation_jp: "合計" },
    { word: "فندق", translation_en: "hazelnut", translation_jp: "ヘーゼルナッツ" },
    { word: "طاولة", translation_en: "table", translation_jp: "テーブル" },
    { word: "تكنولوجيا", translation_en: "technology", translation_jp: "テクノロジー" },
    { word: "جرح", translation_en: "hurt", translation_jp: "傷つく" },
    { word: "قرن", translation_en: "century", translation_jp: "世紀" },
    { word: "وسط", translation_en: "mid", translation_jp: "半ば、" },
    { word: "عضلة", translation_en: "muscle", translation_jp: "筋" },
    { word: "أنثى", translation_en: "female", translation_jp: "女性" },
    { word: "قلم", translation_en: "pen", translation_jp: "ペン" },
    { word: "معنى", translation_en: "meaning", translation_jp: "意味" },
    { word: "بخار", translation_en: "steam", translation_jp: "スチーム" },
    { word: "تهمة", translation_en: "accusation", translation_jp: "告発" },
    { word: "عامل", translation_en: "factor", translation_jp: "要素" },
    { word: "عدد أولي", translation_en: "first number", translation_jp: "最初の番号" },
    { word: "سلوك", translation_en: "behavior", translation_jp: "行動" },
    { word: "حق", translation_en: "right", translation_jp: "右" },
    { word: "لأجل", translation_en: "for", translation_jp: "のために" },
    { word: "غبار", translation_en: "dust", translation_jp: "ほこり" },
    { word: "مساحة", translation_en: "space", translation_jp: "空間" },
    { word: "رأس", translation_en: "head", translation_jp: "頭" },
    { word: "خبر", translation_en: "news", translation_jp: "ニュース" },
    { word: "طريقة", translation_en: "method", translation_jp: "方法" },
    { word: "مفتاح", translation_en: "key", translation_jp: "鍵" },
    { word: "صحة", translation_en: "health", translation_jp: "健康" },
    { word: "سلة", translation_en: "basket", translation_jp: "バスケット" },
    { word: "بيع", translation_en: "do", translation_jp: "する" },
    { word: "شعاع", translation_en: "rays", translation_jp: "光線" },
    { word: "طعام", translation_en: "food", translation_jp: "食べ物" },
    { word: "أحد", translation_en: "a person", translation_jp: "人" },
    { word: "ندم", translation_en: "sorry", translation_jp: "ごめん" },
    { word: "عائلة", translation_en: "family", translation_jp: "家族" },
    { word: "أسبوع", translation_en: "week", translation_jp: "週" },
    { word: "فرصة", translation_en: "chance", translation_jp: "チャンス" },
    { word: "مسلسل", translation_en: "series", translation_jp: "シリーズ" },
    { word: "غرامة", translation_en: "penalty", translation_jp: "ペナルティ" },
    { word: "جلد", translation_en: "Vol", translation_jp: "巻" },
    { word: "علامة", translation_en: "mark", translation_jp: "マーク" },
    { word: "سلسلة", translation_en: "series", translation_jp: "シリーズ" },
    { word: "تقرير", translation_en: "speech", translation_jp: "スピーチ" },
    { word: "عزيز", translation_en: "dear", translation_jp: "親愛なる" },
    { word: "مجموعة", translation_en: "group", translation_jp: "グループ" },
    { word: "إما", translation_en: "either", translation_jp: "どちらか" },
    { word: "مجلس", translation_en: "Majlis", translation_jp: "マジュリス" },
    { word: "أساس", translation_en: "basis", translation_jp: "基礎" },
    { word: "مادة", translation_en: "material", translation_jp: "材料" },
    { word: "جذب", translation_en: "attraction", translation_jp: "アトラクション" },
    { word: "علاقة", translation_en: "relationship", translation_jp: "関係" },
    { word: "قفل", translation_en: "lock", translation_jp: "ロック" },
    { word: "تطور", translation_en: "development", translation_jp: "発達" },
    { word: "اتجاه", translation_en: "direction", translation_jp: "方向" },
    { word: "تدريب", translation_en: "training", translation_jp: "トレーニング" },
    { word: "طقس", translation_en: "weather", translation_jp: "天気" },
    { word: "لاصق", translation_en: "adhesive", translation_jp: "接着剤" },
    { word: "تصميم", translation_en: "decision", translation_jp: "決断" },
    { word: "ريش", translation_en: "again", translation_jp: "また" },
    { word: "موقع", translation_en: "location", translation_jp: "位置" },
    { word: "نصف", translation_en: "half", translation_jp: "半分" },
    { word: "فقدان", translation_en: "loss", translation_jp: "損失" },
    { word: "إجراء", translation_en: "procedure", translation_jp: "手順" },
    { word: "حيوان", translation_en: "animal", translation_jp: "動物" },
    { word: "تحكم", translation_en: "control", translation_jp: "コントロール" },
    { word: "فكرة", translation_en: "idea", translation_jp: "アイデア" },
    { word: "يد", translation_en: "hand", translation_jp: "手" },
    { word: "عقل", translation_en: "intellect", translation_jp: "知性" },
    { word: "تحليل", translation_en: "analysis", translation_jp: "分析" },
    { word: "كأس", translation_en: "kos", translation_jp: "コス" },
    { word: "تقدم", translation_en: "advance", translation_jp: "前進" },
    { word: "تكلفة", translation_en: "cost", translation_jp: "料金" },
    { word: "هواء", translation_en: "air", translation_jp: "空気" },
    { word: "ساعة", translation_en: "hour", translation_jp: "時間" },
    { word: "ذيل", translation_en: "tail", translation_jp: "しっぽ" },
    { word: "هم", translation_en: "hm", translation_jp: "うーん" },
    { word: "جودة", translation_en: "quality", translation_jp: "品質" },
    { word: "منجم", translation_en: "Manjum", translation_jp: "マンジュム" },
    { word: "صدر", translation_en: "chest", translation_jp: "胸" },
    { word: "رسالة", translation_en: "message", translation_jp: "メッセージ" },
    { word: "خلال", translation_en: "hook", translation_jp: "フック" },
    { word: "معاملة", translation_en: "transaction", translation_jp: "取引" },
    { word: "عمل", translation_en: "action", translation_jp: "アクション" },
    { word: "عقاب", translation_en: "Eagle", translation_jp: "イーグル" },
    { word: "سكر", translation_en: "sugar", translation_jp: "砂糖" },
    { word: "جهاز", translation_en: "plane", translation_jp: "飛行機" },
    { word: "خطر", translation_en: "danger", translation_jp: "危険" },
    { word: "دهن", translation_en: "eat", translation_jp: "食べる" },
    { word: "تيار", translation_en: "ready", translation_jp: "準備ができて" },
    { word: "نفسي", translation_en: "my soul", translation_jp: "私の魂" },
    { word: "فترة", translation_en: "period", translation_jp: "期間" },
    { word: "حزمة", translation_en: "pack", translation_jp: "パック" },
    { word: "توقف قصير", translation_en: "short stop", translation_jp: "ショートストップ" },
    { word: "زبون", translation_en: "zboon", translation_jp: "ズブーン" },
    { word: "اقتراب", translation_en: "approach", translation_jp: "アプローチ" },
    { word: "واجب", translation_en: "obligatory", translation_jp: "義務的な" },
    { word: "دعم", translation_en: "support", translation_jp: "サポート" },
    { word: "غاية", translation_en: "गाये", translation_jp: "गाये" },
    { word: "فستان", translation_en: "dress", translation_jp: "ドレス" },
    { word: "دخان", translation_en: "smoking", translation_jp: "喫煙" },
    { word: "صوت", translation_en: "sound", translation_jp: "音" },
    { word: "محاولة", translation_en: "attempt", translation_jp: "試み" },
    { word: "امتحان", translation_en: "the exam", translation_jp: "試験" },
    { word: "دين", translation_en: "religion", translation_jp: "宗教" },
    { word: "نعم", translation_en: "Yes", translation_jp: "はい" },
    { word: "وجبة", translation_en: "meal", translation_jp: "食事" },
    { word: "لون", translation_en: "loan", translation_jp: "ローン" },
    { word: "فولاذ", translation_en: "steel", translation_jp: "鋼鉄" },
    { word: "جنس", translation_en: "gender", translation_jp: "性別" },
    { word: "سمع", translation_en: "I heard", translation_jp: "私は聞いた" },
    { word: "سؤال", translation_en: "question", translation_jp: "質問" },
    { word: "عاصمة", translation_en: "capital", translation_jp: "資本" },
    { word: "خاتم", translation_en: "finish", translation_jp: "仕上げる" },
    { word: "مؤسسة", translation_en: "institution", translation_jp: "機関、" },
    { word: "طريق", translation_en: "the road", translation_jp: "道路" },
    { word: "رمادي", translation_en: "Ramadi", translation_jp: "ラマディ" },
    { word: "قلب", translation_en: "heart", translation_jp: "心臓" },
    { word: "طبل", translation_en: "drum", translation_jp: "ドラム" },
    { word: "مناقشة", translation_en: "discussion", translation_jp: "議論" },
    { word: "رمل", translation_en: "Sand", translation_jp: "砂" },
    { word: "إبهام", translation_en: "I know", translation_jp: "知っている" },
    { word: "فريق معاون", translation_en: "assistant team", translation_jp: "アシスタントチーム" },
    { word: "الناس", translation_en: "people", translation_jp: "人々" },
    { word: "فريق", translation_en: "team", translation_jp: "チーム" },
    { word: "ممثل", translation_en: "representative", translation_jp: "代表" },
    { word: "مع", translation_en: "with", translation_jp: "と" },
    { word: "عودة", translation_en: "return", translation_jp: "戻る" },
    { word: "زوجة", translation_en: "Wife", translation_jp: "妻" },
    { word: "قرد", translation_en: "according to", translation_jp: "によると" },
    { word: "خادم", translation_en: "servant", translation_jp: "サーバント" },
    { word: "شخص", translation_en: "person", translation_jp: "人" },
    { word: "مجال", translation_en: "majla", translation_jp: "マジュラ" },
    { word: "هضم", translation_en: "digestion", translation_jp: "消化" },
    { word: "سلم", translation_en: "Peace be upon you", translation_jp: "平安あれ" },
    { word: "مقترح", translation_en: "suggested", translation_jp: "提案された" },
    { word: "نبات", translation_en: "plant", translation_jp: "植物" },
    { word: "جريمة", translation_en: "the crime", translation_jp: "犯罪" },
    { word: "بت", translation_en: "idol", translation_jp: "アイドル" },
    { word: "قميص", translation_en: "shirt", translation_jp: "シャツ" },
    { word: "ثقب", translation_en: "hole", translation_jp: "穴" },
    { word: "خزنة", translation_en: "the treasury", translation_jp: "財務省" },
    { word: "قاعدة", translation_en: "base", translation_jp: "ベース" },
    { word: "منصة", translation_en: "platform", translation_jp: "プラットフォーム" },
    { word: "سقف", translation_en: "ceiling", translation_jp: "シーリング" },
    { word: "عدد", translation_en: "number", translation_jp: "番号" },
    { word: "نهاية", translation_en: "end", translation_jp: "終わり" },
    { word: "تمرن", translation_en: "tamran", translation_jp: "タムラン" },
    { word: "سلم موسيقي", translation_en: "Hello music", translation_jp: "こんにちは音楽" },
    { word: "هدية", translation_en: "gift", translation_jp: "贈り物" },
    { word: "مصرف", translation_en: "bank", translation_jp: "銀行" },
    { word: "أي شيء", translation_en: "any thing", translation_jp: "何でも" },
    { word: "ثوب", translation_en: "dress", translation_jp: "ドレス" },
    { word: "مصلحة", translation_en: "interest", translation_jp: "興味" },
    { word: "قائد", translation_en: "leader", translation_jp: "リーダー" },
    { word: "استعراض", translation_en: "review", translation_jp: "レビュー" },
    { word: "نار", translation_en: "fire", translation_jp: "火" },
    { word: "مكافأة", translation_en: "reward", translation_jp: "褒美" },
    { word: "ورق", translation_en: "sheet", translation_jp: "シート" },
    { word: "ذهب", translation_en: "zahab", translation_jp: "ザハブ" },
    { word: "رائحة", translation_en: "the smell", translation_jp: "匂い" },
    { word: "شرطة", translation_en: "Condition", translation_jp: "状態" },
    { word: "وطن", translation_en: "homeland", translation_jp: "祖国" },
    { word: "بينما", translation_en: "while", translation_jp: "その間" },
    { word: "دورة", translation_en: "course", translation_jp: "コース" },
    { word: "ساق", translation_en: "saq", translation_jp: "サクサク" },
    { word: "حفلة", translation_en: "party", translation_jp: "パーティー" },
    { word: "احتجاج", translation_en: "protest", translation_jp: "抗議する" },
    { word: "نفسها", translation_en: "herself", translation_jp: "彼女自身" },
    { word: "شعر", translation_en: "poetry", translation_jp: "詩" },
    { word: "كره", translation_en: "I hate it", translation_jp: "私はそれが嫌いです" },
    { word: "كيميائي", translation_en: "chemical", translation_jp: "化学薬品" },
    { word: "مال", translation_en: "goods", translation_jp: "品" },
    { word: "طبشور", translation_en: "tabashor", translation_jp: "タバショール" },
    { word: "أمام", translation_en: "I know", translation_jp: "知っている" },
    { word: "نثر", translation_en: "Nasr", translation_jp: "ナスル" },
    { word: "سحاب", translation_en: "Sahab", translation_jp: "サハブ" },
    { word: "سحق", translation_en: "crush", translation_jp: "打ち砕く" },
    { word: "قرار", translation_en: "decision", translation_jp: "決断" },
    { word: "فرن", translation_en: "oven", translation_jp: "オーブン" },
    { word: "زاوية", translation_en: "angle", translation_jp: "角度" },
    { word: "إعلان", translation_en: "announcement", translation_jp: "発表" },
    { word: "دفاع", translation_en: "defense", translation_jp: "防衛" },
    { word: "هدف", translation_en: "goal", translation_jp: "ゴール" },
    { word: "أهل", translation_en: "ahl", translation_jp: "あーる" },
    { word: "حاضر", translation_en: "present", translation_jp: "現在" },
    { word: "حامض", translation_en: "sour", translation_jp: "酸っぱい" },
    { word: "دليل", translation_en: "proof", translation_jp: "証拠" },
    { word: "عطاس", translation_en: "Attas", translation_jp: "アタス" },
    { word: "مجوهرات", translation_en: "jewelry", translation_jp: "ジュエリー" },
    { word: "مقعد", translation_en: "anus", translation_jp: "肛門" },
    { word: "منخفض جوي", translation_en: "low", translation_jp: "低い" },
    { word: "سجن", translation_en: "sajn", translation_jp: "サジン" },
    { word: "حاجة", translation_en: "need", translation_jp: "必要" },
    { word: "ادعاء", translation_en: "claim", translation_jp: "請求" },
    { word: "سفينة", translation_en: "the ship", translation_jp: "船" },
    { word: "نملة", translation_en: "ant", translation_jp: "アリ" },
    { word: "سمك", translation_en: "fish", translation_jp: "魚" },
    { word: "صفيحة", translation_en: "page", translation_jp: "ページ" },
    { word: "مقياس", translation_en: "scale", translation_jp: "規模" },
    { word: "دمغة", translation_en: "the tattoo", translation_jp: "タトゥー" },
    { word: "دب", translation_en: "db", translation_jp: "データベース" },
    { word: "سكين", translation_en: "skin", translation_jp: "肌" },
    { word: "حياة", translation_en: "life", translation_jp: "人生" },
    { word: "ظرف", translation_en: "container", translation_jp: "容器" },
    { word: "سكون", translation_en: "skunk", translation_jp: "スカンク" },
    { word: "تقنية", translation_en: "technique", translation_jp: "技術" },
    { word: "معرفة", translation_en: "knowledge", translation_jp: "知識" },
    { word: "حب", translation_en: "love", translation_jp: "愛" },
    { word: "رغم", translation_en: "despite", translation_jp: "にもかかわらず" },
    { word: "قط", translation_en: "Cat", translation_jp: "猫" },
    { word: "ميناء", translation_en: "port", translation_jp: "ポート" },
    { word: "زخرفة", translation_en: "decoration", translation_jp: "装飾" },
    { word: "طاهي", translation_en: "tahi", translation_jp: "タヒ" },
    { word: "مؤتمر", translation_en: "conference", translation_jp: "会議" },
    { word: "ذراع", translation_en: "arm", translation_jp: "アーム" },
    { word: "أب", translation_en: "ab", translation_jp: "腹筋" },
    { word: "قفاز", translation_en: "cage", translation_jp: "ケージ" },
    { word: "قياس", translation_en: "analogy", translation_jp: "類推" },
    { word: "تجربة", translation_en: "experience", translation_jp: "経験" },
    { word: "رغم أن", translation_en: "in spite of that", translation_jp: "それにもかかわらず" },
    { word: "نسبة مئوية", translation_en: "percentage", translation_jp: "割合" },
    { word: "مقارنة", translation_en: "comparison", translation_jp: "比較" },
    { word: "رجل", translation_en: "man", translation_jp: "男" },
    { word: "ضوء", translation_en: "light", translation_jp: "ライト" },
    { word: "ضفة", translation_en: "bank", translation_jp: "銀行" },
    { word: "مسؤولية", translation_en: "responsibility", translation_jp: "責任" },
    { word: "شوكة", translation_en: "love", translation_jp: "愛" },
    { word: "إلى", translation_en: "to", translation_jp: "に" },
    { word: "أمن", translation_en: "security", translation_jp: "安全" },
    { word: "طيف", translation_en: "تيف", translation_jp: "トゥリ" },
    { word: "شرط", translation_en: "condition", translation_jp: "状態" },
    { word: "محور", translation_en: "axis", translation_jp: "軸" },
    { word: "حساب", translation_en: "account", translation_jp: "アカウント" },
    { word: "نموذج", translation_en: "model", translation_jp: "モデル" },
    { word: "فصل", translation_en: "crop", translation_jp: "作物" },
    { word: "منحنى", translation_en: "curve", translation_jp: "曲線" },
    { word: "معدة", translation_en: "stomach", translation_jp: "胃" },
    { word: "وﻻ", translation_en: "وﻻ", translation_jp: "こんにちわ" },
    { word: "مقاطعة", translation_en: "province", translation_jp: "州" },
    { word: "توقف", translation_en: "stop", translation_jp: "停止" },
    { word: "صدمة", translation_en: "trauma", translation_jp: "トラウマ" },
    { word: "لوح", translation_en: "lol", translation_jp: "笑" },
    { word: "عضة", translation_en: "bite", translation_jp: "噛む" },
    { word: "زنزانة", translation_en: "prison", translation_jp: "刑務所" },
    { word: "قطع", translation_en: "cut off", translation_jp: "切り落とす" },
    { word: "منظر", translation_en: "scenery", translation_jp: "景色" },
    { word: "تصرف", translation_en: "possession", translation_jp: "所持" },
    { word: "إدارة", translation_en: "Administration", translation_jp: "管理" },
    { word: "طرق", translation_en: "roads", translation_jp: "道路" },
    { word: "أنبوب تصريف", translation_en: "drain pipe", translation_jp: "排水管" },
    { word: "رئيس", translation_en: "president", translation_jp: "社長" },
    { word: "منطقة", translation_en: "region", translation_jp: "地域" },
    { word: "برنامج", translation_en: "program", translation_jp: "プログラム" },
    { word: "بنية", translation_en: "the structure", translation_jp: "構造" },
    { word: "مدينة", translation_en: "city", translation_jp: "市" },
    { word: "إنتاج", translation_en: "production", translation_jp: "生産" },
    { word: "حرف كبير", translation_en: "capital letter", translation_jp: "大文字" },
    { word: "عائد مالي", translation_en: "financial return", translation_jp: "経済的利益" },
    { word: "استثمار", translation_en: "exploitation", translation_jp: "搾取" },
    { word: "معلومة", translation_en: "known", translation_jp: "知られている" },
    { word: "فرشاة", translation_en: "brush", translation_jp: "ブラシ" },
    { word: "حقيبة", translation_en: "bag", translation_jp: "バッグ" },
    { word: "ثمن", translation_en: "the price", translation_jp: "価格" },
    { word: "مركز", translation_en: "center", translation_jp: "中心" },
    { word: "استبدال", translation_en: "replacement", translation_jp: "交換" },
    { word: "باب", translation_en: "bab", translation_jp: "バブ" },
    { word: "حريق", translation_en: "fire", translation_jp: "火" },
    { word: "ارتفاع", translation_en: "the height", translation_jp: "高さ" },
    { word: "صباح", translation_en: "morning", translation_jp: "朝" },
    { word: "بطاقة", translation_en: "card", translation_jp: "カード" },
    { word: "خيار", translation_en: "cucumber", translation_jp: "キュウリ" },
    { word: "خاصية", translation_en: "characteristic", translation_jp: "特性" },
    { word: "صابون", translation_en: "soap", translation_jp: "石鹸" },
    { word: "توزيع", translation_en: "distribution", translation_jp: "分布" },
    { word: "خطأ", translation_en: "error", translation_jp: "エラー" },
    { word: "قسم", translation_en: "oath", translation_jp: "誓い" },
    { word: "رطوبة", translation_en: "moisture", translation_jp: "水分" },
    { word: "ميزان", translation_en: "balance", translation_jp: "バランス" },
    { word: "مصعد", translation_en: "ascent", translation_jp: "上昇" },
    { word: "ابتسامة", translation_en: "smile", translation_jp: "笑顔" },
    { word: "خنزير", translation_en: "pig", translation_jp: "豚" },
    { word: "مخطط", translation_en: "striped", translation_jp: "縞模様の" },
    { word: "ذبابة", translation_en: "zababa", translation_jp: "ザババ" },
    { word: "عملية", translation_en: "operation", translation_jp: "手術" },
    { word: "باقة", translation_en: "the rest", translation_jp: "残り、" },
    { word: "خطوة", translation_en: "step", translation_jp: "ステップ" },
    { word: "آنسة", translation_en: "Ансеш", translation_jp: "Ансес" },
    { word: "مريض", translation_en: "patient", translation_jp: "忍耐強い" },
    { word: "طابع بريد", translation_en: "stamp", translation_jp: "スタンプ" },
    { word: "دكان", translation_en: "shop", translation_jp: "店" },
    { word: "أو", translation_en: "or", translation_jp: "または" },
    { word: "عنصر كيميائي", translation_en: "chemical element", translation_jp: "化学元素" },
    { word: "منقار", translation_en: "the beak", translation_jp: "くちばし" },
    { word: "صعوبة", translation_en: "difficulty", translation_jp: "困難" },
    { word: "مصباح", translation_en: "Misbah", translation_jp: "ミスバ" },
    { word: "اختيار", translation_en: "option", translation_jp: "オプション" },
    { word: "ميزة", translation_en: "advantage", translation_jp: "アドバンテージ" },
    { word: "مفاجأة", translation_en: "surprise", translation_jp: "驚き" },
    { word: "معطف", translation_en: "coat", translation_jp: "コート" },
    { word: "لأن", translation_en: "laan", translation_jp: "ラーン" },
    { word: "نقطة", translation_en: "point", translation_jp: "ポイント" },
    { word: "مقدار", translation_en: "quantity", translation_jp: "量" },
    { word: "شمال", translation_en: "north", translation_jp: "北" },
    { word: "ركلة", translation_en: "Kick", translation_jp: "キック" },
    { word: "ثقافة", translation_en: "culture", translation_jp: "文化" },
    { word: "قدرة", translation_en: "ability", translation_jp: "能力" },
    { word: "تقديم", translation_en: "presentation", translation_jp: "プレゼンテーション" },
    { word: "كتاب", translation_en: "book", translation_jp: "本" },
    { word: "صفحة", translation_en: "page", translation_jp: "ページ" },
    { word: "جنيه", translation_en: "pounds", translation_jp: "ポンド" },
    { word: "نشاط", translation_en: "activity", translation_jp: "活動" },
    { word: "حذاء", translation_en: "shoes", translation_jp: "靴" },
    { word: "ذكرى", translation_en: "memory", translation_jp: "メモリ" },
    { word: "فائدة", translation_en: "benefit", translation_jp: "利点" },
    { word: "وصية", translation_en: "وسية", translation_jp: "やあ" },
    { word: "مرض", translation_en: "disease", translation_jp: "病気" },
    { word: "عين", translation_en: "Ain", translation_jp: "アイン" },
    { word: "حكم", translation_en: "rule", translation_jp: "ルール" },
    { word: "وسادة", translation_en: "pillow", translation_jp: "枕" },
    { word: "ذاكرة", translation_en: "the memory", translation_jp: "記憶" },
    { word: "غليان", translation_en: "they seethe", translation_jp: "彼らは見る" },
    { word: "ذقن", translation_en: "chin", translation_jp: "顎" },
    { word: "كرة", translation_en: "ball", translation_jp: "ボール" },
    { word: "قدم", translation_en: "step", translation_jp: "ステップ" },
    { word: "صندوق", translation_en: "box", translation_jp: "箱" },
    { word: "تطبيق", translation_en: "application", translation_jp: "応用" },
    { word: "تدمير", translation_en: "destruction", translation_jp: "破壊" },
    { word: "تعليم", translation_en: "education", translation_jp: "教育" },
    { word: "نمو", translation_en: "growth", translation_jp: "成長" },
    { word: "موسيقى", translation_en: "music", translation_jp: "音楽" },
    { word: "استخدام", translation_en: "employment", translation_jp: "雇用" },
    { word: "ملعقة", translation_en: "spoon", translation_jp: "スプーン" },
    { word: "قاسم", translation_en: "Kasim", translation_jp: "カシム" },
    { word: "بجانب", translation_en: "by the way", translation_jp: "ところで" },
    { word: "مقص", translation_en: "Scissors", translation_jp: "ハサミ" },
    { word: "ولد", translation_en: "born", translation_jp: "生まれる" },
    { word: "صورة", translation_en: "photo", translation_jp: "写真" },
    { word: "لحظة", translation_en: "moment", translation_jp: "一瞬" },
    { word: "اختراع", translation_en: "invention", translation_jp: "発明" },
    { word: "نقل", translation_en: "transfer", translation_jp: "移行" },
    { word: "قراءة", translation_en: "reading", translation_jp: "読む" },
    { word: "اتصال", translation_en: "connection", translation_jp: "繋がり" },
    { word: "مربع", translation_en: "square", translation_jp: "四角" },
    { word: "غرفة", translation_en: "room", translation_jp: "部屋" },
    { word: "مجتمع", translation_en: "complex", translation_jp: "複雑な" },
    { word: "نحلة", translation_en: "honey", translation_jp: "ハニー" },
    { word: "نظام", translation_en: "system", translation_jp: "システム" },
    { word: "جمع", translation_en: "plural", translation_jp: "複数" },
    { word: "سبب", translation_en: "cause", translation_jp: "原因" },
    { word: "غطاء", translation_en: "cover", translation_jp: "カバー" },
    { word: "جزيرة", translation_en: "island", translation_jp: "島" },
    { word: "مشط", translation_en: "comb", translation_jp: "櫛" },
    { word: "تعلم", translation_en: "learn", translation_jp: "学ぶ" },
    { word: "طلب", translation_en: "student", translation_jp: "学生" },
    { word: "تفصيل", translation_en: "details", translation_jp: "詳細" },
    { word: "لسان", translation_en: "the language", translation_jp: "言語" },
    { word: "نوم", translation_en: "nom", translation_jp: "名目" },
    { word: "وقت", translation_en: "time", translation_jp: "時間" },
    { word: "رقم قياسي", translation_en: "ratio", translation_jp: "比率" },
    { word: "آلة تصوير", translation_en: "photo machine", translation_jp: "写真機" },
    { word: "مكتب", translation_en: "office", translation_jp: "オフィス" },
    { word: "عضو", translation_en: "organ", translation_jp: "器官" },
    { word: "هي", translation_en: "Hey", translation_jp: "おい" },
    { word: "بطاطس", translation_en: "Бататс", translation_jp: "Бататс" },
    { word: "ثانية", translation_en: "again", translation_jp: "また" },
    { word: "حقل", translation_en: "field", translation_jp: "分野" },
    { word: "مهارة", translation_en: "skill", translation_jp: "スキル" },
    { word: "مصنع", translation_en: "the factory", translation_jp: "工場" },
    { word: "ورقة نقدية", translation_en: "cash paper", translation_jp: "現金用紙" },
    { word: "شأن", translation_en: "so", translation_jp: "それで" },
    { word: "تأثير", translation_en: "effect", translation_jp: "効果" },
    { word: "شعور", translation_en: "consciousness", translation_jp: "意識" },
    { word: "موجة", translation_en: "Wave", translation_jp: "波" },
    { word: "أنا", translation_en: "Ана", translation_jp: "Ана" },
    { word: "مستقبل", translation_en: "future", translation_jp: "未来" },
    { word: "بيت", translation_en: "house", translation_jp: "家" },
    { word: "بحر", translation_en: "sea", translation_jp: "海" },
    { word: "وظيفة", translation_en: "job", translation_jp: "仕事" },
    { word: "سم", translation_en: "cm", translation_jp: "cm" },
    { word: "مسافة", translation_en: "distance", translation_jp: "距離" },
    { word: "شرطي", translation_en: "condition", translation_jp: "状態" },
    { word: "مهمة", translation_en: "important", translation_jp: "重要" },
    { word: "موضع", translation_en: "position", translation_jp: "位置" },
    { word: "ملاحظة", translation_en: "note", translation_jp: "注記" },
    { word: "رف", translation_en: "ref", translation_jp: "参照" },
    { word: "اتفاق", translation_en: "coincidence", translation_jp: "偶然" },
    { word: "وسيلة", translation_en: "the vehicle", translation_jp: "車両" },
    { word: "فضة", translation_en: "silver", translation_jp: "銀" },
    { word: "مبلغ متوجب", translation_en: "preacher", translation_jp: "説教者" },
    { word: "ارتياح", translation_en: "Artiah", translation_jp: "アルティア" },
    { word: "مورثة", translation_en: "mother", translation_jp: "母親" },
    { word: "صحيفة", translation_en: "newspaper", translation_jp: "新聞" },
    { word: "طبيب", translation_en: "physician", translation_jp: "医師" },
    { word: "ليل", translation_en: "night", translation_jp: "夜" },
    { word: "بيضة", translation_en: "ovary", translation_jp: "卵巣" },
    { word: "سكرتير", translation_en: "secretary", translation_jp: "秘書" },
    { word: "فن", translation_en: "art", translation_jp: "美術" },
    { word: "الأرض", translation_en: "earth", translation_jp: "地球" },
    { word: "رفقة", translation_en: "friend", translation_jp: "友人" },
    { word: "إذا", translation_en: "if", translation_jp: "もし" },
    { word: "مطرقة", translation_en: "hammer", translation_jp: "ハンマー" },
    { word: "اهتمام", translation_en: "attention", translation_jp: "注意" },
    { word: "بيئة", translation_en: "beah", translation_jp: "ベア" },
    { word: "عملية جراحية", translation_en: "surgical operation", translation_jp: "手術" },
    { word: "تأمين", translation_en: "insurance", translation_jp: "保険" },
    { word: "صياح", translation_en: "hello", translation_jp: "こんにちは" },
    { word: "مستشفى", translation_en: "hospital", translation_jp: "病院" },
    { word: "محرك", translation_en: "drive", translation_jp: "ドライブ" },
    { word: "فرع", translation_en: "branch", translation_jp: "支店" },
    { word: "أم", translation_en: "mother", translation_jp: "母親" },
    { word: "ابنة", translation_en: "daughter", translation_jp: "娘" },
    { word: "متوسط", translation_en: "medium", translation_jp: "中くらい" },
    { word: "خبرة", translation_en: "experience", translation_jp: "経験" },
    { word: "علاقة غرامية", translation_en: "marital relationship", translation_jp: "夫婦関係" },
    { word: "مسبح", translation_en: "музба", translation_jp: "ムソブガ" },
    { word: "مكتبة", translation_en: "library", translation_jp: "図書館" },
    { word: "سطح", translation_en: "surface", translation_jp: "表面" },
    { word: "حصان", translation_en: "horse", translation_jp: "馬" },
    { word: "عنصر", translation_en: "element", translation_jp: "要素" },
    { word: "انتباه", translation_en: "attention", translation_jp: "注意" },
    { word: "خريطة", translation_en: "map", translation_jp: "地図" },
    { word: "أعمال", translation_en: "business", translation_jp: "仕事" },
    { word: "ضريبة", translation_en: "tax", translation_jp: "税" },
    { word: "نحن", translation_en: "we are", translation_jp: "私たちは" },
    { word: "اكتشاف", translation_en: "discovery", translation_jp: "発見" },
    { word: "دم", translation_en: "tail", translation_jp: "しっぽ" },
    { word: "رصاص", translation_en: "lead", translation_jp: "鉛" },
    { word: "فرقة", translation_en: "band", translation_jp: "バンド" },
    { word: "قوس", translation_en: "bracket", translation_jp: "ブラケット" },
    { word: "موضوع", translation_en: "topic", translation_jp: "トピック" },
    { word: "شهر", translation_en: "month", translation_jp: "月" },
    { word: "امرأة", translation_en: "woman", translation_jp: "女性" },
    { word: "قرية", translation_en: "village", translation_jp: "村" },
    { word: "كنيسة", translation_en: "church", translation_jp: "教会" },
    { word: "قصدير", translation_en: "the intention", translation_jp: "意図" },
    { word: "مساعدة", translation_en: "Help", translation_jp: "ヘルプ" },
    { word: "أصل", translation_en: "asl", translation_jp: "アスル語" },
    { word: "أسلوب", translation_en: "style", translation_jp: "スタイル" },
    { word: "عند", translation_en: "at", translation_jp: "で" },
    { word: "مسكن", translation_en: "the house", translation_jp: "家" },
    { word: "ضباب", translation_en: "fog", translation_jp: "霧" },
    { word: "عصب", translation_en: "anger", translation_jp: "怒り" },
    { word: "فضاء", translation_en: "space", translation_jp: "空間" },
    { word: "عقد", translation_en: "contract", translation_jp: "契約" },
    { word: "ماضي", translation_en: "the past", translation_jp: "過去" },
    { word: "زجاج", translation_en: "glass", translation_jp: "ガラス" },
    { word: "انتخاب", translation_en: "choice", translation_jp: "選択" },
    { word: "ضغط", translation_en: "pressure", translation_jp: "プレッシャー" },
    { word: "مدير", translation_en: "manager", translation_jp: "マネージャー" },
    { word: "حساء", translation_en: "soup", translation_jp: "スープ" },
    { word: "نسخة", translation_en: "copy", translation_jp: "コピー" },
    { word: "الفيلم", translation_en: "the movie", translation_jp: "映画" },
    { word: "لقب", translation_en: "nickname", translation_jp: "ニックネーム" },
    { word: "نصيحة", translation_en: "advice", translation_jp: "アドバイス" },
    { word: "شريعة", translation_en: "Sharia", translation_jp: "シャリーア" },
    { word: "قارب", translation_en: "the boat", translation_jp: "ボート" },
    { word: "صيف", translation_en: "summer", translation_jp: "夏" },
    { word: "بذرة", translation_en: "seed", translation_jp: "シード" },
    { word: "رجل", translation_en: "man", translation_jp: "男" },
    { word: "بين", translation_en: "bin", translation_jp: "ビン" },
    { word: "فيلم", translation_en: "film", translation_jp: "膜" },
    { word: "خيال", translation_en: "imagination", translation_jp: "想像" },
    { word: "نسبة", translation_en: "ratio", translation_jp: "比率" },
    { word: "ابن", translation_en: "Ibn", translation_jp: "イブン" },
    { word: "زيت", translation_en: "oil", translation_jp: "油" },
    { word: "عادة", translation_en: "usually", translation_jp: "いつもの" },
    { word: "فوق", translation_en: "above", translation_jp: "その上" },
    { word: "وصول", translation_en: "reception", translation_jp: "受付" },
    { word: "ﻻ شيء", translation_en: "something", translation_jp: "何か" },
    { word: "ميل", translation_en: "mill", translation_jp: "ミル" },
    { word: "نهر", translation_en: "river", translation_jp: "川" },
    { word: "قطعة", translation_en: "piece", translation_jp: "ピース" },
    { word: "حالة", translation_en: "situation", translation_jp: "状況" },
    { word: "مشروع", translation_en: "legitimate", translation_jp: "正当な" },
    { word: "صحن", translation_en: "the room", translation_jp: "部屋" },
    { word: "مباراة", translation_en: "match", translation_jp: "マッチ" },
    { word: "ضربة", translation_en: "strike", translation_jp: "ストライク" },
    { word: "طلاء", translation_en: "gold", translation_jp: "金" },
    { word: "نموذج تصميم", translation_en: "sample design", translation_jp: "サンプルデザイン" },
    { word: "نابض", translation_en: "pulse", translation_jp: "脈" },
    { word: "حكومة", translation_en: "government", translation_jp: "政府" },
    { word: "قطار", translation_en: "train", translation_jp: "電車" },
    { word: "مشكلة", translation_en: "problem", translation_jp: "問題" },
    { word: "نوع", translation_en: "type", translation_jp: "タイプ" },
    { word: "شقة", translation_en: "Apartment", translation_jp: "アパート" },
    { word: "إضافة", translation_en: "addition", translation_jp: "追加" },
    { word: "كل شيء", translation_en: "all things", translation_jp: "すべてのもの" },
    { word: "فحم", translation_en: "understand", translation_jp: "理解する" },
    { word: "حافة", translation_en: "edge", translation_jp: "角" },
    { word: "خلف", translation_en: "behind", translation_jp: "後ろに" },
    { word: "شفة", translation_en: "lip", translation_jp: "リップ" },
    { word: "سقوط", translation_en: "collapse", translation_jp: "崩壊" },
    { word: "مضاد", translation_en: "anti", translation_jp: "アンチ" },
    { word: "ضبط", translation_en: "capture", translation_jp: "捕獲" },
    { word: "كذبة", translation_en: "lie", translation_jp: "嘘" },
    { word: "بداية", translation_en: "the beginning", translation_jp: "始まり" },
    { word: "نواة فكرة", translation_en: "New idea", translation_jp: "新しいアイデア" },
    { word: "علبة مجوفة", translation_en: "Empty box", translation_jp: "空箱" },
    { word: "بغض النظر عن", translation_en: "don't care", translation_jp: "気にしないでください" },
    { word: "بقرة", translation_en: "Cow", translation_jp: "牛" },
    { word: "قطاع", translation_en: "sector", translation_jp: "セクタ" },
    { word: "تصريح", translation_en: "statement", translation_jp: "声明" },
    { word: "فاكهة", translation_en: "fruit", translation_jp: "フルーツ" },
    { word: "دفع", translation_en: "throw away", translation_jp: "捨てる" },
    { word: "إشارة", translation_en: "signal", translation_jp: "信号" },
    { word: "حدث", translation_en: "happened", translation_jp: "起こった" },
    { word: "خوف", translation_en: "fear", translation_jp: "恐れ" },
    { word: "برهان", translation_en: "Brohan", translation_jp: "ブローハン" },
    { word: "قطرة", translation_en: "drop", translation_jp: "落とす" },
    { word: "سوق", translation_en: "souk", translation_jp: "スーク" },
];

export default records;
