export const records: { word: string; translation_en: string; translation_jp: string }[] = [
	{ word: 'een weg', translation_en: 'a road', translation_jp: '道路' },
	{ word: 'het rundvlees', translation_en: 'the beef', translation_jp: '牛肉' },
	{ word: 'een schaap', translation_en: 'a sheep', translation_jp: '羊' },
	{ word: 'het tapijt', translation_en: 'the carpet', translation_jp: 'カーペット' },
	{ word: 'een ingenieur', translation_en: 'an engineer', translation_jp: 'エンジニア' },
	{ word: 'het konijn', translation_en: 'the rabbit', translation_jp: 'ウサギ' },
	{ word: 'meer', translation_en: 'more', translation_jp: 'もっと' },
	{ word: 'de druif', translation_en: 'the grape', translation_jp: 'ブドウ' },
	{ word: 'misschien', translation_en: 'maybe', translation_jp: '多分' },
	{ word: 'de politie', translation_en: 'the police', translation_jp: '警察' },
	{ word: 'de week', translation_en: 'the week', translation_jp: 'その週' },
	{ word: 'een koe', translation_en: 'a cow', translation_jp: '牛' },
	{ word: 'de vrucht', translation_en: 'the fruit', translation_jp: '果物' },
	{ word: 'een aansteker', translation_en: 'a lighter', translation_jp: 'ライター' },
	{ word: 'geven', translation_en: 'give', translation_jp: '与える' },
	{ word: 'de bus', translation_en: 'the bus', translation_jp: 'バス' },
	{ word: 'het eten', translation_en: 'the food', translation_jp: '食べ物' },
	{ word: 'de etage', translation_en: 'the floor', translation_jp: '床' },
	{ word: 'eindigen', translation_en: 'end', translation_jp: '終わり' },
	{ word: 'slapen', translation_en: 'to sleep', translation_jp: '寝る' },
	{ word: 'de taxi', translation_en: 'the taxi', translation_jp: 'タクシー' },
	{ word: 'het avondeten', translation_en: 'dinner', translation_jp: '夕食' },
	{ word: 'het bloed', translation_en: 'the blood', translation_jp: '血' },
	{ word: 'let op!', translation_en: 'NB!', translation_jp: '注意！' },
	{ word: 'een huis', translation_en: 'a house', translation_jp: '家' },
	{ word: 'de universiteit', translation_en: 'the university', translation_jp: '大学' },
	{ word: 'het blad', translation_en: 'the leaf', translation_jp: '葉' },
	{ word: 'een jaar', translation_en: 'one year', translation_jp: '1年' },
	{ word: 'klein', translation_en: 'small', translation_jp: '小さい' },
	{ word: 'niemand', translation_en: 'no one', translation_jp: '誰も' },
	{ word: 'samen', translation_en: 'together', translation_jp: '一緒に' },
	{ word: 'vol', translation_en: 'full', translation_jp: '満杯' },
	{ word: 'de soep', translation_en: 'the soup', translation_jp: 'スープ' },
	{ word: 'rood', translation_en: 'red', translation_jp: '赤' },
	{ word: 'een mes', translation_en: 'a knife', translation_jp: 'ナイフ' },
	{ word: 'een man', translation_en: 'a man', translation_jp: '男' },
	{ word: 'de muur', translation_en: 'the wall', translation_jp: '壁' },
	{ word: 'de productie', translation_en: 'the production', translation_jp: '生産' },
	{ word: 'de kers', translation_en: 'the cherry', translation_jp: '桜' },
	{ word: 'de vloer', translation_en: 'the floor', translation_jp: '床' },
	{ word: 'het beroep', translation_en: 'the profession', translation_jp: '職業' },
	{ word: 'de boer', translation_en: 'the farmer', translation_jp: '農夫' },
	{ word: 'een wolf', translation_en: 'a wolf', translation_jp: 'オオカミ' },
	{ word: 'de flat', translation_en: 'the apartment', translation_jp: 'アパート' },
	{ word: 'het westen', translation_en: 'the west', translation_jp: '西' },
	{ word: 'aandoen', translation_en: 'to affect', translation_jp: '影響を与える' },
	{
		word: 'ik studeer in Parijs',
		translation_en: 'I study in Paris',
		translation_jp: '私はパリで勉強しています'
	},
	{ word: 'de familie', translation_en: 'the family', translation_jp: '家族' },
	{ word: 'het gordijn', translation_en: 'the curtain', translation_jp: 'カーテン' },
	{ word: 'het adres', translation_en: 'the address', translation_jp: '住所' },
	{ word: 'de zus', translation_en: 'the sister', translation_jp: '妹' },
	{ word: 'aansteken', translation_en: 'light', translation_jp: 'ライト' },
	{ word: 'een grootmoeder', translation_en: 'a grandmother', translation_jp: 'おばあちゃん' },
	{ word: 'een station', translation_en: 'a station', translation_jp: '駅' },
	{ word: 'de koffie', translation_en: 'the coffee', translation_jp: 'コーヒー' },
	{ word: 'de mug', translation_en: 'the mosquito', translation_jp: '蚊' },
	{ word: 'het hart', translation_en: 'the heart', translation_jp: '心' },
	{ word: 'het toilet', translation_en: 'the toilet', translation_jp: 'トイレ' },
	{ word: 'het goud', translation_en: 'the gold', translation_jp: '金' },
	{ word: 'de feestdag', translation_en: 'the holiday', translation_jp: '休日' },
	{
		word: 'ik ben twintig jaar',
		translation_en: 'I am twenty years old',
		translation_jp: '私は二十歳です'
	},
	{ word: 'de echtgenote', translation_en: 'the wife', translation_jp: '妻' },
	{ word: 'sterk', translation_en: 'strong', translation_jp: '強い' },
	{ word: 'buitenlands', translation_en: 'foreign', translation_jp: '外国' },
	{ word: 'de bloem', translation_en: 'the flower', translation_jp: '花' },
	{ word: 'de vakbond', translation_en: 'the union', translation_jp: '組合' },
	{ word: 'een jurk', translation_en: 'a dress', translation_jp: 'ドレス' },
	{ word: 'besturen', translation_en: 'control', translation_jp: 'コントロール' },
	{ word: 'een beroep', translation_en: 'a profession', translation_jp: '職業' },
	{ word: 'een broek', translation_en: 'pants', translation_jp: 'パンツ' },
	{ word: 'afwezig', translation_en: 'absent', translation_jp: '不在' },
	{ word: 'schoon', translation_en: 'beautiful', translation_jp: '美しい' },
	{ word: 'gaan', translation_en: 'to go', translation_jp: '持ち帰り' },
	{ word: 'een jongeman', translation_en: 'a young man', translation_jp: '若い男' },
	{ word: 'het schaap', translation_en: 'the sheep', translation_jp: '羊' },
	{ word: 'een tapijt', translation_en: 'a carpet', translation_jp: 'カーペット' },
	{ word: 'een konijn', translation_en: 'a rabbit', translation_jp: 'ウサギ' },
	{ word: 'een pan', translation_en: 'a pan', translation_jp: '鍋' },
	{ word: 'ontwaken', translation_en: 'awaken', translation_jp: '目覚める' },
	{ word: 'alstublieft', translation_en: 'Please', translation_jp: 'お願いします' },
	{ word: 'de priester', translation_en: 'the priest', translation_jp: '司祭' },
	{ word: 'de leerkracht', translation_en: 'the teacher', translation_jp: '先生' },
	{ word: 'we', translation_en: 'we', translation_jp: '私たちは' },
	{ word: 'de minuut', translation_en: 'the minute', translation_jp: 'その分' },
	{ word: 'de grootmoeder', translation_en: 'the grandmother', translation_jp: 'おばあさん' },
	{ word: 'een vork', translation_en: 'a fork', translation_jp: 'フォーク' },
	{ word: 'drinken', translation_en: 'drinks', translation_jp: '飲み物' },
	{ word: 'de kerk', translation_en: 'the church', translation_jp: '教会' },
	{ word: 'nemen', translation_en: 'to take', translation_jp: '取る' },
	{ word: 'wonen', translation_en: 'live', translation_jp: 'ライブ' },
	{ word: 'het vlees', translation_en: 'the meat', translation_jp: '肉' },
	{ word: 'daar', translation_en: 'there', translation_jp: 'そこには' },
	{ word: 'jong', translation_en: 'young', translation_jp: '若い' },
	{ word: 'het vuur', translation_en: 'the fire', translation_jp: '火' },
	{ word: 'een handtas', translation_en: 'a handbag', translation_jp: 'ハンドバッグ' },
	{ word: 'de haren', translation_en: 'the hair', translation_jp: '髪' },
	{ word: 'herhalen', translation_en: 'repeat', translation_jp: '繰り返す' },
	{ word: 'morgen', translation_en: 'tomorrow', translation_jp: '明日' },
	{ word: 'vrij', translation_en: 'free', translation_jp: '無料' },
	{ word: 'de dokter', translation_en: 'the doctor', translation_jp: '医者' },
	{ word: '(de) morgen', translation_en: '(the) morning', translation_jp: '（その）朝' },
	{ word: 'een kast', translation_en: 'a closet', translation_jp: 'クローゼット' },
	{ word: 'God', translation_en: 'God', translation_jp: '神' },
	{ word: 'een ziekenhuis', translation_en: 'a hospital', translation_jp: '病院' },
	{ word: 'een grens', translation_en: 'a border', translation_jp: '国境' },
	{ word: 'een deken', translation_en: 'a blanket', translation_jp: '毛布' },
	{ word: 'begrijpen', translation_en: 'understand', translation_jp: '理解する' },
	{ word: 'nooit', translation_en: 'never', translation_jp: '一度もない' },
	{ word: 'de jas', translation_en: 'the jacket', translation_jp: 'ジャケット' },
	{ word: 'de dood', translation_en: 'death', translation_jp: '死' },
	{ word: '(de) ochtend', translation_en: '(the) morning', translation_jp: '（その）朝' },
	{ word: 'de postzegel', translation_en: 'the postage stamp', translation_jp: '切手' },
	{ word: 'een uur', translation_en: 'one hour', translation_jp: '1時間' },
	{ word: 'een zuigeling', translation_en: 'an infant', translation_jp: '幼児' },
	{ word: 'een reis', translation_en: 'a journey', translation_jp: '旅' },
	{ word: 'de kop', translation_en: 'the head', translation_jp: '頭' },
	{ word: 'vals', translation_en: 'false', translation_jp: '間違い' },
	{ word: 'het middageten', translation_en: 'the lunch', translation_jp: '昼食' },
	{ word: 'de handelaar', translation_en: 'the trader', translation_jp: 'トレーダー' },
	{ word: 'de militair', translation_en: 'the soldier', translation_jp: '兵士' },
	{ word: 'de haven', translation_en: 'the harbour', translation_jp: '港' },
	{ word: 'bellen', translation_en: 'to call', translation_jp: '電話する' },
	{ word: 'het vak', translation_en: 'the profession', translation_jp: '職業' },
	{ word: 'de liefde', translation_en: 'the love', translation_jp: '愛' },
	{ word: 'wakker worden', translation_en: 'wake up', translation_jp: '起きろ' },
	{ word: 'de broer', translation_en: 'the brother', translation_jp: '兄弟' },
	{ word: 'een maaltijd', translation_en: 'a meal', translation_jp: '食事' },
	{ word: 'de appel', translation_en: 'the apple', translation_jp: 'リンゴ' },
	{ word: 'een fiets', translation_en: 'a bicycle', translation_jp: '自転車' },
	{ word: 'een examen', translation_en: 'an exam', translation_jp: '試験' },
	{ word: 'de verloofde', translation_en: 'the fiancée', translation_jp: '婚約者' },
	{ word: 'de huid', translation_en: 'the skin', translation_jp: '皮膚' },
	{ word: 'de keuken', translation_en: 'the kitchen', translation_jp: 'キッチン' },
	{ word: 'de religie', translation_en: 'the religion', translation_jp: '宗教' },
	{ word: 'het lokaal', translation_en: 'the room', translation_jp: '部屋' },
	{ word: 'een trein', translation_en: 'a train', translation_jp: '電車' },
	{ word: 'het appartement', translation_en: 'the apartment', translation_jp: 'アパート' },
	{ word: 'de vrede', translation_en: 'the peace', translation_jp: '平和' },
	{ word: 'ik weet het niet', translation_en: "I don't know", translation_jp: 'わからない' },
	{ word: 'de wc', translation_en: 'the toilet', translation_jp: 'トイレ' },
	{ word: 'doven', translation_en: 'deaf', translation_jp: '聴覚障害者' },
	{ word: 'duur', translation_en: 'duration', translation_jp: '間隔' },
	{ word: 'de belastingen', translation_en: 'the taxes', translation_jp: '税金' },
	{ word: 'een tafel', translation_en: 'a table', translation_jp: 'テーブル' },
	{ word: 'een contract', translation_en: 'a contract', translation_jp: '契約' },
	{ word: 'maandag', translation_en: 'Monday', translation_jp: '月曜日' },
	{ word: 'het licht', translation_en: 'the light', translation_jp: '光' },
	{ word: 'aids', translation_en: 'AIDS', translation_jp: 'エイズ' },
	{ word: 'de maan', translation_en: 'the moon', translation_jp: '月' },
	{ word: 'de arts', translation_en: 'the doctor', translation_jp: '医者' },
	{ word: 'een bank', translation_en: 'a sofa', translation_jp: 'ソファ' },
	{ word: 'een televisie', translation_en: 'a television', translation_jp: 'テレビ' },
	{ word: 'een bad nemen', translation_en: 'take a bath', translation_jp: 'お風呂に入る' },
	{ word: 'ik', translation_en: 'I', translation_jp: '私' },
	{ word: 'een vriend', translation_en: 'a friend', translation_jp: '友人' },
	{ word: 'het examen', translation_en: 'the exam', translation_jp: '試験' },
	{ word: 'lang', translation_en: 'long', translation_jp: '長さ' },
	{ word: 'een buurman', translation_en: 'a neighbor', translation_jp: '隣人' },
	{ word: 'een blad', translation_en: 'a leaf', translation_jp: '葉っぱ' },
	{ word: 'het jaar', translation_en: 'the year', translation_jp: '年' },
	{ word: 'een muis', translation_en: 'a mouse', translation_jp: 'マウス' },
	{ word: 'een lokaal', translation_en: 'a local', translation_jp: '地元の' },
	{ word: 'spreken', translation_en: 'speak', translation_jp: '話す' },
	{ word: 'laat', translation_en: 'leave', translation_jp: '離れる' },
	{ word: 'veraf', translation_en: 'far', translation_jp: '遠い' },
	{ word: 'de benzine', translation_en: 'the gasoline', translation_jp: 'ガソリン' },
	{ word: 'de cultuur', translation_en: 'the culture', translation_jp: '文化' },
	{ word: 'een oma', translation_en: 'a grandmother', translation_jp: 'おばあちゃん' },
	{ word: 'de dag', translation_en: 'the day', translation_jp: 'その日' },
	{ word: 'een verkoudheid', translation_en: 'a cold', translation_jp: '風邪' },
	{ word: 'het leven', translation_en: 'life', translation_jp: '人生' },
	{ word: 'aangenaam!', translation_en: 'nice to meet you!', translation_jp: 'はじめまして！' },
	{ word: 'de brief', translation_en: 'the letter', translation_jp: '手紙' },
	{ word: 'vreemd', translation_en: 'foreign', translation_jp: '外国' },
	{ word: 'de handel', translation_en: 'the trade', translation_jp: '貿易' },
	{ word: 'een taart', translation_en: 'a cake', translation_jp: 'ケーキ' },
	{ word: 'een hoed', translation_en: 'a hat', translation_jp: '帽子' },
	{ word: 'het plafond', translation_en: 'the ceiling', translation_jp: '天井' },
	{ word: 'dicht doen', translation_en: 'close', translation_jp: '近い' },
	{ word: 'de voet', translation_en: 'the foot', translation_jp: '足' },
	{ word: 'de verkoudheid', translation_en: 'the cold', translation_jp: '寒さ' },
	{ word: 'uitgaan', translation_en: 'going out', translation_jp: '出かける' },
	{ word: 'het theater', translation_en: 'the theater', translation_jp: '劇場' },
	{ word: 'een student', translation_en: 'a student', translation_jp: '学生' },
	{ word: 'een kip', translation_en: 'a chicken', translation_jp: '鶏' },
	{ word: 'een vertaler', translation_en: 'a translator', translation_jp: '翻訳者' },
	{ word: 'zondag', translation_en: 'Sunday', translation_jp: '日曜日' },
	{ word: 'de huur', translation_en: 'the rent', translation_jp: '家賃' },
	{ word: 'een groente', translation_en: 'a vegetable', translation_jp: '野菜' },
	{ word: 'het kaartje', translation_en: 'the ticket', translation_jp: 'チケット' },
	{ word: 'de koelkast', translation_en: 'the refrigerator', translation_jp: '冷蔵庫' },
	{ word: 'de auto', translation_en: 'the car', translation_jp: '車' },
	{ word: 'de rijst', translation_en: 'the rice', translation_jp: '米' },
	{ word: 'de brug', translation_en: 'the bridge', translation_jp: '橋' },
	{ word: 'de sokken', translation_en: 'the socks', translation_jp: '靴下' },
	{ word: 'het leger', translation_en: 'the army', translation_jp: '軍隊' },
	{ word: 'grijs', translation_en: 'gray', translation_jp: 'グレー' },
	{ word: 'de azijn', translation_en: 'the vinegar', translation_jp: '酢' },
	{ word: 'een ui', translation_en: 'an onion', translation_jp: '玉ねぎ' },
	{ word: 'hier', translation_en: 'here', translation_jp: 'ここ' },
	{
		word: 'ik woon in een studentenhuis',
		translation_en: 'I live in a student house',
		translation_jp: '私は学生寮に住んでいます'
	},
	{ word: 'een kamer', translation_en: 'a room', translation_jp: '部屋' },
	{ word: 'het huis', translation_en: 'the house', translation_jp: '家' },
	{ word: 'bezet', translation_en: 'busy', translation_jp: '忙しい' },
	{ word: 'een patiënt', translation_en: 'a patient', translation_jp: '患者' },
	{ word: 'een vlieg', translation_en: 'a fly', translation_jp: 'ハエ' },
	{ word: 'de mond', translation_en: 'the mouth', translation_jp: '口' },
	{
		word: 'ik heet Dorenda',
		translation_en: 'My name is Dorenda',
		translation_jp: '私の名前はドレンダです'
	},
	{ word: 'een zakdoek', translation_en: 'a handkerchief', translation_jp: 'ハンカチ' },
	{ word: 'te veel', translation_en: 'too many', translation_jp: '多すぎる' },
	{ word: 'het mes', translation_en: 'the knife', translation_jp: 'ナイフ' },
	{ word: 'het kippenvlees', translation_en: 'the chicken meat', translation_jp: '鶏肉' },
	{ word: '(de) namiddag', translation_en: '(the) afternoon', translation_jp: '（その）午後' },
	{ word: 'de minister', translation_en: 'the minister', translation_jp: '大臣' },
	{ word: 'proberen', translation_en: 'try', translation_jp: '試す' },
	{ word: 'ik wil...', translation_en: 'I do...', translation_jp: '私はします...' },
	{ word: 'de koopman', translation_en: 'the merchant', translation_jp: '商人' },
	{ word: 'het koekje', translation_en: 'the cookie', translation_jp: 'クッキー' },
	{ word: 'een dochter', translation_en: 'a daughter', translation_jp: '娘' },
	{ word: 'de man', translation_en: 'the man', translation_jp: 'その男' },
	{ word: 'uitdoen', translation_en: 'take off', translation_jp: '脱ぐ' },
	{ word: 'snel', translation_en: 'quickly', translation_jp: '素早く' },
	{ word: 'een vlinder', translation_en: 'a butterfly', translation_jp: '蝶' },
	{ word: 'stoppen', translation_en: 'fuses', translation_jp: 'ヒューズ' },
	{ word: 'de aardappel', translation_en: 'the potato', translation_jp: 'ジャガイモ' },
	{ word: 'mevrouw', translation_en: 'Madam', translation_jp: 'マダム' },
	{ word: 'het gaat goed met me', translation_en: "I'm doing well", translation_jp: '元気です' },
	{ word: 'de koe', translation_en: 'the cow', translation_jp: '牛' },
	{ word: 'niet waar', translation_en: 'not true', translation_jp: '真実ではない' },
	{ word: 'de apotheek', translation_en: 'the pharmacy', translation_jp: '薬局' },
	{ word: 'onjuist', translation_en: 'incorrect', translation_jp: '正しくない' },
	{ word: 'de weg', translation_en: 'the road', translation_jp: '道路' },
	{ word: 'een bus', translation_en: 'a bus', translation_jp: 'バス' },
	{ word: 'roze', translation_en: 'pink', translation_jp: 'ピンク' },
	{ word: 'rechts', translation_en: 'right', translation_jp: '右' },
	{ word: 'de broek', translation_en: 'the pants', translation_jp: 'パンツ' },
	{ word: 'de kunst', translation_en: 'the art', translation_jp: '芸術' },
	{ word: 'de bril', translation_en: 'the glasses', translation_jp: 'メガネ' },
	{ word: 'openen', translation_en: 'open', translation_jp: '開ける' },
	{ word: 'wit', translation_en: 'white', translation_jp: '白' },
	{ word: 'de vooruitgang', translation_en: 'the progress', translation_jp: '進歩' },
	{ word: 'kanker', translation_en: 'cancer', translation_jp: '癌' },
	{ word: 'een bloem', translation_en: 'a flower', translation_jp: '花' },
	{ word: 'de bruiloft', translation_en: 'the wedding', translation_jp: '結婚式' },
	{ word: 'de brandweerman', translation_en: 'the fireman', translation_jp: '消防士' },
	{ word: 'een spiegel', translation_en: 'a mirror', translation_jp: '鏡' },
	{ word: 'zetten', translation_en: 'to make', translation_jp: '作る' },
	{ word: 'het brood', translation_en: 'the bread', translation_jp: 'パン' },
	{ word: 'de zakenman', translation_en: 'the businessman', translation_jp: 'ビジネスマン' },
	{ word: 'bouwen', translation_en: 'build', translation_jp: '建てる' },
	{ word: 'kosten', translation_en: 'costs', translation_jp: '費用' },
	{ word: 'het wisselkantoor', translation_en: 'the exchange office', translation_jp: '両替所' },
	{ word: 'ander', translation_en: 'other', translation_jp: '他の' },
	{ word: 'de pan', translation_en: 'the pan', translation_jp: '鍋' },
	{ word: 'een sigaret', translation_en: 'a cigarette', translation_jp: 'タバコ' },
	{ word: 'het vliegtuig', translation_en: 'the plane', translation_jp: '飛行機' },
	{ word: 'een bord', translation_en: 'a plate', translation_jp: '皿' },
	{ word: 'het dorp', translation_en: 'the village', translation_jp: '村' },
	{ word: 'een peer', translation_en: 'a pear', translation_jp: '梨' },
	{ word: 'een persoon', translation_en: 'a person', translation_jp: '人' },
	{ word: 'verstaan', translation_en: 'to hear', translation_jp: '聞く' },
	{ word: 'een seconde', translation_en: 'one second', translation_jp: '1秒' },
	{ word: 'de hemel', translation_en: 'heaven', translation_jp: '天国' },
	{ word: 'zich herinneren', translation_en: 'remember', translation_jp: '覚えて' },
	{ word: 'vergeten', translation_en: 'forget', translation_jp: '忘れる' },
	{ word: 'de ouders', translation_en: 'the parents', translation_jp: '両親' },
	{ word: 'de vriend', translation_en: 'the friend', translation_jp: '友人' },
	{ word: 'zijn', translation_en: 'are', translation_jp: 'は' },
	{ word: 'een appartement', translation_en: 'an apartment', translation_jp: 'アパート' },
	{ word: 'altijd', translation_en: 'always', translation_jp: 'いつも' },
	{ word: 'de fabriek', translation_en: 'the factory', translation_jp: '工場' },
	{ word: 'woensdag', translation_en: 'Wednesday', translation_jp: '水曜日' },
	{ word: 'een dokter', translation_en: 'a doctor', translation_jp: '医者' },
	{ word: 'rechtdoor', translation_en: 'straight ahead', translation_jp: 'まっすぐ' },
	{ word: 'een fles', translation_en: 'a bottle', translation_jp: 'ボトル' },
	{ word: 'een bron', translation_en: 'a source', translation_jp: '情報源' },
	{ word: 'een vliegtuig', translation_en: 'an airplane', translation_jp: '飛行機' },
	{ word: 'tonen', translation_en: 'to show', translation_jp: '見せる' },
	{ word: 'de koekenpan', translation_en: 'the frying pan', translation_jp: 'フライパン' },
	{ word: 'snappen', translation_en: 'understand', translation_jp: '理解する' },
	{ word: 'praten', translation_en: 'talk', translation_jp: '話す' },
	{ word: 'een ster', translation_en: 'a star', translation_jp: '星' },
	{ word: 'een mug', translation_en: 'a mosquito', translation_jp: '蚊' },
	{ word: 'verzenden', translation_en: 'send', translation_jp: '送信' },
	{ word: 'een koekje', translation_en: 'a cookie', translation_jp: 'クッキー' },
	{ word: 'waar', translation_en: 'Where', translation_jp: 'どこ' },
	{ word: 'de machine', translation_en: 'the machine', translation_jp: '機械' },
	{ word: 'een land', translation_en: 'a country', translation_jp: '国' },
	{ word: 'de lucht', translation_en: 'the air', translation_jp: '空気' },
	{ word: 'weten', translation_en: 'know', translation_jp: '知る' },
	{ word: 'een computer', translation_en: 'a computer', translation_jp: 'コンピューター' },
	{ word: 'moe', translation_en: 'tired', translation_jp: '疲れた' },
	{
		word: 'een wisselkantoor',
		translation_en: 'a currency exchange office',
		translation_jp: '外貨両替所'
	},
	{ word: 'een diploma', translation_en: 'a diploma', translation_jp: '卒業証書' },
	{ word: 'een leerkracht', translation_en: 'a teacher', translation_jp: '先生' },
	{ word: 'houden van', translation_en: 'love', translation_jp: '愛' },
	{ word: 'de schrijver', translation_en: 'the writer', translation_jp: '作家' },
	{ word: 'de strijd', translation_en: 'the battle', translation_jp: '戦い' },
	{ word: 'de richting', translation_en: 'the direction', translation_jp: '方向' },
	{ word: 'het drinken', translation_en: 'the drinking', translation_jp: '飲酒' },
	{ word: 'de taart', translation_en: 'the cake', translation_jp: 'ケーキ' },
	{ word: 'de avond', translation_en: 'the evening', translation_jp: '夕方' },
	{ word: 'nogmaals', translation_en: 'once more', translation_jp: 'もう一度' },
	{ word: 'de klas', translation_en: 'the class', translation_jp: 'クラス' },
	{ word: 'hoi!', translation_en: 'hi!', translation_jp: 'こんにちは！' },
	{ word: 'doen', translation_en: 'doing', translation_jp: 'やってる' },
	{ word: 'de kamer', translation_en: 'the room', translation_jp: '部屋' },
	{ word: 'de onderneming', translation_en: 'the company', translation_jp: '会社' },
	{ word: 'de vlieg', translation_en: 'the fly', translation_jp: 'ハエ' },
	{ word: 'een minuut', translation_en: 'one minute', translation_jp: '1分' },
	{ word: 'de politiek', translation_en: 'politics', translation_jp: '政治' },
	{ word: 'meneer', translation_en: 'sir', translation_jp: 'お客様' },
	{ word: 'de stad', translation_en: 'the city', translation_jp: '街' },
	{ word: 'de tand', translation_en: 'the tooth', translation_jp: '歯' },
	{ word: 'het land', translation_en: 'the country', translation_jp: '国' },
	{ word: 'de kleren', translation_en: 'the clothes', translation_jp: '服' },
	{ word: 'het strand', translation_en: 'the beach', translation_jp: 'ビーチ' },
	{ word: 'de abrikoos', translation_en: 'the apricot', translation_jp: 'アプリコット' },
	{ word: 'een onderneming', translation_en: 'an enterprise', translation_jp: '企業' },
	{ word: 'een medicijn', translation_en: 'a medicine', translation_jp: '薬' },
	{ word: 'de economie', translation_en: 'the economy', translation_jp: '経済' },
	{ word: 'de mensen', translation_en: 'the people', translation_jp: '人々' },
	{ word: 'de berg', translation_en: 'the mountain', translation_jp: '山' },
	{ word: 'ik kan niet', translation_en: "I can't", translation_jp: '私はできません' },
	{ word: 'het bord', translation_en: 'the board', translation_jp: 'ボード' },
	{ word: 'de kaas', translation_en: 'the cheese', translation_jp: 'チーズ' },
	{ word: 'een kop', translation_en: 'a cup', translation_jp: '一杯' },
	{ word: 'zenden', translation_en: 'send', translation_jp: '送信' },
	{ word: 'een vak', translation_en: 'a subject', translation_jp: '主題' },
	{ word: 'hebben', translation_en: 'to have', translation_jp: '持つ' },
	{ word: 'een brief', translation_en: 'a letter', translation_jp: '手紙' },
	{ word: 'een dorp', translation_en: 'a village', translation_jp: '村' },
	{ word: 'een venster', translation_en: 'a window', translation_jp: '窓' },
	{ word: 'de deur', translation_en: 'the door', translation_jp: 'ドア' },
	{ word: 'een telefoon', translation_en: 'a telephone', translation_jp: '電話' },
	{ word: 'hallo!', translation_en: 'Hello!', translation_jp: 'こんにちは！' },
	{ word: 'het uur', translation_en: 'the hour', translation_jp: '時間' },
	{ word: 'een lamp', translation_en: 'a lamp', translation_jp: 'ランプ' },
	{ word: 'de tafel', translation_en: 'the table', translation_jp: 'テーブル' },
	{ word: 'voor', translation_en: 'for', translation_jp: 'のために' },
	{ word: 'de jongedame', translation_en: 'the young lady', translation_jp: '若い女性' },
	{ word: 'een baby', translation_en: 'a baby', translation_jp: '赤ちゃん' },
	{ word: 'een wolk', translation_en: 'a cloud', translation_jp: '雲' },
	{ word: 'dinsdag', translation_en: 'Tuesday', translation_jp: '火曜日' },
	{ word: 'de kool', translation_en: 'the cabbage', translation_jp: 'キャベツ' },
	{ word: 'de trein', translation_en: 'the train', translation_jp: '電車' },
	{ word: 'de collegezaal', translation_en: 'the lecture hall', translation_jp: '講堂' },
	{ word: 'het ziekenhuis', translation_en: 'the hospital', translation_jp: '病院' },
	{ word: 'de fiets', translation_en: 'the bicycle', translation_jp: '自転車' },
	{ word: 'een appel', translation_en: 'an apple', translation_jp: 'リンゴ' },
	{ word: 'leren', translation_en: 'learn', translation_jp: '学ぶ' },
	{ word: 'de kip', translation_en: 'the chicken', translation_jp: '鶏' },
	{ word: 'de zoon', translation_en: 'the son', translation_jp: '息子' },
	{ word: 'nieuw', translation_en: 'new', translation_jp: '新しい' },
	{ word: 'vrijdag', translation_en: 'Friday', translation_jp: '金曜日' },
	{ word: 'de sleutel', translation_en: 'the key', translation_jp: '鍵' },
	{ word: 'liefhebben', translation_en: 'to love', translation_jp: '愛すること' },
	{ word: 'een lucifer', translation_en: 'a match', translation_jp: '試合' },
	{ word: 'de neus', translation_en: 'the nose', translation_jp: '鼻' },
	{ word: 'uitzetten', translation_en: 'to expand', translation_jp: '拡大する' },
	{ word: 'het hoofd', translation_en: 'the head', translation_jp: '頭' },
	{ word: 'een ei', translation_en: 'an egg', translation_jp: '卵' },
	{ word: 'de hond', translation_en: 'the dog', translation_jp: '犬' },
	{
		word: 'het is nodig...',
		translation_en: 'it is necessary...',
		translation_jp: 'これは必要である...'
	},
	{ word: 'de boom', translation_en: 'the tree', translation_jp: '木' },
	{ word: 'sorry', translation_en: 'Sorry', translation_jp: 'ごめん' },
	{ word: 'een politieagent', translation_en: 'a police officer', translation_jp: '警察官' },
	{ word: 'de zeep', translation_en: 'the soap', translation_jp: '石鹸' },
	{ word: 'de deken', translation_en: 'the blanket', translation_jp: '毛布' },
	{ word: 'de grens', translation_en: 'the border', translation_jp: '国境' },
	{ word: 'een dag', translation_en: 'a day', translation_jp: '一日' },
	{ word: 'de oma', translation_en: 'the grandmother', translation_jp: 'おばあさん' },
	{ word: 'een vrucht', translation_en: 'a fruit', translation_jp: '果物' },
	{ word: 'de soldaat', translation_en: 'the soldier', translation_jp: '兵士' },
	{ word: 'de handdoek', translation_en: 'the towel', translation_jp: 'タオル' },
	{ word: 'de wind', translation_en: 'the wind', translation_jp: '風' },
	{ word: 'een arbeider', translation_en: 'a worker', translation_jp: '労働者' },
	{ word: 'de natuur', translation_en: 'nature', translation_jp: '自然' },
	{ word: 'internet', translation_en: 'internet', translation_jp: 'インターネット' },
	{ word: 'een haven', translation_en: 'a harbour', translation_jp: '港' },
	{ word: 'de koning', translation_en: 'the king', translation_jp: '王' },
	{ word: 'de hand', translation_en: 'the hand', translation_jp: '手' },
	{ word: 'veel', translation_en: 'a lot of', translation_jp: 'たくさんの' },
	{ word: 'mooi', translation_en: 'Nice', translation_jp: 'ニース' },
	{ word: 'de citroen', translation_en: 'the lemon', translation_jp: 'レモン' },
	{ word: 'lezen', translation_en: 'read', translation_jp: '読む' },
	{ word: 'het overhemd', translation_en: 'the shirt', translation_jp: 'シャツ' },
	{ word: 'een collegezaal', translation_en: 'a lecture hall', translation_jp: '講堂' },
	{ word: 'de ingang', translation_en: 'the entrance', translation_jp: '入り口' },
	{ word: 'een professor', translation_en: 'a professor', translation_jp: '教授' },
	{ word: 'erg', translation_en: 'terribly', translation_jp: 'ひどく' },
	{ word: 'doei!', translation_en: 'bye!', translation_jp: 'さよなら！' },
	{ word: 'een school', translation_en: 'a school', translation_jp: '学校' },
	{ word: 'het huwelijk', translation_en: 'the marriage', translation_jp: '結婚' },
	{ word: 'zwart', translation_en: 'black', translation_jp: '黒' },
	{ word: 'blauw', translation_en: 'blue', translation_jp: '青' },
	{ word: 'een arts', translation_en: 'a doctor', translation_jp: '医者' },
	{ word: 'de bij', translation_en: 'the bee', translation_jp: 'ミツバチ' },
	{ word: 'studeren', translation_en: 'study', translation_jp: '勉強' },
	{ word: 'de jongeman', translation_en: 'the young man', translation_jp: '若い男' },
	{ word: 'de kaart', translation_en: 'the map', translation_jp: '地図' },
	{ word: 'een schip', translation_en: 'a ship', translation_jp: '船' },
	{ word: 'een priester', translation_en: 'a priest', translation_jp: '司祭' },
	{ word: 'de vlinder', translation_en: 'the butterfly', translation_jp: '蝶' },
	{ word: 'de bank', translation_en: 'the bank', translation_jp: '銀行' },
	{ word: 'een dier', translation_en: 'an animal', translation_jp: '動物' },
	{ word: 'de gezondheid', translation_en: 'health', translation_jp: '健康' },
	{ word: 'het been', translation_en: 'the leg', translation_jp: '脚' },
	{ word: 'goedenavond', translation_en: 'Good evening', translation_jp: 'こんばんは' },
	{ word: 'welkom!', translation_en: 'Welcome!', translation_jp: 'いらっしゃいませ！' },
	{ word: 'een bed', translation_en: 'a bed', translation_jp: 'ベッド' },
	{ word: 'de mosterd', translation_en: 'the mustard', translation_jp: 'マスタード' },
	{ word: 'de zakdoek', translation_en: 'the handkerchief', translation_jp: 'ハンカチ' },
	{ word: 'beginnen', translation_en: 'start', translation_jp: '始める' },
	{ word: 'een wet', translation_en: 'a law', translation_jp: '法律' },
	{ word: 'de landbouw', translation_en: 'agriculture', translation_jp: '農業' },
	{ word: 'de opa', translation_en: 'the grandfather', translation_jp: '祖父' },
	{ word: 'een glas', translation_en: 'a glass', translation_jp: 'グラス' },
	{ word: 'het geld', translation_en: 'the money', translation_jp: 'お金' },
	{ word: 'een koekenpan', translation_en: 'a frying pan', translation_jp: 'フライパン' },
	{ word: 'het contract', translation_en: 'the contract', translation_jp: '契約書' },
	{ word: 'een restaurant', translation_en: 'a restaurant', translation_jp: 'レストラン' },
	{ word: 'de mais', translation_en: 'the corn', translation_jp: 'トウモロコシ' },
	{ word: 'de beurs', translation_en: 'the stock exchange', translation_jp: '証券取引所' },
	{ word: 'een koopman', translation_en: 'a merchant', translation_jp: '商人' },
	{ word: 'de dochter', translation_en: 'the daughter', translation_jp: '娘' },
	{ word: 'de vrouw', translation_en: 'the woman', translation_jp: '女性' },
	{ word: 'het vloerkleed', translation_en: 'the carpet', translation_jp: 'カーペット' },
	{ word: 'de reis', translation_en: 'the journey', translation_jp: '旅' },
	{ word: 'verliezen', translation_en: 'to lose', translation_jp: '失うこと' },
	{ word: 'de pers', translation_en: 'the press', translation_jp: '報道陣' },
	{ word: 'een feestdag', translation_en: 'a holiday', translation_jp: '休日' },
	{ word: 'de spiegel', translation_en: 'the mirror', translation_jp: '鏡' },
	{ word: 'de markt', translation_en: 'the market', translation_jp: '市場' },
	{ word: 'een docent', translation_en: 'a teacher', translation_jp: '先生' },
	{ word: 'iedereen', translation_en: 'everyone', translation_jp: 'みんな' },
	{ word: 'een staat', translation_en: 'a state', translation_jp: '状態' },
	{ word: 'nog', translation_en: 'yet', translation_jp: 'まだ' },
	{ word: 'de knoflook', translation_en: 'the garlic', translation_jp: 'ニンニク' },
	{ word: 'de kast', translation_en: 'the closet', translation_jp: 'クローゼット' },
	{ word: 'een eiland', translation_en: 'an island', translation_jp: '島' },
	{ word: 'de tabak', translation_en: 'the tobacco', translation_jp: 'タバコ' },
	{ word: 'graag gedaan', translation_en: "Don't mention it", translation_jp: 'どういたしまして' },
	{ word: 'zich baden', translation_en: 'bathe', translation_jp: '入浴' },
	{ word: 'de uitgang', translation_en: 'the exit', translation_jp: '出口' },
	{ word: 'de rekening', translation_en: 'the bill', translation_jp: '請求書' },
	{ word: 'de tomaat', translation_en: 'the tomato', translation_jp: 'トマト' },
	{ word: 'jullie', translation_en: 'you', translation_jp: 'あなた' },
	{ word: 'een brug', translation_en: 'a bridge', translation_jp: '橋' },
	{ word: 'een auto', translation_en: 'a car', translation_jp: '車' },
	{ word: 'laten zien', translation_en: 'to show', translation_jp: '見せる' },
	{ word: 'lekker', translation_en: 'Tasty', translation_jp: '美味しい' },
	{ word: 'de persoon', translation_en: 'the person', translation_jp: 'その人' },
	{ word: 'het werk', translation_en: 'the work', translation_jp: '作品' },
	{ word: 'de seconde', translation_en: 'the second', translation_jp: '2番目の' },
	{ word: 'de straat', translation_en: 'the street', translation_jp: '通り' },
	{ word: 'vragen', translation_en: 'to ask', translation_jp: '尋ねる' },
	{ word: 'het diploma', translation_en: 'the diploma', translation_jp: '卒業証書' },
	{ word: 'helpen', translation_en: 'to help', translation_jp: '助けるために' },
	{ word: 'de hoed', translation_en: 'the hat', translation_jp: '帽子' },
	{ word: 'aanzetten', translation_en: 'turn on', translation_jp: 'オンにする' },
	{ word: 'geel', translation_en: 'yellow', translation_jp: '黄色' },
	{ word: 'een voet', translation_en: 'a foot', translation_jp: '足' },
	{ word: 'het eiland', translation_en: 'the island', translation_jp: '島' },
	{ word: 'weinig', translation_en: 'few', translation_jp: '少し' },
	{ word: 'zaterdag', translation_en: 'Saturday', translation_jp: '土曜日' },
	{ word: 'de sigaret', translation_en: 'the cigarette', translation_jp: 'タバコ' },
	{ word: 'goed', translation_en: 'Good', translation_jp: '良い' },
	{ word: 'antwoorden', translation_en: 'answers', translation_jp: '答え' },
	{ word: 'de schaar', translation_en: 'the scissors', translation_jp: 'はさみ' },
	{ word: 'koud', translation_en: 'cold', translation_jp: '寒い' },
	{ word: 'zich bevinden', translation_en: 'are located', translation_jp: '位置しています' },
	{ word: 'een grootvader', translation_en: 'a grandfather', translation_jp: '祖父' },
	{ word: 'nee', translation_en: 'no', translation_jp: 'いいえ' },
	{ word: 'een machine', translation_en: 'a machine', translation_jp: '機械' },
	{ word: 'de badkamer', translation_en: 'the bathroom', translation_jp: 'バスルーム' },
	{ word: 'de boter', translation_en: 'the butter', translation_jp: 'バター' },
	{ word: 'nu', translation_en: 'now', translation_jp: '今' },
	{ word: 'tussen de middag', translation_en: 'at noon', translation_jp: '正午に' },
	{ word: 'een fabriek', translation_en: 'a factory', translation_jp: '工場' },
	{ word: 'de muis', translation_en: 'the mouse', translation_jp: 'マウス' },
	{ word: 'de verjaardag', translation_en: 'the birthday', translation_jp: '誕生日' },
	{ word: 'echt', translation_en: 'Real', translation_jp: '本物' },
	{ word: 'een laken', translation_en: 'a sheet', translation_jp: 'シート' },
	{ word: 'wassen', translation_en: 'to wash', translation_jp: '洗う' },
	{ word: 'het bier', translation_en: 'the beer', translation_jp: 'ビール' },
	{ word: 'makkelijk', translation_en: 'comfortable', translation_jp: '快適' },
	{ word: 'de rugzak', translation_en: 'the backpack', translation_jp: 'バックパック' },
	{ word: 'het venster', translation_en: 'the window', translation_jp: '窓' },
	{ word: 'de regen', translation_en: 'the rain', translation_jp: '雨' },
	{ word: 'binnengaan', translation_en: 'enter', translation_jp: '入力' },
	{ word: 'ziek', translation_en: 'sick', translation_jp: '病気' },
	{ word: 'een muur', translation_en: 'a wall', translation_jp: '壁' },
	{ word: 'hij', translation_en: 'he', translation_jp: '彼' },
	{ word: 'de professor', translation_en: 'the professor', translation_jp: '教授' },
	{ word: 'een kers', translation_en: 'a cherry', translation_jp: 'さくらんぼ' },
	{
		word: 'tot binnenkort!',
		translation_en: 'see you soon!',
		translation_jp: 'また近いうちにお会いしましょう！'
	},
	{ word: 'de aankomst', translation_en: 'the arrival', translation_jp: '到着' },
	{ word: 'minder', translation_en: 'fewer', translation_jp: '少ない' },
	{ word: 'de aarde', translation_en: 'the earth', translation_jp: '地球' },
	{ word: 'jij', translation_en: 'you', translation_jp: 'あなた' },
	{ word: 'de vertaler', translation_en: 'the translator', translation_jp: '翻訳者' },
	{ word: 'een flat', translation_en: 'an apartment', translation_jp: 'アパート' },
	{ word: 'de wolf', translation_en: 'the wolf', translation_jp: 'オオカミ' },
	{ word: 'blijven staan', translation_en: 'remain standing', translation_jp: '立ったまま' },
	{ word: 'een boer', translation_en: 'a farmer', translation_jp: '農民' },
	{ word: 'alleen', translation_en: 'only', translation_jp: 'のみ' },
	{ word: 'knap', translation_en: 'handsome', translation_jp: 'ハンサム' },
	{ word: 'een kanaal', translation_en: 'a channel', translation_jp: 'チャンネル' },
	{ word: 'oud', translation_en: 'old', translation_jp: '古い' },
	{ word: 'boven', translation_en: 'above', translation_jp: 'その上' },
	{ word: 'een journalist', translation_en: 'a journalist', translation_jp: 'ジャーナリスト' },
	{ word: 'vandaag', translation_en: 'Today', translation_jp: '今日' },
	{ word: 'achternaam', translation_en: 'surname', translation_jp: '姓' },
	{ word: 'een koelkast', translation_en: 'a refrigerator', translation_jp: '冷蔵庫' },
	{ word: 'de schoenen', translation_en: 'the shoes', translation_jp: '靴' },
	{ word: 'de patiënt', translation_en: 'the patient', translation_jp: '患者' },
	{ word: 'genoeg', translation_en: 'enough', translation_jp: '十分' },
	{ word: 'achter', translation_en: 'behind', translation_jp: '後ろに' },
	{ word: 'het lichaam', translation_en: 'the body', translation_jp: '体' },
	{ word: 'dank u wel', translation_en: 'Thank you', translation_jp: 'ありがとう' },
	{ word: 'de suiker', translation_en: 'the sugar', translation_jp: '砂糖' },
	{ word: 'de kleding', translation_en: 'the clothes', translation_jp: '服' },
	{ word: 'proper', translation_en: 'clean', translation_jp: 'クリーン' },
	{ word: 'bruin', translation_en: 'brown', translation_jp: '茶色' },
	{ word: 'kennen', translation_en: 'know', translation_jp: '知る' },
	{ word: 'een halte', translation_en: 'a stop', translation_jp: '停止' },
	{ word: 'een taxi', translation_en: 'a taxi', translation_jp: 'タクシー' },
	{ word: 'sluiten', translation_en: 'close', translation_jp: '近い' },
	{ word: 'ze', translation_en: 'them', translation_jp: '彼ら' },
	{ word: 'de stoel', translation_en: 'the chair', translation_jp: '椅子' },
	{ word: 'de vervuiling', translation_en: 'the pollution', translation_jp: '汚染' },
	{ word: 'het oosten', translation_en: 'the east', translation_jp: '東' },
	{ word: 'het sap', translation_en: 'the juice', translation_jp: 'ジュース' },
	{ word: 'het voorhoofd', translation_en: 'the forehead', translation_jp: '額' },
	{ word: 'de industrie', translation_en: 'the industry', translation_jp: '業界' },
	{ word: 'zingen', translation_en: 'sing', translation_jp: '歌う' },
	{ word: 'een hoofdkussen', translation_en: 'a pillow', translation_jp: '枕' },
	{ word: 'het zout', translation_en: 'the salt', translation_jp: '塩' },
	{ word: 'een week', translation_en: 'a week', translation_jp: '一週間' },
	{ word: 'schrijven', translation_en: 'to write', translation_jp: '書く' },
	{ word: 'hoog', translation_en: 'high', translation_jp: '高い' },
	{ word: 'kopen', translation_en: 'buy', translation_jp: '買う' },
	{ word: 'een jongedame', translation_en: 'a young lady', translation_jp: '若い女性' },
	{ word: 'een maand', translation_en: 'a month', translation_jp: '一ヶ月' },
	{ word: 'het laken', translation_en: 'the sheet', translation_jp: 'シート' },
	{ word: 'de zee', translation_en: 'the sea', translation_jp: '海' },
	{ word: 'de rat', translation_en: 'the rat', translation_jp: 'ネズミ' },
	{ word: 'een vogel', translation_en: 'a bird', translation_jp: '鳥' },
	{ word: 'de ziekte', translation_en: 'the disease', translation_jp: '病気' },
	{ word: 'warm', translation_en: 'hot', translation_jp: '熱い' },
	{ word: 'een sleutel', translation_en: 'a key', translation_jp: '鍵' },
	{ word: 'het bos', translation_en: 'the forest', translation_jp: '森' },
	{ word: 'de maaltijd', translation_en: 'the meal', translation_jp: '食事' },
	{ word: 'willen', translation_en: 'want', translation_jp: '欲しい' },
	{ word: 'de lucifer', translation_en: 'the match', translation_jp: '試合' },
	{ word: 'de vork', translation_en: 'the fork', translation_jp: 'フォーク' },
	{ word: 'gevaarlijk', translation_en: 'dangerous', translation_jp: '危険な' },
	{ word: 'brengen', translation_en: 'to take', translation_jp: '取る' },
	{ word: 'een kerk', translation_en: 'a church', translation_jp: '教会' },
	{ word: 'de servet', translation_en: 'the napkin', translation_jp: 'ナプキン' },
	{ word: 'het schip', translation_en: 'the ship', translation_jp: '船' },
	{ word: 'het pad', translation_en: 'the path', translation_jp: '道' },
	{ word: 'de muziek', translation_en: 'the music', translation_jp: '音楽' },
	{ word: 'de dans', translation_en: 'the dance', translation_jp: 'ダンス' },
	{ word: 'een zieke', translation_en: 'a sick person', translation_jp: '病気の人' },
	{ word: 'de arm', translation_en: 'the arm', translation_jp: '腕' },
	{ word: 'de chocolade', translation_en: 'the chocolate', translation_jp: 'チョコレート' },
	{ word: 'een rivier', translation_en: 'a river', translation_jp: '川' },
	{ word: 'wachten', translation_en: 'to wait', translation_jp: '待つ' },
	{ word: 'laag', translation_en: 'low', translation_jp: '低い' },
	{ word: 'de president', translation_en: 'the president', translation_jp: '大統領' },
	{ word: 'het varkensvlees', translation_en: 'the pork', translation_jp: '豚肉' },
	{ word: 'wij', translation_en: 'We', translation_jp: '私たちは' },
	{ word: 'de lepel', translation_en: 'the spoon', translation_jp: 'スプーン' },
	{ word: 'opsturen', translation_en: 'send', translation_jp: '送信' },
	{ word: 'de omgeving', translation_en: 'the environment', translation_jp: '環境' },
	{ word: 'komen', translation_en: 'come', translation_jp: '来る' },
	{ word: 'een motor', translation_en: 'an engine', translation_jp: 'エンジン' },
	{ word: 'een citroen', translation_en: 'a lemon', translation_jp: 'レモン' },
	{ word: 'een been', translation_en: 'a leg', translation_jp: '脚' },
	{ word: 'de jurk', translation_en: 'the dress', translation_jp: 'ドレス' },
	{ word: 'het dier', translation_en: 'the animal', translation_jp: '動物' },
	{ word: 'het water', translation_en: 'the water', translation_jp: '水' },
	{ word: 'de geschiedenis', translation_en: 'the history', translation_jp: '歴史' },
	{ word: 'het woordenboek', translation_en: 'the dictionary', translation_jp: '辞書' },
	{ word: 'het glas', translation_en: 'the glass', translation_jp: 'ガラス' },
	{ word: 'de rok', translation_en: 'the skirt', translation_jp: 'スカート' },
	{ word: 'de kat', translation_en: 'the cat', translation_jp: '猫' },
	{ word: 'het kanaal', translation_en: 'the canal', translation_jp: '運河' },
	{ word: 'koken', translation_en: 'to cook', translation_jp: '料理する' },
	{ word: 'een schrijver', translation_en: 'a writer', translation_jp: '作家' },
	{ word: 'een soldaat', translation_en: 'a soldier', translation_jp: '兵士' },
	{ word: 'een militair', translation_en: 'a soldier', translation_jp: '兵士' },
	{ word: 'dichtbij', translation_en: 'near', translation_jp: '近く' },
	{ word: 'het ontbijt', translation_en: 'the breakfast', translation_jp: '朝食' },
	{ word: 'zij', translation_en: 'she', translation_jp: '彼女' },
	{ word: 'een deur', translation_en: 'a door', translation_jp: 'ドア' },
	{ word: 'een brandweerman', translation_en: 'a firefighter', translation_jp: '消防士' },
	{ word: 'de zon', translation_en: 'the sun', translation_jp: '太陽' },
	{ word: 'een gebouw', translation_en: 'a building', translation_jp: '建物' },
	{ word: 'de lamp', translation_en: 'the lamp', translation_jp: 'ランプ' },
	{ word: '(de) middag', translation_en: '(the) afternoon', translation_jp: '（その）午後' },
	{ word: 'de sneeuw', translation_en: 'the snow', translation_jp: '雪' },
	{ word: 'de prijs', translation_en: 'the price', translation_jp: '価格' },
	{ word: 'leggen', translation_en: 'lay', translation_jp: '横たわる' },
	{ word: 'het vertrek', translation_en: 'the departure', translation_jp: '出発' },
	{ word: 'een boek', translation_en: 'a book', translation_jp: '本' },
	{ word: 'het medicijn', translation_en: 'the medicine', translation_jp: '薬' },
	{ word: 'een ziekte', translation_en: 'a disease', translation_jp: '病気' },
	{ word: 'het bed', translation_en: 'the bed', translation_jp: 'ベッド' },
	{ word: 'een bij', translation_en: 'a bee', translation_jp: '蜂' },
	{ word: 'de hel', translation_en: 'hell', translation_jp: '地獄' },
	{ word: 'gisteren', translation_en: 'yesterday', translation_jp: '昨日' },
	{ word: 'een zakenman', translation_en: 'a businessman', translation_jp: 'ビジネスマン' },
	{ word: 'een woordenboek', translation_en: 'a dictionary', translation_jp: '辞書' },
	{ word: 'kunnen', translation_en: 'be able to', translation_jp: 'できる' },
	{ word: 'een servet', translation_en: 'a napkin', translation_jp: 'ナプキン' },
	{ word: 'een tand', translation_en: 'a tooth', translation_jp: '歯' },
	{ word: 'een stad', translation_en: 'a city', translation_jp: '都市' },
	{ word: 'eten', translation_en: 'to eat', translation_jp: '食べる' },
	{ word: 'een opa', translation_en: 'a grandfather', translation_jp: '祖父' },
	{ word: 'een kind', translation_en: 'a child', translation_jp: '子供' },
	{ word: 'de wet', translation_en: 'the law', translation_jp: '法律' },
	{ word: 'de rivier', translation_en: 'the river', translation_jp: '川' },
	{
		word: 'wacht op mij!',
		translation_en: 'wait for me!',
		translation_jp: '私を待っててください！'
	},
	{ word: 'luisteren', translation_en: 'listen', translation_jp: '聞く' },
	{ word: 'een kaartje', translation_en: 'a ticket', translation_jp: 'チケット' },
	{
		word: 'ik spreek Nederlands',
		translation_en: 'I speak Dutch',
		translation_jp: '私はオランダ語を話します'
	},
	{ word: 'het meer', translation_en: 'the lake', translation_jp: '湖' },
	{ word: 'het paradijs', translation_en: 'paradise', translation_jp: 'パラダイス' },
	{ word: 'een klas', translation_en: 'a class', translation_jp: 'クラス' },
	{ word: 'tekenen', translation_en: 'to draw', translation_jp: '描く' },
	{ word: 'de olie', translation_en: 'the oil', translation_jp: '油' },
	{ word: 'zien', translation_en: 'to see', translation_jp: '見る' },
	{ word: 'een paard', translation_en: 'a horse', translation_jp: '馬' },
	{ word: 'een apotheek', translation_en: 'a pharmacy', translation_jp: '薬局' },
	{ word: 'links', translation_en: 'left', translation_jp: '左' },
	{ word: 'een hand', translation_en: 'a hand', translation_jp: '手' },
	{ word: 'accepteren', translation_en: 'accept', translation_jp: '受け入れる' },
	{ word: 'een vakbond', translation_en: 'a trade union', translation_jp: '労働組合' },
	{ word: 'maken', translation_en: 'to make', translation_jp: '作る' },
	{ word: 'klaar', translation_en: 'finished', translation_jp: '終了した' },
	{ word: 'de tuin', translation_en: 'the garden', translation_jp: '庭' },
	{ word: 'de godsdienst', translation_en: 'religion', translation_jp: '宗教' },
	{ word: 'tot ziens', translation_en: 'goodbye', translation_jp: 'さようなら' },
	{ word: 'de revolutie', translation_en: 'the revolution', translation_jp: '革命' },
	{ word: 'het restaurant', translation_en: 'the restaurant', translation_jp: 'レストラン' },
	{ word: 'langzaam', translation_en: 'slowly', translation_jp: 'ゆっくり' },
	{ word: 'een boom', translation_en: 'a tree', translation_jp: '木' },
	{ word: 'voornaam', translation_en: 'first name', translation_jp: 'ファーストネーム' },
	{ word: 'leeg', translation_en: 'empty', translation_jp: '空の' },
	{ word: 'de lippen', translation_en: 'the lips', translation_jp: '唇' },
	{ word: 'donderdag', translation_en: 'Thursday', translation_jp: '木曜日' },
	{ word: 'de echtgenoot', translation_en: 'the husband', translation_jp: '夫' },
	{ word: 'de staat', translation_en: 'the state', translation_jp: '州' },
	{ word: 'de film', translation_en: 'the movie', translation_jp: '映画' },
	{ word: 'een minister', translation_en: 'a minister', translation_jp: '大臣' },
	{ word: 'een zoon', translation_en: 'a son', translation_jp: '息子' },
	{ word: 'een vloerkleed', translation_en: 'a rug', translation_jp: '敷物' },
	{ word: 'in bad gaan', translation_en: 'take a bath', translation_jp: 'お風呂に入る' },
	{ word: 'de jam', translation_en: 'the jam', translation_jp: 'ジャム' },
	{ word: 'het gebouw', translation_en: 'the building', translation_jp: '建物' },
	{ word: 'groot', translation_en: 'big', translation_jp: '大きい' },
	{ word: 'een kaart', translation_en: 'a card', translation_jp: 'カード' },
	{ word: 'een hond', translation_en: 'a dog', translation_jp: '犬' },
	{ word: 'de alcohol', translation_en: 'the alcohol', translation_jp: 'アルコール' },
	{ word: 'de handtas', translation_en: 'the handbag', translation_jp: 'ハンドバッグ' },
	{ word: 'het platteland', translation_en: 'the countryside', translation_jp: '田舎' },
	{ word: 'slecht', translation_en: 'bad', translation_jp: '悪い' },
	{ word: 'een vrouw', translation_en: 'a woman', translation_jp: '女性' },
	{ word: 'groen', translation_en: 'green', translation_jp: '緑' },
	{ word: 'de wolk', translation_en: 'the cloud', translation_jp: '雲' },
	{ word: 'de baby', translation_en: 'the baby', translation_jp: '赤ちゃん' },
	{ word: 'de aansteker', translation_en: 'the lighter', translation_jp: '軽い方' },
	{ word: 'de journalist', translation_en: 'the journalist', translation_jp: 'ジャーナリスト' },
	{ word: 'vinden', translation_en: 'find', translation_jp: '探す' },
	{ word: 'het hoofdkussen', translation_en: 'the pillow', translation_jp: '枕' },
	{ word: 'de ingenieur', translation_en: 'the engineer', translation_jp: 'エンジニア' },
	{ word: 'de asbak', translation_en: 'the ashtray', translation_jp: '灰皿' },
	{ word: 'het station', translation_en: 'the station', translation_jp: '駅' },
	{ word: 'allen', translation_en: 'all', translation_jp: '全て' },
	{ word: 'de arbeider', translation_en: 'the worker', translation_jp: '労働者' },
	{ word: 'het paard', translation_en: 'the horse', translation_jp: '馬' },
	{ word: 'de motor', translation_en: 'the engine', translation_jp: 'エンジン' },
	{ word: 'een handdoek', translation_en: 'a towel', translation_jp: 'タオル' },
	{ word: 'een gordijn', translation_en: 'a curtain', translation_jp: 'カーテン' },
	{ word: 'de grootvader', translation_en: 'the grandfather', translation_jp: '祖父' },
	{ word: 'plaatsen', translation_en: 'places', translation_jp: '場所' },
	{ word: 'je', translation_en: 'you', translation_jp: 'あなた' },
	{ word: 'de oorlog', translation_en: 'the war', translation_jp: '戦争' },
	{ word: 'de regering', translation_en: 'the government', translation_jp: '政府' },
	{ word: 'ja', translation_en: 'Yes', translation_jp: 'はい' },
	{ word: 'een rat', translation_en: 'a rat', translation_jp: 'ネズミ' },
	{ word: 'het gezin', translation_en: 'the family', translation_jp: '家族' },
	{ word: 'een rugzak', translation_en: 'a backpack', translation_jp: 'バックパック' },
	{ word: 'de ogen', translation_en: 'the eyes', translation_jp: '目' },
	{ word: 'het noorden', translation_en: 'the north', translation_jp: '北' },
	{
		word: 'op je gezondheid',
		translation_en: 'on your health',
		translation_jp: 'あなたの健康について'
	},
	{ word: 'een sinaasappel', translation_en: 'an orange', translation_jp: 'オレンジ' },
	{ word: 'gelukkig', translation_en: 'happy', translation_jp: 'ハッピー' },
	{ word: 'een verjaardag', translation_en: 'a birthday', translation_jp: '誕生日' },
	{ word: 'een tomaat', translation_en: 'a tomato', translation_jp: 'トマト' },
	{
		word: 'het vruchtensap',
		translation_en: 'the fruit juice',
		translation_jp: 'フルーツジュース'
	},
	{ word: 'de peper', translation_en: 'the pepper', translation_jp: 'コショウ' },
	{ word: 'men moet...', translation_en: 'one must...', translation_jp: '必ず...' },
	{ word: 'horen', translation_en: 'to belong', translation_jp: '所属する' },
	{ word: 'een straat', translation_en: 'a street', translation_jp: '通り' },
	{ word: 'de sinaasappel', translation_en: 'the orange', translation_jp: 'オレンジ' },
	{ word: 'de vogel', translation_en: 'the bird', translation_jp: '鳥' },
	{ word: 'goedkoop', translation_en: 'cheap', translation_jp: '安い' },
	{ word: 'de huurprijs', translation_en: 'the rental price', translation_jp: 'レンタル価格' },
	{ word: 'een partij', translation_en: 'a party', translation_jp: 'パーティー' },
	{ word: 'een lepel', translation_en: 'a spoon', translation_jp: 'スプーン' },
	{ word: 'lelijk', translation_en: 'ugly', translation_jp: '醜い' },
	{ word: 'moeilijk', translation_en: 'difficult', translation_jp: '難しい' },
	{ word: 'vertalen', translation_en: 'translate', translation_jp: '翻訳する' },
	{ word: 'verboden', translation_en: 'forbidden', translation_jp: '禁断' },
	{ word: 'een ticket', translation_en: 'a ticket', translation_jp: 'チケット' },
	{ word: 'het koren', translation_en: 'the corn', translation_jp: 'トウモロコシ' },
	{ word: 'de maatschappij', translation_en: 'society', translation_jp: '社会' },
	{ word: 'de melk', translation_en: 'the milk', translation_jp: '牛乳' },
	{ word: 'de zieke', translation_en: 'the sick person', translation_jp: '病気の人' },
	{ word: 'het onderwijs', translation_en: 'education', translation_jp: '教育' },
	{ word: 'onder', translation_en: 'under', translation_jp: '下' },
	{ word: 'het zuiden', translation_en: 'the south', translation_jp: '南' },
	{ word: 'het volk', translation_en: 'the people', translation_jp: '人々' },
	{ word: 'de schilderkunst', translation_en: 'painting', translation_jp: '絵画' },
	{ word: 'de televisie', translation_en: 'the television', translation_jp: 'テレビ' },
	{ word: 'een abrikoos', translation_en: 'an apricot', translation_jp: 'アプリコット' },
	{ word: 'de verdieping', translation_en: 'the floor', translation_jp: '床' },
	{ word: 'een stoel', translation_en: 'a chair', translation_jp: '椅子' },
	{ word: 'tellen', translation_en: 'to count', translation_jp: '数える' },
	{ word: 'u', translation_en: 'you', translation_jp: 'あなた' },
	{ word: 'de docent', translation_en: 'the teacher', translation_jp: '先生' },
	{ word: 'het graan', translation_en: 'the grain', translation_jp: '穀物' },
	{ word: 'de vader', translation_en: 'the father', translation_jp: '父親' },
	{ word: 'de tong', translation_en: 'the tongue', translation_jp: '舌' },
	{ word: 'het ei', translation_en: 'the egg', translation_jp: '卵' },
	{ word: 'het kind', translation_en: 'the child', translation_jp: '子供' },
	{ word: 'de telefoon', translation_en: 'the phone', translation_jp: '電話' },
	{ word: 'het papier', translation_en: 'the paper', translation_jp: '紙' },
	{ word: 'de buurman', translation_en: 'the neighbor', translation_jp: '隣人' },
	{ word: 'de maand', translation_en: 'the month', translation_jp: '月' },
	{ word: 'de bron', translation_en: 'the source', translation_jp: 'ソース' },
	{ word: 'de fles', translation_en: 'the bottle', translation_jp: 'ボトル' },
	{ word: 'een rok', translation_en: 'a skirt', translation_jp: 'スカート' },
	{ word: 'een kat', translation_en: 'a cat', translation_jp: '猫' },
	{ word: 'de politieagent', translation_en: 'the police officer', translation_jp: '警察官' },
	{ word: 'een meer', translation_en: 'a lake', translation_jp: '湖' },
	{ word: 'het ticket', translation_en: 'the ticket', translation_jp: 'チケット' },
	{
		word: 'ik kom uit Nederland',
		translation_en: 'I am from the Netherlands',
		translation_jp: '私はオランダ出身です'
	},
	{ word: 'de ster', translation_en: 'the star', translation_jp: '星' },
	{ word: 'weigeren', translation_en: 'to refuse', translation_jp: '拒否する' },
	{ word: 'goedendag', translation_en: 'Good day', translation_jp: '良い一日' },
	{ word: 'laten', translation_en: 'to leave', translation_jp: '去る' },
	{ word: 'de ui', translation_en: 'the onion', translation_jp: 'タマネギ' },
	{ word: 'een pad', translation_en: 'a path', translation_jp: '道' },
	{ word: 'de school', translation_en: 'the school', translation_jp: '学校' },
	{ word: 'breed', translation_en: 'wide', translation_jp: '広い' },
	{ word: 'de peer', translation_en: 'the pear', translation_jp: '梨' },
	{ word: 'de computer', translation_en: 'the computer', translation_jp: 'コンピューター' },
	{ word: 'vroeg', translation_en: 'asked', translation_jp: '尋ねた' },
	{ word: 'een handelaar', translation_en: 'a trader', translation_jp: 'トレーダー' },
	{ word: 'vies', translation_en: 'dirty', translation_jp: '汚い' },
	{ word: 'goedenacht', translation_en: 'good night', translation_jp: 'おやすみ' },
	{ word: 'ontmoeten', translation_en: 'meet', translation_jp: '会う' },
	{ word: 'de moeder', translation_en: 'the mother', translation_jp: '母親' },
	{ word: 'de zuigeling', translation_en: 'the infant', translation_jp: '幼児' },
	{ word: 'een postzegel', translation_en: 'a postage stamp', translation_jp: '切手' },
	{ word: 'verkopen', translation_en: 'to sell', translation_jp: '売る' },
	{ word: 'naam', translation_en: 'name', translation_jp: '名前' },
	{ word: 'de thee', translation_en: 'the tea', translation_jp: 'お茶' },
	{ word: 'het lawaai', translation_en: 'the noise', translation_jp: '騒音' },
	{ word: 'de oren', translation_en: 'the ears', translation_jp: '耳' },
	{ word: 'een arm', translation_en: 'an arm', translation_jp: '腕' },
	{ word: 'de vis', translation_en: 'the fish', translation_jp: '魚' },
	{ word: 'de student', translation_en: 'the student', translation_jp: '学生' },
	{ word: 'het boek', translation_en: 'the book', translation_jp: '本' },
	{ word: 'het milieu', translation_en: 'the environment', translation_jp: '環境' },
	{ word: 'de wijn', translation_en: 'the wine', translation_jp: 'ワイン' },
	{ word: 'de groente', translation_en: 'the vegetable', translation_jp: '野菜' }
];

export default records;
