export const records: { word: string, translation_en: string, translation_jp: string }[] = [
    { word: "die Nullstelle einer Funktion", translation_en: "the zero of a function", translation_jp: "関数のゼロ" },
    { word: "absteigend", translation_en: "descending", translation_jp: "降順" },
    { word: "darstellen", translation_en: "represent", translation_jp: "代表する" },
    { word: "der Funktionswert", translation_en: "the function value", translation_jp: "関数の値" },
    { word: "die Definitionsmenge", translation_en: "the definition set", translation_jp: "定義セット" },
    { word: "die höchste vorkommende Potenz", translation_en: "the highest occurring potency", translation_jp: "最も高い効力が発生する" },
    { word: "der Satz", translation_en: "the sentence", translation_jp: "文" },
    { word: "die Kurvendiskussion", translation_en: "the curve discussion", translation_jp: "カーブの議論" },
    { word: "die Kubikwurzel", translation_en: "the cube root", translation_jp: "立方根" },
    { word: "die Einheit", translation_en: "the unit", translation_jp: "ユニット" },
    { word: "die Tabelle", translation_en: "the table", translation_jp: "テーブル" },
    { word: "der Grad", translation_en: "the degree", translation_jp: "学位" },
    { word: "die Multiplikation", translation_en: "the multiplication", translation_jp: "掛け算" },
    { word: "der Lehrsatz", translation_en: "the doctrine", translation_jp: "教義" },
    { word: "abnehmen", translation_en: "lose weight", translation_jp: "体重を減らす" },
    { word: "die Ausgangsgleichung", translation_en: "the initial equation", translation_jp: "初期方程式" },
    { word: "das Drittel", translation_en: "the third", translation_jp: "3番目の" },
    { word: "das unbestimmte Integral", translation_en: "the indefinite integral", translation_jp: "不定積分" },
    { word: "das Beispiel", translation_en: "the example", translation_jp: "例" },
    { word: "der Graph", translation_en: "the graph", translation_jp: "グラフ" },
    { word: "die Varianz", translation_en: "the variance", translation_jp: "差異" },
    { word: "die Kurventangente an einer Stelle", translation_en: "the curve tangent at one point", translation_jp: "曲線の 1 点での接線" },
    { word: "der Wurzelexponent", translation_en: "the root exponent", translation_jp: "根指数" },
    { word: "die gebrochenrationale Funktion", translation_en: "the fractional rational function", translation_jp: "分数有理関数" },
    { word: "die y-Koordinate", translation_en: "the y coordinate", translation_jp: "y 座標" },
    { word: "die Skizze", translation_en: "the sketch", translation_jp: "スケッチ" },
    { word: "die Funktionskurve", translation_en: "the function curve", translation_jp: "関数曲線" },
    { word: "die Menge", translation_en: "the amount", translation_jp: "金額" },
    { word: "die Logarithmusfunktion", translation_en: "the logarithm function", translation_jp: "対数関数" },
    { word: "das Vieleck", translation_en: "the polygon", translation_jp: "多角形" },
    { word: "das Paar", translation_en: "the couple", translation_jp: "カップル" },
    { word: "die Normalform", translation_en: "the normal form", translation_jp: "通常の形" },
    { word: "das Ereignis", translation_en: "the event", translation_jp: "イベント" },
    { word: "das Gesetz", translation_en: "the law", translation_jp: "法律" },
    { word: "das geordnete Paar", translation_en: "the ordered pair", translation_jp: "注文されたペア" },
    { word: "die Lösung bestimmen", translation_en: "determine the solution", translation_jp: "解決策を決める" },
    { word: "das Längenmaß", translation_en: "the measure of length", translation_jp: "長さの測り方" },
    { word: "der Rest", translation_en: "the rest", translation_jp: "残り" },
    { word: "die Tangente", translation_en: "the tangent", translation_jp: "接線" },
    { word: "die geometrische Folge", translation_en: "the geometric sequence", translation_jp: "幾何級数" },
    { word: "das Zeichen", translation_en: "the sign", translation_jp: "サイン" },
    { word: "die Punktrechnung", translation_en: "the point calculation", translation_jp: "ポイント計算" },
    { word: "die Diagonale", translation_en: "the diagonal", translation_jp: "対角線" },
    { word: "die Raute", translation_en: "the diamond", translation_jp: "ダイヤモンド" },
    { word: "die Asymptote", translation_en: "the asymptote", translation_jp: "漸近線" },
    { word: "die Folge", translation_en: "the consequence", translation_jp: "結果" },
    { word: "das Hexadezimalsystem", translation_en: "the hexadecimal system", translation_jp: "16進法" },
    { word: "der Schenkel", translation_en: "the thigh", translation_jp: "太もも" },
    { word: "das Urbild", translation_en: "the archetype", translation_jp: "原型" },
    { word: "der Zähler", translation_en: "the counter", translation_jp: "カウンター" },
    { word: "die doppelte Nullstelle", translation_en: "the double zero", translation_jp: "二重ゼロ" },
    { word: "die Zuordnungsvorschrift", translation_en: "the allocation rule", translation_jp: "割り当てルール" },
    { word: "der Brennpunkt", translation_en: "the focal point", translation_jp: "焦点" },
    { word: "die Kettenfunktion", translation_en: "the chain function", translation_jp: "チェーン機能" },
    { word: "die Inklusion", translation_en: "the inclusion", translation_jp: "包含" },
    { word: "die Gesamtfläche", translation_en: "the total area", translation_jp: "総面積" },
    { word: "die x-Achse", translation_en: "the x-axis", translation_jp: "X軸" },
    { word: "der Endpunkt", translation_en: "the end point", translation_jp: "終点" },
    { word: "die Endpunkte einer Strecke", translation_en: "the end points of a route", translation_jp: "ルートの終点" },
    { word: "der Umfangswinkel", translation_en: "the circumferential angle", translation_jp: "円周角" },
    { word: "die Quotientenfunktion", translation_en: "the quotient function", translation_jp: "商関数" },
    { word: "die Abszisse", translation_en: "the abscissa", translation_jp: "横軸" },
    { word: "die Wertemenge", translation_en: "the set of values", translation_jp: "値のセット" },
    { word: "der Fragebogen", translation_en: "the questionnaire", translation_jp: "アンケート" },
    { word: "die Halbebene", translation_en: "the demiplane", translation_jp: "デミプレーン" },
    { word: "die Gegenseite", translation_en: "the opposite side", translation_jp: "反対側" },
    { word: "abnehmend", translation_en: "decreasing", translation_jp: "減少する" },
    { word: "aufzählen", translation_en: "enumerate", translation_jp: "列挙する" },
    { word: "die Primfaktorzerlegung", translation_en: "the prime factorization", translation_jp: "素因数分解" },
    { word: "die quadratische Normalfunktion", translation_en: "the quadratic normal function", translation_jp: "二次正規関数" },
    { word: "das Krümmungverhalten", translation_en: "the curvature behavior", translation_jp: "曲率挙動" },
    { word: "die natürlichen Zahlen", translation_en: "the natural numbers", translation_jp: "自然数" },
    { word: "der Ereignisbaum", translation_en: "the event tree", translation_jp: "イベントツリー" },
    { word: "der Flächeninhalt", translation_en: "the area", translation_jp: "地域" },
    { word: "das lokale Minimum", translation_en: "the local minimum", translation_jp: "極小値" },
    { word: "die Ordinatenachse", translation_en: "the ordinate axis", translation_jp: "縦軸" },
    { word: "das lokale Maximum", translation_en: "the local maximum", translation_jp: "極大値" },
    { word: "der Begriff", translation_en: "the term", translation_jp: "用語" },
    { word: "der Inhalt", translation_en: "the content", translation_jp: "内容" },
    { word: "bestimmt", translation_en: "certainly", translation_jp: "確かに" },
    { word: "die Grenzsekante", translation_en: "the border secant", translation_jp: "国境の割線" },
    { word: "alternieren", translation_en: "alternate", translation_jp: "代替" },
    { word: "der Einer", translation_en: "the one", translation_jp: "一つ" },
    { word: "die Rechenregel", translation_en: "the calculation rule", translation_jp: "計算ルール" },
    { word: "die Vorgehensweise", translation_en: "the procedure", translation_jp: "手順" },
    { word: "der quadratische Faktor", translation_en: "the square factor", translation_jp: "二乗因数" },
    { word: "die Annäherung", translation_en: "the approach", translation_jp: "アプローチ" },
    { word: "der Hunderter", translation_en: "the hundred", translation_jp: "百" },
    { word: "daraus folgt", translation_en: "it follows", translation_jp: "それは続きます" },
    { word: "die Standardabweichung", translation_en: "the standard deviation", translation_jp: "標準偏差" },
    { word: "der Mittelpunktswinkel", translation_en: "the center angle", translation_jp: "中心角" },
    { word: "das Pfeildiagramm", translation_en: "the arrow diagram", translation_jp: "アローダイアグラム" },
    { word: "die Trefferwahrscheinlichkeit", translation_en: "the probability of hitting", translation_jp: "当たる確率" },
    { word: "der Differenzenquotient", translation_en: "the difference quotient", translation_jp: "差の商" },
    { word: "das Quadrat", translation_en: "the square", translation_jp: "広場" },
    { word: "das unmögliche Ereignis", translation_en: "the impossible event", translation_jp: "不可能な出来事" },
    { word: "besitzen", translation_en: "own", translation_jp: "自分の" },
    { word: "die Grenzlage", translation_en: "the border location", translation_jp: "国境の位置" },
    { word: "der Kehrwert", translation_en: "the reciprocal", translation_jp: "相互" },
    { word: "die Zahlen von 3 bis 10", translation_en: "the numbers from 3 to 10", translation_jp: "3から10までの数字" },
    { word: "der Differentialquotient", translation_en: "the differential quotient", translation_jp: "微分商" },
    { word: "der Minimalwert", translation_en: "the minimum value", translation_jp: "最小値" },
    { word: "die Häufigkeit", translation_en: "the frequency", translation_jp: "周波数" },
    { word: "die Warscheinlichkeitsverteilung", translation_en: "the probability distribution", translation_jp: "確率分布" },
    { word: "bezeichnen", translation_en: "designate", translation_jp: "指定する" },
    { word: "der Erwartungswert", translation_en: "the expected value", translation_jp: "期待値" },
    { word: "die Kotangensfunktion", translation_en: "the cotangent function", translation_jp: "コタンジェント関数" },
    { word: "der Wert", translation_en: "the value", translation_jp: "値" },
    { word: "das Divisionszeichen", translation_en: "the division symbol", translation_jp: "除算記号" },
    { word: "die Tiefe", translation_en: "the depth", translation_jp: "深さ" },
    { word: "die Streung", translation_en: "the scatter", translation_jp: "散らばる" },
    { word: "das offene Intervall", translation_en: "the open interval", translation_jp: "開いた間隔" },
    { word: "die Definition", translation_en: "the definition", translation_jp: "定義" },
    { word: "das unabhängige Experiment", translation_en: "the independent experiment", translation_jp: "独立した実験" },
    { word: "die Potenzrechnung", translation_en: "the power calculation", translation_jp: "電力の計算" },
    { word: "die surjektive Abbildung", translation_en: "the surjective mapping", translation_jp: "全射写像" },
    { word: "das Ungleichungssystem", translation_en: "the inequality system", translation_jp: "不平等制度" },
    { word: "der Umkreis", translation_en: "the perimeter", translation_jp: "周囲" },
    { word: "die Division", translation_en: "the division", translation_jp: "部門" },
    { word: "die Umkehrfunktion", translation_en: "the inverse function", translation_jp: "逆関数" },
    { word: "die Gegenereignisregel", translation_en: "the counter-event rule", translation_jp: "カウンターイベントルール" },
    { word: "das Vierfache", translation_en: "four times as much", translation_jp: "4倍" },
    { word: "die Einschränkung", translation_en: "the restriction", translation_jp: "制限" },
    { word: "das Doppelte", translation_en: "double", translation_jp: "ダブル" },
    { word: "das Gleichsetzungsverfahren", translation_en: "the equation procedure", translation_jp: "方程式の手順" },
    { word: "die Eigenschaft", translation_en: "the property", translation_jp: "財産" },
    { word: "die Umformung", translation_en: "the transformation", translation_jp: "変革" },
    { word: "das Monotonieverhalten", translation_en: "the monotonic behavior", translation_jp: "単調な動作" },
    { word: "das Steigungsverhalten", translation_en: "the gradient behavior", translation_jp: "勾配の動作" },
    { word: "der Limes", translation_en: "the Limes", translation_jp: "ライムズ" },
    { word: "der Berührungspunkt", translation_en: "the point of contact", translation_jp: "連絡先" },
    { word: "der Tiefpunkt", translation_en: "the low point", translation_jp: "最低点" },
    { word: "die Problemstellung", translation_en: "the problem statement", translation_jp: "問題文" },
    { word: "der Winkel", translation_en: "the angle", translation_jp: "角度" },
    { word: "das Elementarereignis", translation_en: "the elementary event", translation_jp: "初歩的な出来事" },
    { word: "an der Stelle", translation_en: "on the spot", translation_jp: "その場で" },
    { word: "der Term", translation_en: "the term", translation_jp: "用語" },
    { word: "der y-Wert", translation_en: "the y value", translation_jp: "y 値" },
    { word: "der Umfang", translation_en: "the scope", translation_jp: "範囲" },
    { word: "der Höhenschnittpunkt", translation_en: "the height intersection point", translation_jp: "高さの交点" },
    { word: "die Grenzgerade", translation_en: "the border straight", translation_jp: "国境は真っ直ぐ" },
    { word: "bedeuten", translation_en: "mean", translation_jp: "平均" },
    { word: "die Ziffer", translation_en: "the number", translation_jp: "番号" },
    { word: "die Unbekannte", translation_en: "the unknown", translation_jp: "未知の" },
    { word: "anhand", translation_en: "based on", translation_jp: "に基づく" },
    { word: "der Nullwert", translation_en: "the zero value", translation_jp: "ゼロ値" },
    { word: "die Diskriminante", translation_en: "the discriminant", translation_jp: "判別式" },
    { word: "die Normale", translation_en: "the normal one", translation_jp: "普通のもの" },
    { word: "das Minuszeichen", translation_en: "the minus sign", translation_jp: "マイナス記号" },
    { word: "das sichere Ereignis", translation_en: "the certain event", translation_jp: "ある出来事" },
    { word: "die Variable fällt heraus", translation_en: "the variable drops out", translation_jp: "変数が抜け出す" },
    { word: "die Halbgerade", translation_en: "the half-line", translation_jp: "ハーフライン" },
    { word: "der Nenner", translation_en: "the denominator", translation_jp: "分母" },
    { word: "die Ellipse", translation_en: "the ellipse", translation_jp: "楕円" },
    { word: "die Quadratwurzelfunktion", translation_en: "the square root function", translation_jp: "平方根関数" },
    { word: "die Exponentialfunktion", translation_en: "the exponential function", translation_jp: "指数関数" },
    { word: "das Allzeichen", translation_en: "the all-sign", translation_jp: "オールサイン" },
    { word: "die vertikale Asymptote", translation_en: "the vertical asymptote", translation_jp: "垂直漸近線" },
    { word: "die Teilung", translation_en: "the division", translation_jp: "部門" },
    { word: "die Menge der rationalen Zahlen", translation_en: "the set of rational numbers", translation_jp: "有理数の集合" },
    { word: "die Sekante", translation_en: "the secant", translation_jp: "割線" },
    { word: "die Parallele", translation_en: "the parallel", translation_jp: "平行線" },
    { word: "die Möglichkeit", translation_en: "the possibility", translation_jp: "可能性" },
    { word: "die gerade Funktion", translation_en: "the straight function", translation_jp: "直線関数" },
    { word: "das Einsetzungsverfahren", translation_en: "the appointment procedure", translation_jp: "任命手続き" },
    { word: "die ungerade Potenz", translation_en: "the odd power", translation_jp: "奇妙な力" },
    { word: "die Ableitung", translation_en: "the derivation", translation_jp: "派生" },
    { word: "die Breite", translation_en: "the width", translation_jp: "幅" },
    { word: "benötigen", translation_en: "need", translation_jp: "必要" },
    { word: "die Seitenlänge", translation_en: "the side length", translation_jp: "辺の長さ" },
    { word: "der Ring", translation_en: "the ring", translation_jp: "指輪" },
    { word: "das Fallen", translation_en: "the falling", translation_jp: "落ちる" },
    { word: "das Pluszeichen", translation_en: "the plus sign", translation_jp: "プラス記号" },
    { word: "die graphische Lösung", translation_en: "the graphic solution", translation_jp: "グラフィックソリューション" },
    { word: "die Aufgabe", translation_en: "the task", translation_jp: "タスク" },
    { word: "der Vektor", translation_en: "the vector", translation_jp: "ベクトル" },
    { word: "die zweite Wurzel aus 2", translation_en: "the second root of 2", translation_jp: "2の2番目の根" },
    { word: "der Inkreis", translation_en: "the incircle", translation_jp: "内接円" },
    { word: "die identische Funktion", translation_en: "the identical function", translation_jp: "同一の機能" },
    { word: "die relative Häufigkeit", translation_en: "the relative frequency", translation_jp: "相対周波数" },
    { word: "das lineare Gleischungssystem", translation_en: "the linear system of equations", translation_jp: "線形方程式系" },
    { word: "der Grenzwert", translation_en: "the limit value", translation_jp: "限界値" },
    { word: "die Hälfte", translation_en: "the half", translation_jp: "半分" },
    { word: "die Tangente an der Stelle", translation_en: "the tangent at the point", translation_jp: "点における接線" },
    { word: "abzählen", translation_en: "count", translation_jp: "カウント" },
    { word: "die Wurzel aus x", translation_en: "the root of x", translation_jp: "xの根" },
    { word: "der natürliche Logarithmus", translation_en: "the natural logarithm", translation_jp: "自然対数" },
    { word: "die Kreiszahl Pi", translation_en: "the circle number Pi", translation_jp: "円周率Pi" },
    { word: "die Aussage", translation_en: "the statement", translation_jp: "声明" },
    { word: "definieren", translation_en: "define", translation_jp: "定義する" },
    { word: "die gerade Potenz", translation_en: "the even power", translation_jp: "均等な力" },
    { word: "auf einer Geraden liegen", translation_en: "lie on a straight line", translation_jp: "直線上に横たわる" },
    { word: "die Potenz", translation_en: "the potency", translation_jp: "効力" },
    { word: "der Teiler", translation_en: "the divider", translation_jp: "ディバイダー" },
    { word: "die Gerade", translation_en: "the straight line", translation_jp: "直線" },
    { word: "der Nachfolger", translation_en: "the successor", translation_jp: "後継者" },
    { word: "der Mittelpunkt des Umkreises", translation_en: "the center of the circle", translation_jp: "円の中心" },
    { word: "der Kreis um A mit Radius r", translation_en: "the circle around A with radius r", translation_jp: "Aの周りの半径rの円" },
    { word: "der Zehnerlogarithmus", translation_en: "the ten logarithm", translation_jp: "10の対数" },
    { word: "der Schnittpunkt", translation_en: "the intersection point", translation_jp: "交点" },
    { word: "ausfüllen", translation_en: "fill out", translation_jp: "記入する" },
    { word: "das Diagramm", translation_en: "the diagram", translation_jp: "図" },
    { word: "das Substrahieren", translation_en: "the subtraction", translation_jp: "引き算" },
    { word: "die Kante", translation_en: "the edge", translation_jp: "端" },
    { word: "das Koordinatensystem", translation_en: "the coordinate system", translation_jp: "座標系" },
    { word: "die Reihe", translation_en: "the row", translation_jp: "行" },
    { word: "das Multiplikationszeichen", translation_en: "the multiplication sign", translation_jp: "掛け算の記号" },
    { word: "die Potenzfunktion", translation_en: "the power function", translation_jp: "べき乗関数" },
    { word: "die Abszissenachse", translation_en: "the abscissa axis", translation_jp: "横軸" },
    { word: "der Logarithmus", translation_en: "the logarithm", translation_jp: "対数" },
    { word: "das Potenzieren", translation_en: "the potentiation", translation_jp: "増強" },
    { word: "ausklammern", translation_en: "exclude", translation_jp: "除外する" },
    { word: "betrachten", translation_en: "regard", translation_jp: "尊重する" },
    { word: "die Komplementbildung", translation_en: "the complement formation", translation_jp: "補体形成" },
    { word: "das Monom", translation_en: "the monomial", translation_jp: "単項式" },
    { word: "die Exponentialfunktion zur Basis a", translation_en: "the exponential function to base a", translation_jp: "aを底とする指数関数" },
    { word: "die Rechtskurve", translation_en: "the right turn", translation_jp: "右折" },
    { word: "der Funktionsterm", translation_en: "the function term", translation_jp: "関数項" },
    { word: "die Bedingung erfüllen", translation_en: "fulfill the condition", translation_jp: "条件を満たす" },
    { word: "das Viertel", translation_en: "the quarter", translation_jp: "四半期" },
    { word: "der Exponentialwert von 6 zur Basis 3", translation_en: "the exponential value of 6 to base 3", translation_jp: "6 を底 3 にした指数値" },
    { word: "das Zahlenpaar", translation_en: "the pair of numbers", translation_jp: "数字のペア" },
    { word: "der Quotient", translation_en: "the quotient", translation_jp: "商" },
    { word: "das halboffene Intervall", translation_en: "the half-open interval", translation_jp: "半開間隔" },
    { word: "die Wurzel", translation_en: "the root", translation_jp: "根" },
    { word: "der Ereignisraum", translation_en: "the event space", translation_jp: "イベントスペース" },
    { word: "die Summe", translation_en: "the sum", translation_jp: "合計" },
    { word: "die Winkelhalbierende", translation_en: "the angle bisector", translation_jp: "角の二等分線" },
    { word: "die waagerechte Asymptote", translation_en: "the horizontal asymptote", translation_jp: "水平漸近線" },
    { word: "die Basis", translation_en: "the base", translation_jp: "ベース" },
    { word: "anstelle y einsetzen", translation_en: "insert instead of y", translation_jp: "y の代わりに挿入" },
    { word: "das Axiom", translation_en: "the axiom", translation_jp: "公理" },
    { word: "die Steigerung", translation_en: "the increase", translation_jp: "増加" },
    { word: "das Vielfache", translation_en: "the multiple", translation_jp: "複数の" },
    { word: "die dritte Wurzel aus 2", translation_en: "the third root of 2", translation_jp: "2の3番目の根" },
    { word: "das Zufallsexperiment", translation_en: "the random experiment", translation_jp: "ランダムな実験" },
    { word: "die Ebene", translation_en: "the level", translation_jp: "レベル" },
    { word: "der x-Wert", translation_en: "the x value", translation_jp: "xの値" },
    { word: "der Wendepunkt", translation_en: "the turning point", translation_jp: "転換点" },
    { word: "eine Gleichung ausetzen", translation_en: "suspend an equation", translation_jp: "方程式を一時停止する" },
    { word: "die disjunkten Teile", translation_en: "the disjoint parts", translation_jp: "ばらばらの部分" },
    { word: "eine Operation ausführen", translation_en: "perform an operation", translation_jp: "操作を実行する" },
    { word: "der Radius", translation_en: "the radius", translation_jp: "半径" },
    { word: "der Abstand zwischen zwei Kurven", translation_en: "the distance between two curves", translation_jp: "2つの曲線の間の距離" },
    { word: "das Zweiersystem", translation_en: "the two-system", translation_jp: "2つのシステム" },
    { word: "die Termdarstellung", translation_en: "the term representation", translation_jp: "表現という用語" },
    { word: "das Variationsverhalten", translation_en: "the variation behavior", translation_jp: "変化行動" },
    { word: "die Formel", translation_en: "the formula", translation_jp: "式" },
    { word: "die Produktdarstellung", translation_en: "the product presentation", translation_jp: "製品プレゼンテーション" },
    { word: "die Längeneinheit", translation_en: "the unit of length", translation_jp: "長さの単位" },
    { word: "der Ableitungswert", translation_en: "the derivative value", translation_jp: "微分値" },
    { word: "die Stichprobe", translation_en: "the sample", translation_jp: "サンプル" },
    { word: "das Gegenbeispiel", translation_en: "the counterexample", translation_jp: "反例" },
    { word: "die Darstellung", translation_en: "the representation", translation_jp: "表現" },
    { word: "die Stammfunktion", translation_en: "the antiderivative function", translation_jp: "反微分関数" },
    { word: "die ganzrationale Funktion", translation_en: "the entirely rational function", translation_jp: "完全に有理関数" },
    { word: "das Polynom", translation_en: "the polynomial", translation_jp: "多項式" },
    { word: "die Rechnung", translation_en: "the bill", translation_jp: "請求書" },
    { word: "die Wurzel ziehen", translation_en: "pull the root", translation_jp: "根を引っ張る" },
    { word: "das Element einer Menge", translation_en: "the element of a set", translation_jp: "集合の要素" },
    { word: "die notwendige Bedingung", translation_en: "the necessary condition", translation_jp: "必要な条件" },
    { word: "das Rechteck", translation_en: "the rectangle", translation_jp: "長方形" },
    { word: "die Quadratwurzel", translation_en: "the square root", translation_jp: "平方根" },
    { word: "die Erhebung", translation_en: "the survey", translation_jp: "調査" },
    { word: "die Ableitung von f an der Stelle x", translation_en: "the derivative of f at position x", translation_jp: "位置 x における f の導関数" },
    { word: "der Satz von Pythagoras", translation_en: "the Pythagorean theorem", translation_jp: "ピタゴラスの定理" },
    { word: "der Vorzeichenwechsel", translation_en: "the change of sign", translation_jp: "符号の変更" },
    { word: "das Folgeglied", translation_en: "the following member", translation_jp: "次のメンバー" },
    { word: "der Ursprung eines Koordinatensystems", translation_en: "the origin of a coordinate system", translation_jp: "座標系の原点" },
    { word: "die Vervielfachung", translation_en: "the multiplication", translation_jp: "掛け算" },
    { word: "die lineare Optimierung", translation_en: "the linear optimization", translation_jp: "線形最適化" },
    { word: "die geordnete Auswahl", translation_en: "the ordered selection", translation_jp: "順序付けられた選択" },
    { word: "die Permutation", translation_en: "the permutation", translation_jp: "順列" },
    { word: "das Wertepaar", translation_en: "the pair of values", translation_jp: "値のペア" },
    { word: "bzw. (beziehungsweise)", translation_en: "or (respectively)", translation_jp: "または（それぞれ）" },
    { word: "der Strahlensatz", translation_en: "the radiation theorem", translation_jp: "放射定理" },
    { word: "die Additionsregel", translation_en: "the addition rule", translation_jp: "追加ルール" },
    { word: "das Dreifache", translation_en: "three times as much", translation_jp: "3倍" },
    { word: "die Tangente an einer Kurve", translation_en: "the tangent on a curve", translation_jp: "曲線上の接線" },
    { word: "die Mengenlehre", translation_en: "set theory", translation_jp: "集合論" },
    { word: "die absolute Häufigkeit", translation_en: "the absolute frequency", translation_jp: "絶対周波数" },
    { word: "die konstante Funktion", translation_en: "the constant function", translation_jp: "定数関数" },
    { word: "die Quadratzahl", translation_en: "the square number", translation_jp: "平方数" },
    { word: "das Achsenkreuz", translation_en: "the axis cross", translation_jp: "軸のクロス" },
    { word: "die hinreichende Bedingung", translation_en: "the sufficient condition", translation_jp: "十分条件" },
    { word: "der Faktor", translation_en: "the factor", translation_jp: "要因" },
    { word: "der Erweiterungsfaktor", translation_en: "the expansion factor", translation_jp: "拡大率" },
    { word: "der Produktsatz", translation_en: "the product set", translation_jp: "製品セット" },
    { word: "die Menge aller Elemente von", translation_en: "the set of all elements of", translation_jp: "のすべての要素のセット" },
    { word: "das Verhältnis", translation_en: "the relationship", translation_jp: "関係" },
    { word: "der Symmetriepunkt", translation_en: "the point of symmetry", translation_jp: "対称点" },
    { word: "die x-Koordinate", translation_en: "the x coordinate", translation_jp: "x座標" },
    { word: "der Teil", translation_en: "the part", translation_jp: "その部分" },
    { word: "das Körpermaß", translation_en: "the body measurement", translation_jp: "身体測定" },
    { word: "der Exponent", translation_en: "the exponent", translation_jp: "指数" },
    { word: "die Kurve", translation_en: "the curve", translation_jp: "曲線" },
    { word: "das Element", translation_en: "the element", translation_jp: "要素" },
    { word: "das Anstiegsdreieck", translation_en: "the rising triangle", translation_jp: "上昇三角形" },
    { word: "der Scheitelpunkt", translation_en: "the vertex", translation_jp: "頂点" },
    { word: "die Verknüpfung", translation_en: "the link", translation_jp: "リンク" },
    { word: "die Zahlen", translation_en: "the numbers", translation_jp: "数字" },
    { word: "das Gegenereignis", translation_en: "the counter event", translation_jp: "カウンターイベント" },
    { word: "absteigen", translation_en: "descend", translation_jp: "降りる" },
    { word: "der Durchschnitt", translation_en: "the average", translation_jp: "平均" },
    { word: "das Verhalten einer Funktion", translation_en: "the behavior of a function", translation_jp: "関数の動作" },
    { word: "die Koordinaten", translation_en: "the coordinates", translation_jp: "座標" },
    { word: "die senkrechte Gerade", translation_en: "the vertical straight line", translation_jp: "垂直の直線" },
    { word: "der Prüfling", translation_en: "the examinee", translation_jp: "受験生" },
    { word: "die injektive Abbildung", translation_en: "the injective mapping", translation_jp: "単射写像" },
    { word: "der Anstieg", translation_en: "the rise", translation_jp: "上昇" },
    { word: "das geschlossene Intervall", translation_en: "the closed interval", translation_jp: "閉じた間隔" },
    { word: "die Variable", translation_en: "the variable", translation_jp: "変数" },
    { word: "der Abstand", translation_en: "the distance", translation_jp: "距離" },
    { word: "der Kubus", translation_en: "the cube", translation_jp: "立方体" },
    { word: "die Norm", translation_en: "the norm", translation_jp: "標準" },
    { word: "das Viereck", translation_en: "the square", translation_jp: "広場" },
    { word: "die Kehrzahl", translation_en: "the reciprocal", translation_jp: "相互" },
    { word: "der Durchmesser eines Kreises", translation_en: "the diameter of a circle", translation_jp: "円の直径" },
    { word: "der Koordinatenursprung", translation_en: "the coordinate origin", translation_jp: "座標原点" },
    { word: "die Wertetabelle", translation_en: "the table of values", translation_jp: "価値観の表" },
    { word: "die Stichprobenerhebung", translation_en: "the sample survey", translation_jp: "サンプル調査" },
    { word: "das Zweifache", translation_en: "twice as much", translation_jp: "2倍" },
    { word: "die Stelle", translation_en: "the spot", translation_jp: "現場" },
    { word: "die Anzahl an Punkten", translation_en: "the number of points", translation_jp: "ポイント数" },
    { word: "die horizontale Asymptote", translation_en: "the horizontal asymptote", translation_jp: "水平漸近線" },
    { word: "abziehen", translation_en: "deduct", translation_jp: "控除する" },
    { word: "das Intervall", translation_en: "the interval", translation_jp: "間隔" },
    { word: "die Umgebung einer Stelle", translation_en: "the surroundings of a place", translation_jp: "ある場所の周囲" },
    { word: "abstreichen", translation_en: "wipe off", translation_jp: "拭き取る" },
    { word: "das Bild", translation_en: "the picture", translation_jp: "絵" },
    { word: "die Ordinate", translation_en: "the ordinate", translation_jp: "縦座標" },
    { word: "die erste Ableitung", translation_en: "the first derivative", translation_jp: "一次導関数" },
    { word: "die Bernouillikette", translation_en: "the Bernouilli chain", translation_jp: "ベルヌーイ連鎖" },
    { word: "das rechnerische Verfahren", translation_en: "the computational procedure", translation_jp: "計算手順" },
    { word: "die Fläche", translation_en: "the area", translation_jp: "地域" },
    { word: "verallgemeinern", translation_en: "generalize", translation_jp: "一般化する" },
    { word: "der Mittelpunkt des Inkreises", translation_en: "the center of the incircle", translation_jp: "内接円の中心" },
    { word: "das Anfangsglied", translation_en: "the initial link", translation_jp: "最初のリンク" },
    { word: "die Funktion", translation_en: "the function", translation_jp: "機能" },
    { word: "der Ursprung", translation_en: "the origin", translation_jp: "起源" },
    { word: "die Tafel", translation_en: "the whiteboard", translation_jp: "ホワイトボード" },
    { word: "die Regel", translation_en: "the rule", translation_jp: "ルール" },
    { word: "die ganzen Zahlen", translation_en: "the whole numbers", translation_jp: "整数" },
    { word: "die Ergebnismenge", translation_en: "the result set", translation_jp: "結果セット" },
    { word: "die Höhe", translation_en: "the height", translation_jp: "高さ" },
    { word: "der Vorgänger", translation_en: "the predecessor", translation_jp: "前任者" },
    { word: "die Gegenzahl", translation_en: "the opposite number", translation_jp: "反対の数字" },
    { word: "das Zentrum", translation_en: "the center", translation_jp: "中心" },
    { word: "das Ergebnis", translation_en: "the result", translation_jp: "結果" },
    { word: "der Maßstab", translation_en: "the scale", translation_jp: "スケール" },
    { word: "das Vorzeichenfeld", translation_en: "the sign field", translation_jp: "サインフィールド" },
    { word: "das Änderungsverhalten", translation_en: "the change behavior", translation_jp: "変化行動" },
    { word: "das Glied", translation_en: "the limb", translation_jp: "手足" },
    { word: "das Parallelogramm", translation_en: "the parallelogram", translation_jp: "平行四辺形" },
    { word: "die eulersche Zahl", translation_en: "the Euler number", translation_jp: "オイラー数" },
    { word: "die Zahl", translation_en: "the number", translation_jp: "番号" },
    { word: "der Extremwert", translation_en: "the extreme value", translation_jp: "極値" },
    { word: "die Symmetrieeigenschaft", translation_en: "the symmetry property", translation_jp: "対称性" },
    { word: "die Vereinigung", translation_en: "the union", translation_jp: "組合" },
    { word: "die Seite", translation_en: "the page", translation_jp: "ページ" },
    { word: "die Ecken eines Vielecks", translation_en: "the corners of a polygon", translation_jp: "多角形の角" },
    { word: "die Strecke", translation_en: "the route", translation_jp: "ルート" },
    { word: "ausrechnen", translation_en: "calculate", translation_jp: "計算する" },
    { word: "die Nummer", translation_en: "the number", translation_jp: "番号" },
    { word: "die ungeordnete Auswahl", translation_en: "the unordered selection", translation_jp: "順序付けされていない選択" },
    { word: "der y-Achsenabschnitt", translation_en: "the y-intercept", translation_jp: "y 切片" },
    { word: "die y-Achse", translation_en: "the y-axis", translation_jp: "Y軸" },
    { word: "achsensymmetrisch", translation_en: "axisymmetric", translation_jp: "軸対称" },
    { word: "die Addition", translation_en: "the addition", translation_jp: "追加" },
    { word: "die Methode", translation_en: "the method", translation_jp: "方法" },
    { word: "das Rechnen", translation_en: "the calculation", translation_jp: "計算" },
    { word: "der Abschnitt", translation_en: "the section", translation_jp: "セクション" },
    { word: "das Integral", translation_en: "the integral", translation_jp: "積分" },
    { word: "die Anzahl an Elementen", translation_en: "the number of elements", translation_jp: "要素の数" },
    { word: "der linksseitige Grenzwert", translation_en: "the left-hand limit", translation_jp: "左側の限界" },
    { word: "das Malzeichen", translation_en: "the mark", translation_jp: "マーク" },
    { word: "das Symmetriezentrum", translation_en: "the center of symmetry", translation_jp: "対称の中心" },
    { word: "die Zufallsvariable", translation_en: "the random variable", translation_jp: "確率変数" },
    { word: "der Vektorraum", translation_en: "the vector space", translation_jp: "ベクトル空間" },
    { word: "der Bogen", translation_en: "the bow", translation_jp: "弓" },
    { word: "die Wendetangente", translation_en: "the turning tangent", translation_jp: "回転接線" },
    { word: "das Dreieck", translation_en: "the triangle", translation_jp: "三角形" },
    { word: "das Additionsverfahren", translation_en: "the addition process", translation_jp: "追加プロセス" },
    { word: "die Parabel", translation_en: "the parable", translation_jp: "たとえ話" },
    { word: "die Lösungsmenge", translation_en: "the solution quantity", translation_jp: "溶液の量" },
    { word: "der Bruch", translation_en: "the break", translation_jp: "休憩" },
    { word: "die Summenfunktion", translation_en: "the sum function", translation_jp: "合計関数" },
    { word: "die Konjunktion", translation_en: "the conjunction", translation_jp: "接続詞" },
    { word: "die Tangente an die Kurve", translation_en: "the tangent to the curve", translation_jp: "曲線の接線" },
    { word: "die Beziehung", translation_en: "the relationship", translation_jp: "関係" },
    { word: "die Funktionsgleichung", translation_en: "the functional equation", translation_jp: "関数方程式" },
    { word: "die Stetigkeit", translation_en: "the continuity", translation_jp: "継続性" },
    { word: "die Lösung", translation_en: "the solution", translation_jp: "解決策" },
    { word: "die Hyperbel", translation_en: "the hyperbola", translation_jp: "双曲線" },
    { word: "das Vorzeichen", translation_en: "the sign", translation_jp: "サイン" },
    { word: "beschränkt", translation_en: "limited", translation_jp: "限定" },
    { word: "das Wurzelzeichen", translation_en: "the root symbol", translation_jp: "ルートシンボル" },
    { word: "anwenden", translation_en: "apply", translation_jp: "適用する" },
    { word: "der Faktor der höchsten Potenz", translation_en: "the factor of the highest power", translation_jp: "最大電力の係数" },
    { word: "die Zufallsgröße", translation_en: "the random size", translation_jp: "ランダムなサイズ" },
    { word: "das Gleichungssystem", translation_en: "the system of equations", translation_jp: "方程式系" },
    { word: "die Produktfunktion", translation_en: "the product function", translation_jp: "製品の機能" },
    { word: "die Achse", translation_en: "the axis", translation_jp: "軸" },
    { word: "anstelle x, y einsetzen", translation_en: "insert y instead of x", translation_jp: "xの代わりにyを挿入してください" },
    { word: "der Definitionsbereich", translation_en: "the definition area", translation_jp: "定義エリア" },
    { word: "die Figur", translation_en: "the figure", translation_jp: "数字" },
    { word: "das Symbol", translation_en: "the symbol", translation_jp: "シンボル" },
    { word: "die Wahrscheinlichkeitsrechnung", translation_en: "the probability calculation", translation_jp: "確率の計算" },
    { word: "der Lösungsweg", translation_en: "the solution", translation_jp: "解決策" },
    { word: "der Rhombus", translation_en: "the rhombus", translation_jp: "ひし形" },
    { word: "beweisen", translation_en: "prove", translation_jp: "証明する" },
    { word: "die Differentialrechnung", translation_en: "the differential calculus", translation_jp: "微分積分" },
    { word: "behaupten", translation_en: "claim", translation_jp: "請求" },
    { word: "das Produkt", translation_en: "the product", translation_jp: "製品" },
    { word: "die rationalen Zahlen", translation_en: "the rational numbers", translation_jp: "有理数" },
    { word: "die Menge der ganzen Zahlen", translation_en: "the set of integers", translation_jp: "整数の集合" },
    { word: "das Maximum", translation_en: "the maximum", translation_jp: "最大の" },
    { word: "die zweite Ableitung", translation_en: "the second derivative", translation_jp: "二次導関数" },
    { word: "der Radius eines Kreises", translation_en: "the radius of a circle", translation_jp: "円の半径" },
    { word: "die Grundmenge", translation_en: "the base quantity", translation_jp: "基本量" },
    { word: "annehmen", translation_en: "assume", translation_jp: "仮定する" },
    { word: "das Minimum", translation_en: "the minimum", translation_jp: "最低限の" },
    { word: "die lineare Funktion", translation_en: "the linear function", translation_jp: "一次関数" },
    { word: "die Mittelsenkrechte", translation_en: "the perpendicular bisector", translation_jp: "垂直二等分線" },
    { word: "die Determinante", translation_en: "the determinant", translation_jp: "決定要因" },
    { word: "das Existenzsymbol", translation_en: "the symbol of existence", translation_jp: "存在の象徴" },
    { word: "der Scheitelpunkt einer Kurve", translation_en: "the apex of a curve", translation_jp: "曲線の頂点" },
    { word: "der Koeffizient", translation_en: "the coefficient", translation_jp: "係数" },
    { word: "das bestimmte Integral", translation_en: "the definite integral", translation_jp: "定積分" },
    { word: "ableitbar", translation_en: "derivable", translation_jp: "導出可能" },
    { word: "anschließend", translation_en: "afterward", translation_jp: "その後" },
    { word: "der rechtsseitige Grenzwert", translation_en: "the right-hand limit value", translation_jp: "右側の限界値" },
    { word: "die Tangensfunktion", translation_en: "the tangent function", translation_jp: "正接関数" },
    { word: "das Gesetz der grossen Zahlen", translation_en: "the law of large numbers", translation_jp: "大数の法則" },
    { word: "beschreiben", translation_en: "describe", translation_jp: "説明する" },
    { word: "die Ableitungsfunktion", translation_en: "the derivative function", translation_jp: "導関数" },
    { word: "die schiefe Asymptote", translation_en: "the skewed asymptote", translation_jp: "歪んだ漸近線" },
    { word: "die Sinusfunktion", translation_en: "the sine function", translation_jp: "正弦関数" },
    { word: "der Hauptnenner", translation_en: "the main denominator", translation_jp: "主な分母" },
    { word: "die kubische Normalfunktion", translation_en: "the cubic normal function", translation_jp: "3次正規関数" },
    { word: "der Kreisbogen", translation_en: "the circular arc", translation_jp: "円弧" },
    { word: "die bijektive Abbildung", translation_en: "the bijective mapping", translation_jp: "全単射マッピング" },
    { word: "der Parameter", translation_en: "the parameters", translation_jp: "パラメータ" },
    { word: "die binomische Formel", translation_en: "the binomial formula", translation_jp: "二項式" },
    { word: "die senkrechte Asymptote", translation_en: "the vertical asymptote", translation_jp: "垂直漸近線" },
    { word: "die Bedingung", translation_en: "the condition", translation_jp: "状態" },
    { word: "die Symmetrieachse", translation_en: "the axis of symmetry", translation_jp: "対称軸" },
    { word: "das Verfahren", translation_en: "the procedure", translation_jp: "手順" },
    { word: "der Beweis", translation_en: "the proof", translation_jp: "証拠" },
    { word: "die Anzahl", translation_en: "the number", translation_jp: "番号" },
    { word: "die Kubikzahl", translation_en: "the cubic number", translation_jp: "立方数" },
    { word: "das Rechenzeichen", translation_en: "the arithmetic symbol", translation_jp: "算術記号" },
    { word: "das Zwölfersystem", translation_en: "the twelve system", translation_jp: "十二系" },
    { word: "das Lineal", translation_en: "the ruler", translation_jp: "定規" },
    { word: "die Länge", translation_en: "the length", translation_jp: "長さ" },
    { word: "das Extremum", translation_en: "the extremum", translation_jp: "極値" },
    { word: "der Kreis", translation_en: "the circle", translation_jp: "サークル" },
    { word: "die einfache Nullstelle", translation_en: "the simple zero", translation_jp: "シンプルなゼロ" },
    { word: "die Differenzenfunktion", translation_en: "the difference function", translation_jp: "差分関数" },
    { word: "die Beweisführung", translation_en: "the evidence", translation_jp: "証拠" },
    { word: "die Abbildung", translation_en: "the illustration", translation_jp: "イラスト" },
    { word: "die Maßeinheit", translation_en: "the unit of measurement", translation_jp: "測定単位" },
    { word: "die stetige Funktion", translation_en: "the continuous function", translation_jp: "連続関数" },
    { word: "die Menge der reellen Zahlen", translation_en: "the set of real numbers", translation_jp: "実数の集合" },
    { word: "der Kreis um A", translation_en: "the circle around A", translation_jp: "Aの周りの円" },
    { word: "ausmultiplizieren", translation_en: "multiply out", translation_jp: "乗算する" },
    { word: "die Ungleichung", translation_en: "the inequality", translation_jp: "不平等" },
    { word: "eine Gleichung ansetzen", translation_en: "set up an equation", translation_jp: "方程式を立てる" },
    { word: "beliebig", translation_en: "any", translation_jp: "どれでも" },
    { word: "das Zehnersystem", translation_en: "the ten system", translation_jp: "テンシステム" },
    { word: "begründen", translation_en: "justify", translation_jp: "正当化する" },
    { word: "das Baumdiagramm", translation_en: "the tree diagram", translation_jp: "樹形図" },
    { word: "der Schwerpunkt", translation_en: "the focus", translation_jp: "焦点" },
    { word: "der Körper", translation_en: "the body", translation_jp: "体" },
    { word: "die graphische Darstellung", translation_en: "the graphic representation", translation_jp: "グラフィック表現" },
    { word: "der Grundsatz", translation_en: "the principle", translation_jp: "原則" },
    { word: "der Wertebereich", translation_en: "the range of values", translation_jp: "値の範囲" },
    { word: "die bedingte Wahrscheinlichkeit", translation_en: "the conditional probability", translation_jp: "条件付き確率" },
    { word: "der Logarithmus von drei zur Basis 10", translation_en: "the logarithm of three to base 10", translation_jp: "3 を底とする 10 の対数" },
    { word: "das Flächenmaß", translation_en: "the area measure", translation_jp: "面積の測定" },
    { word: "der Binomialkoeffizient", translation_en: "the binomial coefficient", translation_jp: "二項係数" },
    { word: "die Proportion", translation_en: "the proportion", translation_jp: "割合" },
    { word: "addieren", translation_en: "add", translation_jp: "追加" },
    { word: "der Abstand zwischen zwei Punkten", translation_en: "the distance between two points", translation_jp: "2 点間の距離" },
    { word: "der Zehner", translation_en: "the tenner", translation_jp: "テナー" },
    { word: "die arithmetische Folge", translation_en: "the arithmetic progression", translation_jp: "等差数列" },
    { word: "die Schreibweise", translation_en: "the spelling", translation_jp: "スペル" },
    { word: "die Ecke", translation_en: "the corner", translation_jp: "隅" },
    { word: "die Seitenhalbierende", translation_en: "the bisector", translation_jp: "二等分線" },
    { word: "der Strahl", translation_en: "the beam", translation_jp: "ビーム" },
    { word: "die Menge der natürlichen Zahlen", translation_en: "the set of natural numbers", translation_jp: "自然数の集合" },
    { word: "der Zirkel", translation_en: "the circle", translation_jp: "サークル" },
    { word: "das Lösungspaar", translation_en: "the pair of solutions", translation_jp: "ソリューションのペア" },
    { word: "ableiten", translation_en: "derive", translation_jp: "導き出す" },
    { word: "die ungerade Funktion", translation_en: "the odd function", translation_jp: "奇関数" },
    { word: "bestimmen", translation_en: "determine", translation_jp: "決定する" },
    { word: "die Monotonieregel", translation_en: "the monotonicity rule", translation_jp: "単調性の法則" },
    { word: "der Würfel", translation_en: "the cube", translation_jp: "立方体" },
    { word: "die Zuordnung", translation_en: "the assignment", translation_jp: "割り当て" },
    { word: "die Linkskurve", translation_en: "the left turn", translation_jp: "左折" },
    { word: "die Kosinusfunktion", translation_en: "the cosine function", translation_jp: "コサイン関数" },
    { word: "der Funktionsgraph", translation_en: "the function graph", translation_jp: "関数グラフ" },
    { word: "das Maß", translation_en: "the measure", translation_jp: "尺度" },
    { word: "der Mittelpunkt", translation_en: "the center", translation_jp: "中心" },
    { word: "aufrunden", translation_en: "round up", translation_jp: "切り上げする" },
    { word: "die Äquivalenz", translation_en: "the equivalence", translation_jp: "等価性" },
    { word: "die komplexen Zahlen", translation_en: "the complex numbers", translation_jp: "複素数" },
    { word: "das Lot", translation_en: "the plumb line", translation_jp: "鉛直線" },
    { word: "der Halbkreis", translation_en: "the semicircle", translation_jp: "半円" },
    { word: "der Punkt", translation_en: "the point", translation_jp: "要点" },
    { word: "ausführen", translation_en: "carry out", translation_jp: "実行する" },
    { word: "die Teilmenge", translation_en: "the subset", translation_jp: "サブセット" },
    { word: "die Menge der Dezimalzahlen", translation_en: "the amount of decimal numbers", translation_jp: "小数の量" },
    { word: "die Differenz", translation_en: "the difference", translation_jp: "違い" },
    { word: "der Maximalwert", translation_en: "the maximum value", translation_jp: "最大値" },
    { word: "die eckige Klammer", translation_en: "the square bracket", translation_jp: "角括弧" },
    { word: "das Trapez", translation_en: "the trapeze", translation_jp: "空中ブランコ" },
    { word: "der Durchmesser", translation_en: "the diameter", translation_jp: "直径" },
    { word: "das Theorem", translation_en: "the theorem", translation_jp: "定理" },
    { word: "die xy-Ebene", translation_en: "the xy plane", translation_jp: "xy平面" },
    { word: "die Umgebung einer Zahl", translation_en: "the environment of a number", translation_jp: "数字の環境" },
    { word: "die Klammer", translation_en: "the bracket", translation_jp: "ブラケット" },
    { word: "die Implikation", translation_en: "the implication", translation_jp: "意味合い" },
    { word: "der Tausender", translation_en: "the thousand", translation_jp: "千" },
    { word: "die Betragsfunktion", translation_en: "the amount function", translation_jp: "金額関数" },
    { word: "die Zuordnungstabelle", translation_en: "the allocation table", translation_jp: "割り当てテーブル" },
    { word: "die Strichrechnung", translation_en: "the line calculation", translation_jp: "ライン計算" },
    { word: "die Zeichnung", translation_en: "the drawing", translation_jp: "図面" },
    { word: "das Dezimalsystem", translation_en: "the decimal system", translation_jp: "10進法" },
    { word: "die Senkrechte", translation_en: "the vertical", translation_jp: "垂直の" },
    { word: "das graphische Verfahren", translation_en: "the graphic process", translation_jp: "グラフィックプロセス" },
    { word: "der Bruchstrich", translation_en: "the fraction line", translation_jp: "分数線" },
    { word: "berechnen", translation_en: "calculate", translation_jp: "計算する" },
    { word: "gebrauchen", translation_en: "use", translation_jp: "使用" },
    { word: "präzisieren", translation_en: "specify", translation_jp: "特定" },
    { word: "linksgekrümmt", translation_en: "curved to the left", translation_jp: "左に曲がった" },
    { word: "geeignet", translation_en: "suitable", translation_jp: "適切な" },
    { word: "stellen", translation_en: "place", translation_jp: "場所" },
    { word: "die Klammer auflösen", translation_en: "dissolve the bracket", translation_jp: "ブラケットを溶かす" },
    { word: "untersuchen", translation_en: "investigate", translation_jp: "調査する" },
    { word: "gegen plus unendlich streben", translation_en: "strive towards plus infinity", translation_jp: "プラスの無限大を目指して" },
    { word: "vereinigt mit", translation_en: "united with", translation_jp: "と団結した" },
    { word: "vereinfacht", translation_en: "simplified", translation_jp: "簡略化された" },
    { word: "es gelten die folgenden Aussagen", translation_en: "the following statements apply", translation_jp: "次の記述が適用されます" },
    { word: "eine reelle Zahl", translation_en: "a real number", translation_jp: "実数" },
    { word: "daraus ergibt sich für alle Dreiecke die Formel", translation_en: "This results in the formula for all triangles", translation_jp: "これにより、すべての三角形の公式が得られます。" },
    { word: "stetig", translation_en: "steadily", translation_jp: "着実に" },
    { word: "sonst", translation_en: "otherwise", translation_jp: "さもないと" },
    { word: "rechtwinkliges Dreieck", translation_en: "right triangle", translation_jp: "直角三角形" },
    { word: "vermindert um", translation_en: "reduced by", translation_jp: "によって削減される" },
    { word: "daraus folgt", translation_en: "it follows", translation_jp: "それは続きます" },
    { word: "schneiden", translation_en: "cut", translation_jp: "カット" },
    { word: "vergleichen", translation_en: "compare", translation_jp: "比較する" },
    { word: "gegeben sind", translation_en: "are given", translation_jp: "与えられる" },
    { word: "gleichnamig setzen", translation_en: "put with the same name", translation_jp: "同じ名前で置く" },
    { word: "vereinbar", translation_en: "compatible", translation_jp: "互換性がある" },
    { word: "Die Umkehrung", translation_en: "The reversal", translation_jp: "逆転" },
    { word: "eine Eigenschaft beweisen", translation_en: "prove a property", translation_jp: "財産を証明する" },
    { word: "in etw. enthalten sein", translation_en: "to be contained in sth", translation_jp: "sth に含まれる" },
    { word: "und", translation_en: "and", translation_jp: "そして" },
    { word: "faktorisieren", translation_en: "factorize", translation_jp: "因数分解する" },
    { word: "ermitteln", translation_en: "determine", translation_jp: "決定する" },
    { word: "Ich dividiere durch 5", translation_en: "I divide by 5", translation_jp: "5で割ります" },
    { word: "voraussetzen", translation_en: "assume", translation_jp: "仮定する" },
    { word: "vernachlässigen", translation_en: "neglect", translation_jp: "無視する" },
    { word: "mit Beachtung der Reihenfolge", translation_en: "with attention to the order", translation_jp: "順序に注意して" },
    { word: "keiner der beiden", translation_en: "neither of them", translation_jp: "どちらでもない" },
    { word: "streng fallend", translation_en: "strictly falling", translation_jp: "厳密に落ちる" },
    { word: "maximieren", translation_en: "maximize", translation_jp: "最大化する" },
    { word: "verdreifachen", translation_en: "triple", translation_jp: "トリプル" },
    { word: "minimieren", translation_en: "minimize", translation_jp: "最小化する" },
    { word: "es ergibt sich die Gleichheit", translation_en: "Equality results", translation_jp: "平等の結果" },
    { word: "raten", translation_en: "guess", translation_jp: "推測" },
    { word: "wenn nicht", translation_en: "unless", translation_jp: "ない限り" },
    { word: "es ergibt sich der Wert", translation_en: "the value results", translation_jp: "値の結果" },
    { word: "führen", translation_en: "lead", translation_jp: "鉛" },
    { word: "entsprechen", translation_en: "are equivalent to", translation_jp: "と同等です" },
    { word: "unbestimmt", translation_en: "indefinite", translation_jp: "不定" },
    { word: "positiv", translation_en: "positive", translation_jp: "ポジティブ" },
    { word: "überprüfen ob", translation_en: "check whether", translation_jp: "かどうかを確認してください" },
    { word: "eine ganze Zahl", translation_en: "an integer", translation_jp: "整数" },
    { word: "ungefähr", translation_en: "approximately", translation_jp: "約" },
    { word: "gleichständig", translation_en: "equal", translation_jp: "等しい" },
    { word: "senkrecht", translation_en: "perpendicular", translation_jp: "垂直" },
    { word: "es handelt sich um", translation_en: "it is a matter of", translation_jp: "それは問題です" },
    { word: "Eine Hypothese aufstellen", translation_en: "Create a hypothesis", translation_jp: "仮説を立てる" },
    { word: "durch einen Punkt gehen", translation_en: "go through a point", translation_jp: "点を通過する" },
    { word: "GGT, der größte gemeinsame Teiler", translation_en: "GGT, the greatest common divisor", translation_jp: "GGT、最大公約数" },
    { word: "parallel zu einer Geraden", translation_en: "parallel to a straight line", translation_jp: "直線に平行" },
    { word: "erfüllen", translation_en: "fulfill", translation_jp: "満たす" },
    { word: "einsetzen", translation_en: "insert", translation_jp: "入れる" },
    { word: "steigen", translation_en: "climb", translation_jp: "登る" },
    { word: "ungleich Null", translation_en: "not equal to zero", translation_jp: "ゼロに等しくない" },
    { word: "übertragen", translation_en: "transmitted", translation_jp: "送信されました" },
    { word: "also", translation_en: "so", translation_jp: "それで" },
    { word: "KGV, das kleinste gemeinsame Vielfache", translation_en: "P/E ratio, the least common multiple", translation_jp: "PER、最小公倍数" },
    { word: "gleich Null", translation_en: "equal to zero", translation_jp: "ゼロに等しい" },
    { word: "die Schlussfolgerung", translation_en: "the conclusion", translation_jp: "結論" },
    { word: "nehmen wir an dass", translation_en: "let's assume that", translation_jp: "それを仮定しましょう" },
    { word: "numerieren", translation_en: "number", translation_jp: "番号" },
    { word: "eine Wurzel", translation_en: "a root", translation_jp: "根" },
    { word: "der Schluss", translation_en: "the conclusion", translation_jp: "結論" },
    { word: "gerade", translation_en: "straight", translation_jp: "真っ直ぐ" },
    { word: "umwandeln", translation_en: "convert", translation_jp: "変換する" },
    { word: "umkehren", translation_en: "reverse", translation_jp: "逆行する" },
    { word: "paarweise disjunkt", translation_en: "disjoint in pairs", translation_jp: "ペアが素である" },
    { word: "senkrecht zu einer Geraden", translation_en: "perpendicular to a straight line", translation_jp: "直線に垂直な" },
    { word: "sich mit etw. befassen", translation_en: "to deal with sth", translation_jp: "sthに対処する" },
    { word: "streng steigend", translation_en: "strictly rising", translation_jp: "厳密に上昇" },
    { word: "ein einheitliches Vorzeichen", translation_en: "a uniform sign", translation_jp: "ユニフォームのサイン" },
    { word: "isolieren", translation_en: "isolate", translation_jp: "隔離する" },
    { word: "vermuten", translation_en: "assume", translation_jp: "仮定する" },
    { word: "eine irrationale Zahl", translation_en: "an irrational number", translation_jp: "無理数" },
    { word: "man kann daraus schliessen", translation_en: "one can conclude from this", translation_jp: "これから結論付けることができます" },
    { word: "eindeutig", translation_en: "clearly", translation_jp: "明らかに" },
    { word: "vermindern", translation_en: "reduce", translation_jp: "減らす" },
    { word: "vielfach", translation_en: "many times", translation_jp: "何度も" },
    { word: "symmetrisch zum Punkt A", translation_en: "symmetrical to point A", translation_jp: "点Aに対して対称" },
    { word: "geteilt", translation_en: "divided", translation_jp: "分割された" },
    { word: "eine Potenz", translation_en: "a power", translation_jp: "力" },
    { word: "horizontal", translation_en: "horizontal", translation_jp: "水平" },
    { word: "ein gleichschenkliges Dreieck", translation_en: "an isosceles triangle", translation_jp: "二等辺三角形" },
    { word: "gegeben ist", translation_en: "is given", translation_jp: "与えられる" },
    { word: "entstehen", translation_en: "arise", translation_jp: "起きる" },
    { word: "ersetzen", translation_en: "substitute", translation_jp: "代わりの" },
    { word: "ungleich", translation_en: "unequal", translation_jp: "不平等" },
    { word: "für x gegen plus unendlich", translation_en: "for x towards plus infinity", translation_jp: "x の場合はプラスの無限大に向けて" },
    { word: "eine Rechnung", translation_en: "an invoice", translation_jp: "請求書" },
    { word: "man kann daraus folgern", translation_en: "one can conclude from this", translation_jp: "これから結論付けることができます" },
    { word: "erhalten", translation_en: "receive", translation_jp: "受け取る" },
    { word: "zusammenzählen", translation_en: "add up", translation_jp: "合計する" },
    { word: "hoch drei", translation_en: "to the power of three", translation_jp: "3 乗" },
    { word: "doppelt", translation_en: "double", translation_jp: "ダブル" },
    { word: "eine Zahl mit einer anderen multiplizieren", translation_en: "multiply one number by another", translation_jp: "ある数値と別の数値を掛ける" },
    { word: "Am Ende eines Beweises schreibt man", translation_en: "At the end of a proof you write", translation_jp: "証明の最後に次のように書きます" },
    { word: "mehrstufig", translation_en: "multi-stage", translation_jp: "多段式" },
    { word: "folglich", translation_en: "consequently", translation_jp: "その結果" },
    { word: "schreiben", translation_en: "write", translation_jp: "書く" },
    { word: "fallend", translation_en: "falling", translation_jp: "落ちる" },
    { word: "die Behauptung", translation_en: "the claim", translation_jp: "主張" },
    { word: "gelten", translation_en: "apply", translation_jp: "適用する" },
    { word: "ein gleichseitiges Dreieck", translation_en: "an equilateral triangle", translation_jp: "正三角形" },
    { word: "beziehungsweise", translation_en: "respectively", translation_jp: "それぞれ" },
    { word: "weil", translation_en: "because", translation_jp: "なぜなら" },
    { word: "dividieren durch", translation_en: "divide by", translation_jp: "で割る" },
    { word: "parallel", translation_en: "parallel", translation_jp: "平行" },
    { word: "streichen", translation_en: "cancel", translation_jp: "キャンセル" },
    { word: "rechnen", translation_en: "calculate", translation_jp: "計算する" },
    { word: "zwei Punkte verbinden", translation_en: "connect two points", translation_jp: "2点を結ぶ" },
    { word: "skizzieren", translation_en: "sketch", translation_jp: "スケッチ" },
    { word: "einer Sache zugrunde liegen", translation_en: "underlie something", translation_jp: "何かの根底にある" },
    { word: "ergänzen", translation_en: "add to", translation_jp: "に追加" },
    { word: "mit Zurücklegen", translation_en: "with putting it back", translation_jp: "元に戻すと" },
    { word: "angenommen dass", translation_en: "assumed that", translation_jp: "と仮定した" },
    { word: "eine Funktion", translation_en: "a function", translation_jp: "関数" },
    { word: "vermehren", translation_en: "multiply", translation_jp: "乗算する" },
    { word: "da", translation_en: "there", translation_jp: "そこには" },
    { word: "zunehmend", translation_en: "increasingly", translation_jp: "ますます" },
    { word: "vervielfachen", translation_en: "multiply", translation_jp: "乗算する" },
    { word: "kürzen", translation_en: "shorten", translation_jp: "短くする" },
    { word: "einen Punkt setzen", translation_en: "put a point", translation_jp: "点を置く" },
    { word: "zeichnen", translation_en: "draw", translation_jp: "描く" },
    { word: "weder noch", translation_en: "neither nor", translation_jp: "どちらでもない" },
    { word: "ohne Null", translation_en: "without zero", translation_jp: "ゼロなし" },
    { word: "erstellen", translation_en: "create", translation_jp: "作成する" },
    { word: "rechnerisch", translation_en: "computationally", translation_jp: "計算的に" },
    { word: "eine Rechnung durchführen", translation_en: "carry out an invoice", translation_jp: "請求書を発行する" },
    { word: "eine Operation", translation_en: "an operation", translation_jp: "手術" },
    { word: "es gilt die folgende Formel", translation_en: "the following formula applies", translation_jp: "次の式が適用されます" },
    { word: "gleichwahrscheinlich", translation_en: "equally likely", translation_jp: "同じくらいの確率で" },
    { word: "schrittweise", translation_en: "gradually", translation_jp: "徐々に" },
    { word: "geringer", translation_en: "lower", translation_jp: "より低い" },
    { word: "ganz", translation_en: "quite", translation_jp: "とても" },
    { word: "nicht beide zugleich", translation_en: "not both at the same time", translation_jp: "両方同時にではない" },
    { word: "waagerecht", translation_en: "horizontally", translation_jp: "水平方向" },
    { word: "zunehmen", translation_en: "gain weight", translation_jp: "体重が増える" },
    { word: "denn", translation_en: "because", translation_jp: "なぜなら" },
    { word: "eintragen", translation_en: "register", translation_jp: "登録する" },
    { word: "errichten", translation_en: "build", translation_jp: "建てる" },
    { word: "potenzieren", translation_en: "potentiate", translation_jp: "強化する" },
    { word: "eine natürliche Zahl", translation_en: "a natural number", translation_jp: "自然数" },
    { word: "verschieden", translation_en: "different", translation_jp: "違う" },
    { word: "dann", translation_en: "then", translation_jp: "それから" },
    { word: "angenommen, es wäre nicht so", translation_en: "suppose it wasn't so", translation_jp: "そうではなかったと思います" },
    { word: "die Grundvoraussetzung", translation_en: "the basic requirement", translation_jp: "基本的な要件" },
    { word: "folgern", translation_en: "conclude", translation_jp: "結論する" },
    { word: "ist eine Teilmenge von", translation_en: "is a subset of", translation_jp: "のサブセットです" },
    { word: "ordnen", translation_en: "arrange", translation_jp: "整える" },
    { word: "Nach dem Satz gilt", translation_en: "According to the sentence:", translation_jp: "文によると：" },
    { word: "konstruieren", translation_en: "construct", translation_jp: "構築する" },
    { word: "wiedergeben", translation_en: "reproduce", translation_jp: "再現する" },
    { word: "die Voraussetzung", translation_en: "the prerequisite", translation_jp: "前提条件" },
    { word: "mit wachsendem x", translation_en: "with increasing x", translation_jp: "x が増加するにつれて" },
    { word: "streng monoton", translation_en: "strictly monotonous", translation_jp: "まったく単調な" },
    { word: "etw. annehmen", translation_en: "accept sth", translation_jp: "受け入れます" },
    { word: "die Annahme", translation_en: "the acceptance", translation_jp: "受け入れ" },
    { word: "einzig", translation_en: "only", translation_jp: "のみ" },
    { word: "kleiner", translation_en: "smaller", translation_jp: "小さい" },
    { word: "senkrecht auf einer Geraden", translation_en: "perpendicular to a straight line", translation_jp: "直線に垂直な" },
    { word: "zu etw. gehören", translation_en: "belong to sth", translation_jp: "sthに所属" },
    { word: "es ergibt sich", translation_en: "it turns out", translation_jp: "それは判明しました" },
    { word: "gleichschenkliges Dreieck", translation_en: "isosceles triangle", translation_jp: "二等辺三角形" },
    { word: "mit Hilfe des Lineals", translation_en: "with the help of the ruler", translation_jp: "支配者の助けを借りて" },
    { word: "gleichschenklig", translation_en: "isosceles", translation_jp: "二等辺三角形" },
    { word: "zusammenfassen", translation_en: "summarize", translation_jp: "要約する" },
    { word: "graphisch", translation_en: "graphically", translation_jp: "グラフィック的に" },
    { word: "geordnet", translation_en: "ordered", translation_jp: "注文した" },
    { word: "vertikal", translation_en: "vertical", translation_jp: "垂直" },
    { word: "symmetrisch zur y-Achse", translation_en: "symmetrical to the y-axis", translation_jp: "y 軸に対して対称" },
    { word: "eine Summe berechnen", translation_en: "calculate a sum", translation_jp: "合計を計算する" },
    { word: "ungerade", translation_en: "odd", translation_jp: "奇数" },
    { word: "schraffieren", translation_en: "hatch", translation_jp: "ハッチ" },
    { word: "oder", translation_en: "or", translation_jp: "または" },
    { word: "wählen", translation_en: "choose", translation_jp: "選ぶ" },
    { word: "entsprechend", translation_en: "accordingly", translation_jp: "それに応じて" },
    { word: "ein rechtwinkliges Dreieck", translation_en: "a right triangle", translation_jp: "直角三角形" },
    { word: "einen Abstand messen", translation_en: "measure a distance", translation_jp: "距離を測る" },
    { word: "teilbar", translation_en: "divisible", translation_jp: "割り切れる" },
    { word: "ungleich sein", translation_en: "be unequal", translation_jp: "不平等である" },
    { word: "verwandeln", translation_en: "transform", translation_jp: "変身" },
    { word: "löse nach x auf", translation_en: "solve for x", translation_jp: "xを解く" },
    { word: "f strich", translation_en: "f struck", translation_jp: "打った" },
    { word: "gleich sein", translation_en: "be the same", translation_jp: "同じである" },
    { word: "das widerspicht der Annahme", translation_en: "that contradicts the assumption", translation_jp: "それは仮定に矛盾します" },
    { word: "Werte annehmen", translation_en: "Accept values", translation_jp: "値を受け入れる" },
    { word: "vervollständigen", translation_en: "complete", translation_jp: "完了" },
    { word: "lösen", translation_en: "solve", translation_jp: "解決する" },
    { word: "abzählbar", translation_en: "countable", translation_jp: "数えられる" },
    { word: "unendlich viele Lösungen", translation_en: "infinite number of solutions", translation_jp: "無限の解" },
    { word: "gleich", translation_en: "even", translation_jp: "平" },
    { word: "entscheiden", translation_en: "decide", translation_jp: "決める" },
    { word: "zeichnerisch", translation_en: "graphically", translation_jp: "グラフィック的に" },
    { word: "sich schneiden", translation_en: "intersect", translation_jp: "交差する" },
    { word: "die Konsequenz", translation_en: "the consequence", translation_jp: "結果" },
    { word: "eine rationale Zahl", translation_en: "a rational number", translation_jp: "有理数" },
    { word: "eine Wurzel ziehen", translation_en: "pull a root", translation_jp: "根を抜く" },
    { word: "teilen", translation_en: "split", translation_jp: "スプリット" },
    { word: "kleiner oder gleich", translation_en: "less than or equal", translation_jp: "以下" },
    { word: "vereinfachen", translation_en: "simplify", translation_jp: "単純化する" },
    { word: "geschnitten mit", translation_en: "cut with", translation_jp: "でカット" },
    { word: "enthalten sein in Q", translation_en: "be contained in Q", translation_jp: "Qに含まれる" },
    { word: "höchstens", translation_en: "at most", translation_jp: "せいぜい" },
    { word: "eine Rechnung ausführen", translation_en: "carry out an invoice", translation_jp: "請求書を発行する" },
    { word: "daher", translation_en: "therefore", translation_jp: "したがって" },
    { word: "messen", translation_en: "measure", translation_jp: "測定" },
    { word: "zählen", translation_en: "to count", translation_jp: "数える" },
    { word: "steigend", translation_en: "rising", translation_jp: "上昇中" },
    { word: "optimieren", translation_en: "optimize", translation_jp: "最適化する" },
    { word: "differenzieren", translation_en: "differentiate", translation_jp: "差別化する" },
    { word: "zum Beispiel", translation_en: "for example", translation_jp: "例えば" },
    { word: "integrieren", translation_en: "integrate", translation_jp: "統合する" },
    { word: "monoton", translation_en: "monotonous", translation_jp: "単調な" },
    { word: "suchen", translation_en: "seek", translation_jp: "求める" },
    { word: "vorteilhaft", translation_en: "advantageous", translation_jp: "有利" },
    { word: "punktsymmetrisch", translation_en: "point symmetric", translation_jp: "点対称" },
    { word: "schätzen", translation_en: "treasure", translation_jp: "宝物" },
    { word: "anderenfalls", translation_en: "otherwise", translation_jp: "さもないと" },
    { word: "keine Lösung", translation_en: "no solution", translation_jp: "解決策がない" },
    { word: "unvereinbar", translation_en: "incompatible", translation_jp: "互換性のない" },
    { word: "zuordnen", translation_en: "assign", translation_jp: "割り当てる" },
    { word: "deshalb", translation_en: "for this reason", translation_jp: "このため" },
    { word: "verdoppeln", translation_en: "double", translation_jp: "ダブル" },
    { word: "eine Primzahl", translation_en: "a prime number", translation_jp: "素数" },
    { word: "vermehrt um", translation_en: "increased by", translation_jp: "増加しました" },
    { word: "für x gegen minus unendlich", translation_en: "for x towards minus infinity", translation_jp: "x がマイナス無限大に向かう場合" },
    { word: "ergeben", translation_en: "result", translation_jp: "結果" },
    { word: "gleichnamig", translation_en: "same name", translation_jp: "同じ名前" },
    { word: "nicht erfüllbare Gleichung", translation_en: "unsatisfiable equation", translation_jp: "満たされない方程式" },
    { word: "dreifach", translation_en: "triple", translation_jp: "トリプル" },
    { word: "gleichseitiges Dreieck", translation_en: "equilateral triangle", translation_jp: "正三角形" },
    { word: "in einen Kreis eingeschrieben sein", translation_en: "be inscribed in a circle", translation_jp: "円に内接する" },
    { word: "finden", translation_en: "find", translation_jp: "探す" },
    { word: "erläutern", translation_en: "explain", translation_jp: "説明する" },
    { word: "quadrat", translation_en: "square", translation_jp: "四角" },
    { word: "gleichbedeutend", translation_en: "equivalent", translation_jp: "同等" },
    { word: "wenn, dann", translation_en: "if, then", translation_jp: "もし、それでは" },
    { word: "meinen", translation_en: "mean", translation_jp: "平均" },
    { word: "erweitern", translation_en: "expand", translation_jp: "拡大する" },
    { word: "mit einer Zahl multiplizieren", translation_en: "multiply by a number", translation_jp: "数値を掛ける" },
    { word: "negativ", translation_en: "negative", translation_jp: "ネガティブ" },
    { word: "Dieses ist ein Widerspruch, also muss die Annahme falsch sein", translation_en: "This is a contradiction, so the assumption must be wrong", translation_jp: "これは矛盾しているので、仮定が間違っているはずです" },
    { word: "jeweils", translation_en: "respectively", translation_jp: "それぞれ" },
    { word: "eine Schlussfolgerung ziehen", translation_en: "draw a conclusion", translation_jp: "結論を出す" },
    { word: "einen Punkt auf eine Gerade setzen", translation_en: "put a point on a line", translation_jp: "直線上に点を置く" },
    { word: "hoch zwei", translation_en: "to the power of two", translation_jp: "2のべき乗" },
    { word: "rechtsgekrümmt", translation_en: "curved to the right", translation_jp: "右に曲がった" },
    { word: "umgekehrt", translation_en: "vice versa", translation_jp: "逆に" },
    { word: "mit drei potenzieren", translation_en: "raise to the power of three", translation_jp: "3 乗する" },
    { word: "ansonsten", translation_en: "otherwise", translation_jp: "さもないと" },
    { word: "gleichseitig", translation_en: "equilateral", translation_jp: "等辺" },
    { word: "zeigen", translation_en: "show", translation_jp: "見せる" },
    { word: "mindestens", translation_en: "at least", translation_jp: "少なくとも" },
    { word: "verändern", translation_en: "change", translation_jp: "変化" },
    { word: "größer", translation_en: "bigger", translation_jp: "より大きな" },
    { word: "in Faktoren zerlegen", translation_en: "break it down into factors", translation_jp: "要素に分解してみる" },
    { word: "eine Strecke halbieren", translation_en: "halve a distance", translation_jp: "距離を半分にする" },
    { word: "nennen", translation_en: "to name", translation_jp: "名前を付ける" },
    { word: "zugehörig", translation_en: "associated", translation_jp: "関連する" },
    { word: "größer oder gleich", translation_en: "greater than or equal to", translation_jp: "以上" },
    { word: "halb", translation_en: "half", translation_jp: "半分" },
    { word: "eine Dezimalzahl", translation_en: "a decimal number", translation_jp: "10進数" },
    { word: "enthalten", translation_en: "contain", translation_jp: "含む" },
    { word: "ohne Zurücklegen", translation_en: "without putting it back", translation_jp: "元に戻さずに" },
    { word: "genau", translation_en: "Exactly", translation_jp: "その通り" },
    { word: "rechtfertigen", translation_en: "justify", translation_jp: "正当化する" },
];