export const records: { word: string, translation_en: string, translation_jp: string }[] = [
    { word: "ieri", translation_en: "Yesterday", translation_jp: "昨日" },
    { word: "il cuore", translation_en: "the heart", translation_jp: "心" },
    { word: "un francobollo", translation_en: "a stamp", translation_jp: "スタンプ" },
    { word: "un immobile", translation_en: "a property", translation_jp: "財産" },
    { word: "un lupo", translation_en: "a wolf", translation_jp: "オオカミ" },
    { word: "la neve", translation_en: "the snow", translation_jp: "雪" },
    { word: "una camicia", translation_en: "a shirt", translation_jp: "シャツ" },
    { word: "la carne", translation_en: "the meat", translation_jp: "肉" },
    { word: "un porto", translation_en: "a port", translation_jp: "港" },
    { word: "una casa", translation_en: "a house", translation_jp: "家" },
    { word: "caldo", translation_en: "heat", translation_jp: "熱" },
    { word: "un partito", translation_en: "a party", translation_jp: "パーティー" },
    { word: "un dente", translation_en: "a tooth", translation_jp: "歯" },
    { word: "il tè", translation_en: "tea", translation_jp: "お茶" },
    { word: "una coperta", translation_en: "a blanket", translation_jp: "毛布" },
    { word: "una ragazza giovane", translation_en: "a young girl", translation_jp: "若い女の子" },
    { word: "il pepe", translation_en: "the pepper", translation_jp: "コショウ" },
    { word: "una scuola", translation_en: "a school", translation_jp: "学校" },
    { word: "provare", translation_en: "try", translation_jp: "試す" },
    { word: "un frigorifero", translation_en: "a refrigerator", translation_jp: "冷蔵庫" },
    { word: "dimenticare", translation_en: "forget", translation_jp: "忘れる" },
    { word: "una lettera", translation_en: "a letter", translation_jp: "手紙" },
    { word: "un zaino", translation_en: "a backpack", translation_jp: "バックパック" },
    { word: "un maestro", translation_en: "a master", translation_jp: "マスター" },
    { word: "ricordarsi", translation_en: "remember", translation_jp: "覚えて" },
    { word: "bagnarsi", translation_en: "get wet", translation_jp: "濡れる" },
    { word: "un telefono", translation_en: "a telephone", translation_jp: "電話" },
    { word: "benvenuto !", translation_en: "welcome !", translation_jp: "いらっしゃいませ ！" },
    { word: "martedì", translation_en: "Tuesday", translation_jp: "火曜日" },
    { word: "l'industria", translation_en: "the industry", translation_jp: "業界" },
    { word: "solo", translation_en: "Alone", translation_jp: "一人で" },
    { word: "un tappeto", translation_en: "a carpet", translation_jp: "カーペット" },
    { word: "una porta", translation_en: "a door", translation_jp: "ドア" },
    { word: "malato", translation_en: "sick", translation_jp: "病気" },
    { word: "la verdura", translation_en: "the vegetables", translation_jp: "野菜" },
    { word: "scrivere", translation_en: "write", translation_jp: "書く" },
    { word: "a presto !", translation_en: "Soon !", translation_jp: "すぐ ！" },
    { word: "difficile", translation_en: "difficult", translation_jp: "難しい" },
    { word: "l'Aids", translation_en: "AIDS", translation_jp: "エイズ" },
    { word: "oggi", translation_en: "Today", translation_jp: "今日" },
    { word: "pieno", translation_en: "full", translation_jp: "満杯" },
    { word: "l'uscita", translation_en: "the exit", translation_jp: "出口" },
    { word: "il vino", translation_en: "the wine", translation_jp: "ワイン" },
    { word: "molto", translation_en: "Very", translation_jp: "とても" },
    { word: "bisogna ...", translation_en: "must ...", translation_jp: "しなければならない ..." },
    { word: "un infante", translation_en: "an infant", translation_jp: "幼児" },
    { word: "un ragazzino", translation_en: "a little boy", translation_jp: "小さな男の子" },
    { word: "il formaggio", translation_en: "the cheese", translation_jp: "チーズ" },
    { word: "un'albicocca", translation_en: "an apricot", translation_jp: "アプリコット" },
    { word: "la direzione", translation_en: "the direction", translation_jp: "方向" },
    { word: "prendere", translation_en: "take", translation_jp: "取る" },
    { word: "il matrimonio", translation_en: "the wedding", translation_jp: "結婚式" },
    { word: "un viaggio", translation_en: "a trip", translation_jp: "旅行" },
    { word: "anziano", translation_en: "elderly", translation_jp: "お年寄り" },
    { word: "ancora", translation_en: "Still", translation_jp: "まだ" },
    { word: "apportare", translation_en: "make", translation_jp: "作る" },
    { word: "uscire", translation_en: "go out", translation_jp: "外出" },
    { word: "una frontiera", translation_en: "a frontier", translation_jp: "フロンティア" },
    { word: "un ristorante", translation_en: "a restaurant", translation_jp: "レストラン" },
    { word: "un canale", translation_en: "a channel", translation_jp: "チャンネル" },
    { word: "il latte", translation_en: "milk", translation_jp: "牛乳" },
    { word: "un istitutore", translation_en: "an instructor", translation_jp: "インストラクター" },
    { word: "la colazione", translation_en: "breakfast", translation_jp: "朝食" },
    { word: "una stanza", translation_en: "a room", translation_jp: "部屋" },
    { word: "buono", translation_en: "Good", translation_jp: "良い" },
    { word: "la birra", translation_en: "the beer", translation_jp: "ビール" },
    { word: "un foglio", translation_en: "a sheet", translation_jp: "シート" },
    { word: "ascoltare", translation_en: "listen", translation_jp: "聞く" },
    { word: "un'isola", translation_en: "an island", translation_jp: "島" },
    { word: "un pompiere", translation_en: "a fireman", translation_jp: "消防士" },
    { word: "un lavoratore", translation_en: "a worker", translation_jp: "労働者" },
    { word: "una ciliegia", translation_en: "a cherry", translation_jp: "さくらんぼ" },
    { word: "il caffè", translation_en: "the coffee", translation_jp: "コーヒー" },
    { word: "una finestra", translation_en: "a window", translation_jp: "窓" },
    { word: "il pranzo", translation_en: "lunch", translation_jp: "ランチ" },
    { word: "un lago", translation_en: "a lake", translation_jp: "湖" },
    { word: "l'arte", translation_en: "the art", translation_jp: "芸術" },
    { word: "mi chiamo Marta", translation_en: "My name is Marta", translation_jp: "私の名前はマルタです" },
    { word: "cuocere", translation_en: "cook", translation_jp: "料理する" },
    { word: "la borsa", translation_en: "the bag", translation_jp: "バッグ" },
    { word: "dritto", translation_en: "straight", translation_jp: "真っ直ぐ" },
    { word: "l'educazione", translation_en: "education", translation_jp: "教育" },
    { word: "una farmacia", translation_en: "a pharmacy", translation_jp: "薬局" },
    { word: "una farfalla", translation_en: "a butterfly", translation_jp: "蝶" },
    { word: "la foresta", translation_en: "the forest", translation_jp: "森" },
    { word: "il cielo", translation_en: "the sky", translation_jp: "空" },
    { word: "aiutare", translation_en: "help", translation_jp: "ヘルプ" },
    { word: "l'oro", translation_en: "They", translation_jp: "彼らは" },
    { word: "una cipolla", translation_en: "an onion", translation_jp: "玉ねぎ" },
    { word: "il petrolio", translation_en: "oil", translation_jp: "油" },
    { word: "un farmaco", translation_en: "a drug", translation_jp: "薬" },
    { word: "il cancro", translation_en: "cancer", translation_jp: "癌" },
    { word: "giovane", translation_en: "young", translation_jp: "若い" },
    { word: "una fabbricca", translation_en: "a factory", translation_jp: "工場" },
    { word: "la pioggia", translation_en: "the rain", translation_jp: "雨" },
    { word: "chiedere", translation_en: "ask", translation_jp: "聞く" },
    { word: "un lattante", translation_en: "an infant", translation_jp: "幼児" },
    { word: "io", translation_en: "I", translation_jp: "私" },
    { word: "dietro", translation_en: "behind", translation_jp: "後ろに" },
    { word: "parlare", translation_en: "speak", translation_jp: "話す" },
    { word: "basso", translation_en: "Bass", translation_jp: "ベース" },
    { word: "un uccello", translation_en: "a bird", translation_jp: "鳥" },
    { word: "uno specchio", translation_en: "a mirror", translation_jp: "鏡" },
    { word: "il manzo", translation_en: "the beef", translation_jp: "牛肉" },
    { word: "rispondere", translation_en: "answer", translation_jp: "答え" },
    { word: "tu", translation_en: "you", translation_jp: "あなた" },
    { word: "potere", translation_en: "candies", translation_jp: "キャンディー" },
    { word: "tardi", translation_en: "late", translation_jp: "遅い" },
    { word: "pulito", translation_en: "clean", translation_jp: "クリーン" },
    { word: "un ragazzo giovane", translation_en: "a young boy", translation_jp: "若い男の子" },
    { word: "una mela", translation_en: "an apple", translation_jp: "リンゴ" },
    { word: "il sud", translation_en: "the south", translation_jp: "南" },
    { word: "le labbra", translation_en: "the lips", translation_jp: "唇" },
    { word: "aprire", translation_en: "open", translation_jp: "開ける" },
    { word: "i soldi", translation_en: "the money", translation_jp: "お金" },
    { word: "il pollo", translation_en: "the chicken", translation_jp: "鶏" },
    { word: "un cammino", translation_en: "a path", translation_jp: "道" },
    { word: "il pavimento", translation_en: "the floor", translation_jp: "床" },
    { word: "un ospedale", translation_en: "a hospital", translation_jp: "病院" },
    { word: "una città", translation_en: "a city", translation_jp: "都市" },
    { word: "l'università", translation_en: "the university", translation_jp: "大学" },
    { word: "un gatto", translation_en: "a cat", translation_jp: "猫" },
    { word: "lo zucchero", translation_en: "sugar", translation_jp: "砂糖" },
    { word: "la luna", translation_en: "the moon", translation_jp: "月" },
    { word: "sera", translation_en: "evening", translation_jp: "夕方" },
    { word: "il governo", translation_en: "the government", translation_jp: "政府" },
    { word: "il pesce", translation_en: "the fish", translation_jp: "魚" },
    { word: "un armadio", translation_en: "a wardrobe", translation_jp: "ワードローブ" },
    { word: "bianco", translation_en: "white", translation_jp: "白" },
    { word: "disegnare", translation_en: "draw", translation_jp: "描く" },
    { word: "mangiare", translation_en: "eat", translation_jp: "食べる" },
    { word: "dormire", translation_en: "sleep", translation_jp: "寝る" },
    { word: "una gamba", translation_en: "one leg", translation_jp: "片足" },
    { word: "un ingegnere", translation_en: "an engineer", translation_jp: "エンジニア" },
    { word: "un anno", translation_en: "a year", translation_jp: "一年" },
    { word: "una macchina", translation_en: "a car", translation_jp: "車" },
    { word: "un secondo", translation_en: "a second", translation_jp: "二番目" },
    { word: "un compleanno", translation_en: "a birthday", translation_jp: "誕生日" },
    { word: "bene", translation_en: "Well", translation_jp: "良い" },
    { word: "vuoto", translation_en: "empty", translation_jp: "空の" },
    { word: "il presidente", translation_en: "the president", translation_jp: "大統領" },
    { word: "il re", translation_en: "the king", translation_jp: "王" },
    { word: "il cinema", translation_en: "the cinema", translation_jp: "映画館" },
    { word: "carino", translation_en: "cute", translation_jp: "かわいい" },
    { word: "affaticato", translation_en: "tired", translation_jp: "疲れた" },
    { word: "domandare", translation_en: "ask", translation_jp: "聞く" },
    { word: "una tovaglia", translation_en: "a tablecloth", translation_jp: "テーブルクロス" },
    { word: "palazzo", translation_en: "building", translation_jp: "建物" },
    { word: "un portacenere", translation_en: "an ashtray", translation_jp: "灰皿" },
    { word: "un aeroplano", translation_en: "an airplane", translation_jp: "飛行機" },
    { word: "scusa", translation_en: "Excuse me", translation_jp: "すみません" },
    { word: "mattino", translation_en: "morning", translation_jp: "朝" },
    { word: "una camera", translation_en: "a room", translation_jp: "部屋" },
    { word: "una donna", translation_en: "a woman", translation_jp: "女性" },
    { word: "venerdì", translation_en: "Friday", translation_jp: "金曜日" },
    { word: "la musica", translation_en: "the music", translation_jp: "音楽" },
    { word: "il paradiso", translation_en: "heaven", translation_jp: "天国" },
    { word: "un'aula", translation_en: "a classroom", translation_jp: "教室" },
    { word: "essere", translation_en: "to be", translation_jp: "なる" },
    { word: "domenica", translation_en: "Sunday", translation_jp: "日曜日" },
    { word: "lento", translation_en: "slow", translation_jp: "遅い" },
    { word: "velocemente", translation_en: "quickly", translation_jp: "素早く" },
    { word: "esse", translation_en: "they", translation_jp: "彼らは" },
    { word: "avere", translation_en: "have", translation_jp: "持っている" },
    { word: "la polizia", translation_en: "the police", translation_jp: "警察" },
    { word: "un'arancia", translation_en: "an orange", translation_jp: "オレンジ" },
    { word: "ripetere", translation_en: "repeat", translation_jp: "繰り返す" },
    { word: "la religione", translation_en: "religion", translation_jp: "宗教" },
    { word: "la madre", translation_en: "the mother", translation_jp: "母親" },
    { word: "grigio", translation_en: "grey", translation_jp: "グレー" },
    { word: "libero", translation_en: "free", translation_jp: "無料" },
    { word: "i calzini", translation_en: "the socks", translation_jp: "靴下" },
    { word: "un cavallo", translation_en: "a horse", translation_jp: "馬" },
    { word: "chiudere", translation_en: "close", translation_jp: "近い" },
    { word: "finire", translation_en: "finish", translation_jp: "仕上げる" },
    { word: "imparare", translation_en: "learn", translation_jp: "学ぶ" },
    { word: "un capello", translation_en: "a hair", translation_jp: "髪の毛" },
    { word: "prego", translation_en: "Please", translation_jp: "お願いします" },
    { word: "studiare", translation_en: "study", translation_jp: "勉強" },
    { word: "il lavoro", translation_en: "the work", translation_jp: "作品" },
    { word: "una nuvola", translation_en: "a cloud", translation_jp: "雲" },
    { word: "vivo nel campus universitario", translation_en: "I live on the university campus", translation_jp: "私は大学のキャンパスに住んでいます" },
    { word: "il mercato", translation_en: "the market", translation_jp: "市場" },
    { word: "essi", translation_en: "they", translation_jp: "彼らは" },
    { word: "un commerciante", translation_en: "a merchant", translation_jp: "商人" },
    { word: "gli abiti", translation_en: "the clothes", translation_jp: "服" },
    { word: "la moglie", translation_en: "the wife", translation_jp: "妻" },
    { word: "cantare", translation_en: "sing", translation_jp: "歌う" },
    { word: "mandare", translation_en: "send", translation_jp: "送信" },
    { word: "il vento", translation_en: "the wind", translation_jp: "風" },
    { word: "un giornalista", translation_en: "a journalist", translation_jp: "ジャーナリスト" },
    { word: "un paese", translation_en: "a country", translation_jp: "国" },
    { word: "la nafta", translation_en: "naphtha", translation_jp: "ナフサ" },
    { word: "conoscere", translation_en: "know", translation_jp: "知る" },
    { word: "facile", translation_en: "easy", translation_jp: "簡単" },
    { word: "straniero", translation_en: "foreigner", translation_jp: "外国人" },
    { word: "una bevanda", translation_en: "a drink", translation_jp: "飲み物" },
    { word: "uno studente", translation_en: "a student", translation_jp: "学生" },
    { word: "un fratello", translation_en: "a brother", translation_jp: "兄弟" },
    { word: "il suolo", translation_en: "the soil", translation_jp: "土壌" },
    { word: "nome", translation_en: "name", translation_jp: "名前" },
    { word: "ufficio cambi", translation_en: "exchange office", translation_jp: "両替所" },
    { word: "pomeriggio", translation_en: "afternoon", translation_jp: "午後" },
    { word: "una persona", translation_en: "a person", translation_jp: "人" },
    { word: "fare", translation_en: "Do", translation_jp: "する" },
    { word: "un autobus", translation_en: "a bus", translation_jp: "バス" },
    { word: "un vicino", translation_en: "a neighbor", translation_jp: "隣人" },
    { word: "salute !", translation_en: "Health !", translation_jp: "健康 ！" },
    { word: "vietato", translation_en: "prohibited", translation_jp: "禁止" },
    { word: "il giardino", translation_en: "the garden", translation_jp: "庭" },
    { word: "un paese", translation_en: "a country", translation_jp: "国" },
    { word: "i vestiti", translation_en: "the clothes", translation_jp: "服" },
    { word: "una borsa", translation_en: "a bag", translation_jp: "バッグ" },
    { word: "il commercio", translation_en: "trade", translation_jp: "貿易" },
    { word: "una pera", translation_en: "a pear", translation_jp: "梨" },
    { word: "nuovo", translation_en: "new", translation_jp: "新しい" },
    { word: "una fermata", translation_en: "one stop", translation_jp: "ワンストップ" },
    { word: "un biglietto", translation_en: "a ticket", translation_jp: "チケット" },
    { word: "blu", translation_en: "blue", translation_jp: "青" },
    { word: "trovarsi", translation_en: "be", translation_jp: "なれ" },
    { word: "un prete", translation_en: "a priest", translation_jp: "司祭" },
    { word: "una zanzara", translation_en: "a mosquito", translation_jp: "蚊" },
    { word: "il marito", translation_en: "the husband", translation_jp: "夫" },
    { word: "più", translation_en: "more", translation_jp: "もっと" },
    { word: "una pentola", translation_en: "a pot", translation_jp: "鍋" },
    { word: "la politica", translation_en: "politics", translation_jp: "政治" },
    { word: "un fazzoletto", translation_en: "a handkerchief", translation_jp: "ハンカチ" },
    { word: "un animale", translation_en: "an animal", translation_jp: "動物" },
    { word: "stanco", translation_en: "tired", translation_jp: "疲れた" },
    { word: "sporco", translation_en: "dirty", translation_jp: "汚い" },
    { word: "il riso", translation_en: "rice", translation_jp: "米" },
    { word: "una padella", translation_en: "a pan", translation_jp: "鍋" },
    { word: "il grano", translation_en: "the wheat", translation_jp: "小麦" },
    { word: "un cavolo", translation_en: "a cabbage", translation_jp: "キャベツ" },
    { word: "su", translation_en: "on", translation_jp: "の上" },
    { word: "la zuppa", translation_en: "the soup", translation_jp: "スープ" },
    { word: "i genitori", translation_en: "the parents", translation_jp: "両親" },
    { word: "magari", translation_en: "Perhaps", translation_jp: "多分" },
    { word: "no", translation_en: "No", translation_jp: "いいえ" },
    { word: "mercoledì", translation_en: "Wednesday", translation_jp: "水曜日" },
    { word: "troppo", translation_en: "too", translation_jp: "あまりにも" },
    { word: "un aereo", translation_en: "a plane", translation_jp: "飛行機" },
    { word: "volere", translation_en: "want", translation_jp: "欲しい" },
    { word: "un contratto", translation_en: "a contract", translation_jp: "契約" },
    { word: "un minuto", translation_en: "a minute", translation_jp: "ちょっと" },
    { word: "giovedì", translation_en: "Thursday", translation_jp: "木曜日" },
    { word: "fermarsi", translation_en: "stop", translation_jp: "停止" },
    { word: "un appartamento", translation_en: "an apartment", translation_jp: "アパート" },
    { word: "leggere", translation_en: "light", translation_jp: "ライト" },
    { word: "un braccio", translation_en: "an arm", translation_jp: "腕" },
    { word: "un raffreddore", translation_en: "a cold", translation_jp: "風邪" },
    { word: "un uovo", translation_en: "an egg", translation_jp: "卵" },
    { word: "noi", translation_en: "us", translation_jp: "私たち" },
    { word: "spegnere", translation_en: "turn off", translation_jp: "消す" },
    { word: "l'indirizzo", translation_en: "the address", translation_jp: "住所" },
    { word: "un corso", translation_en: "a course", translation_jp: "コース" },
    { word: "un computer", translation_en: "a computer", translation_jp: "コンピューター" },
    { word: "un mese", translation_en: "a month", translation_jp: "一ヶ月" },
    { word: "una lampada", translation_en: "a lamp", translation_jp: "ランプ" },
    { word: "un fiore", translation_en: "a flower", translation_jp: "花" },
    { word: "il cioccolato", translation_en: "chocolate", translation_jp: "チョコレート" },
    { word: "il soffito", translation_en: "the ceiling", translation_jp: "天井" },
    { word: "perdere", translation_en: "LOSE", translation_jp: "失う" },
    { word: "mezzogiorno", translation_en: "noon", translation_jp: "正午" },
    { word: "si", translation_en: "Yes", translation_jp: "はい" },
    { word: "il popolo", translation_en: "the people", translation_jp: "人々" },
    { word: "marrone", translation_en: "brown", translation_jp: "茶色" },
    { word: "freddo", translation_en: "Freddo", translation_jp: "フレッド" },
    { word: "lungo", translation_en: "long", translation_jp: "長さ" },
    { word: "grazie", translation_en: "Thank you", translation_jp: "ありがとう" },
    { word: "nero", translation_en: "black", translation_jp: "黒" },
    { word: "contare", translation_en: "count", translation_jp: "カウント" },
    { word: "per favore", translation_en: "Please", translation_jp: "お願いします" },
    { word: "alto", translation_en: "high", translation_jp: "高い" },
    { word: "la cena", translation_en: "dinner", translation_jp: "夕食" },
    { word: "una nonna", translation_en: "a grandmother", translation_jp: "おばあちゃん" },
    { word: "un cane", translation_en: "a dog", translation_jp: "犬" },
    { word: "il naso", translation_en: "the nose", translation_jp: "鼻" },
    { word: "la bocca", translation_en: "the mouth", translation_jp: "口" },
    { word: "domani", translation_en: "Tomorrow", translation_jp: "明日" },
    { word: "un'impresa", translation_en: "a business", translation_jp: "ビジネス" },
    { word: "una vacca", translation_en: "a cow", translation_jp: "牛" },
    { word: "una gonna", translation_en: "a skirt", translation_jp: "スカート" },
    { word: "un agricoltore", translation_en: "a farmer", translation_jp: "農民" },
    { word: "voi", translation_en: "you", translation_jp: "あなた" },
    { word: "di niente", translation_en: "not at all", translation_jp: "全くない" },
    { word: "a destra", translation_en: "To the right", translation_jp: "右の方へ" },
    { word: "lentamente", translation_en: "slowly", translation_jp: "ゆっくり" },
    { word: "mostrare", translation_en: "show", translation_jp: "見せる" },
    { word: "la benzina", translation_en: "petrol", translation_jp: "ガソリン" },
    { word: "il fidanzato", translation_en: "the boyfriend", translation_jp: "ボーイフレンド" },
    { word: "felice", translation_en: "happy", translation_jp: "ハッピー" },
    { word: "l'acqua", translation_en: "the water", translation_jp: "水" },
    { word: "il fuoco", translation_en: "the fire", translation_jp: "火" },
    { word: "veloce", translation_en: "fast", translation_jp: "速い" },
    { word: "voglio ...", translation_en: "I want ...", translation_jp: "欲しい ..." },
    { word: "bello", translation_en: "Handsome", translation_jp: "ハンサム" },
    { word: "un nonno", translation_en: "a grandfather", translation_jp: "祖父" },
    { word: "un lenzuolo", translation_en: "a sheet", translation_jp: "シート" },
    { word: "un pantalone", translation_en: "a pair of trousers", translation_jp: "ズボン" },
    { word: "un traduttore", translation_en: "a translator", translation_jp: "翻訳者" },
    { word: "piacere !", translation_en: "Pleasure !", translation_jp: "喜び ！" },
    { word: "sto bene", translation_en: "I am fine", translation_jp: "私は元気です" },
    { word: "una tavola", translation_en: "a table", translation_jp: "テーブル" },
    { word: "costruire", translation_en: "build", translation_jp: "建てる" },
    { word: "una sorella", translation_en: "a sister", translation_jp: "妹" },
    { word: "meno", translation_en: "less", translation_jp: "少ない" },
    { word: "cognome", translation_en: "surname", translation_jp: "姓" },
    { word: "altro", translation_en: "other", translation_jp: "他の" },
    { word: "venire", translation_en: "come", translation_jp: "来る" },
    { word: "caro", translation_en: "Dear", translation_jp: "親愛なる" },
    { word: "la pace", translation_en: "peace", translation_jp: "平和" },
    { word: "un bicchiere", translation_en: "a glass", translation_jp: "グラス" },
    { word: "l'ovest", translation_en: "the west", translation_jp: "西" },
    { word: "arrivederci", translation_en: "Until we meet again", translation_jp: "また会う日まで" },
    { word: "la luce", translation_en: "the light", translation_jp: "光" },
    { word: "il rumore", translation_en: "the noise", translation_jp: "騒音" },
    { word: "un fiammifero", translation_en: "a match", translation_jp: "試合" },
    { word: "Internet", translation_en: "Internet", translation_jp: "インターネット" },
    { word: "la fronte", translation_en: "the forehead", translation_jp: "額" },
    { word: "lontano", translation_en: "distant", translation_jp: "遠い" },
    { word: "un topo", translation_en: "a mouse", translation_jp: "マウス" },
    { word: "portare", translation_en: "bring", translation_jp: "持ってくる" },
    { word: "una strada", translation_en: "a road", translation_jp: "道路" },
    { word: "un dizionario", translation_en: "a dictionary", translation_jp: "辞書" },
    { word: "la pelle", translation_en: "the skin", translation_jp: "皮膚" },
    { word: "là", translation_en: "there", translation_jp: "そこには" },
    { word: "la marmellata", translation_en: "the jam", translation_jp: "ジャム" },
    { word: "la natura", translation_en: "nature", translation_jp: "自然" },
    { word: "il conto", translation_en: "the account", translation_jp: "アカウント" },
    { word: "un cuscino", translation_en: "a pillow", translation_jp: "枕" },
    { word: "andare", translation_en: "go", translation_jp: "行く" },
    { word: "la danza", translation_en: "the dance", translation_jp: "ダンス" },
    { word: "l'arrivo", translation_en: "the arrival", translation_jp: "到着" },
    { word: "la montagna", translation_en: "the mountain", translation_jp: "山" },
    { word: "una classe", translation_en: "a class", translation_jp: "クラス" },
    { word: "una tazza", translation_en: "a cup", translation_jp: "一杯" },
    { word: "il prezzo", translation_en: "the price", translation_jp: "価格" },
    { word: "buonasera", translation_en: "Good evening", translation_jp: "こんばんは" },
    { word: "é necessario ...", translation_en: "it is necessary...", translation_jp: "これは必要である..." },
    { word: "un muro", translation_en: "a wall", translation_jp: "壁" },
    { word: "una stella", translation_en: "a star", translation_jp: "星" },
    { word: "donare", translation_en: "donate", translation_jp: "寄付する" },
    { word: "un tovagliolo", translation_en: "a napkin", translation_jp: "ナプキン" },
    { word: "rifiutare", translation_en: "reject", translation_jp: "拒否する" },
    { word: "pericoloso", translation_en: "dangerous", translation_jp: "危険な" },
    { word: "un piano", translation_en: "a plan", translation_jp: "計画" },
    { word: "non caro", translation_en: "not expensive", translation_jp: "高価ではない" },
    { word: "una nave", translation_en: "a ship", translation_jp: "船" },
    { word: "il sangue", translation_en: "the blood", translation_jp: "血" },
    { word: "un cappotto", translation_en: "a coat", translation_jp: "コート" },
    { word: "pronto", translation_en: "ready", translation_jp: "準備ができて" },
    { word: "una festa", translation_en: "a party", translation_jp: "パーティー" },
    { word: "un accendino", translation_en: "a lighter", translation_jp: "ライター" },
    { word: "il teatro", translation_en: "the theatre", translation_jp: "劇場" },
    { word: "il progesso", translation_en: "progress", translation_jp: "進捗" },
    { word: "un piatto", translation_en: "a dish", translation_jp: "皿" },
    { word: "un piede", translation_en: "one foot", translation_jp: "片足" },
    { word: "accettare", translation_en: "accept", translation_jp: "受け入れる" },
    { word: "una sigaretta", translation_en: "a cigarette", translation_jp: "タバコ" },
    { word: "un frutto", translation_en: "a fruit", translation_jp: "果物" },
    { word: "vecchio", translation_en: "old", translation_jp: "古い" },
    { word: "un figlio", translation_en: "a son", translation_jp: "息子" },
    { word: "un pullman", translation_en: "a bus", translation_jp: "バス" },
    { word: "giù", translation_en: "below", translation_jp: "下に" },
    { word: "forte", translation_en: "strong", translation_jp: "強い" },
    { word: "una mosca", translation_en: "a fly", translation_jp: "ハエ" },
    { word: "una riviera", translation_en: "a riviera", translation_jp: "リビエラ" },
    { word: "un tegame", translation_en: "a pan", translation_jp: "鍋" },
    { word: "un'ora", translation_en: "an hour", translation_jp: "1時間" },
    { word: "un sindacato", translation_en: "a union", translation_jp: "組合" },
    { word: "le orecchie", translation_en: "the ears", translation_jp: "耳" },
    { word: "il bagno", translation_en: "the bathroom", translation_jp: "バスルーム" },
    { word: "capire", translation_en: "understand", translation_jp: "理解する" },
    { word: "una figlia", translation_en: "a daughter", translation_jp: "娘" },
    { word: "un ratto", translation_en: "a rat", translation_jp: "ネズミ" },
    { word: "il sapone", translation_en: "the soap", translation_jp: "石鹸" },
    { word: "la lingua", translation_en: "the language", translation_jp: "言語" },
    { word: "poco", translation_en: "little", translation_jp: "少し" },
    { word: "un'automobile", translation_en: "a car", translation_jp: "車" },
    { word: "un militare", translation_en: "a soldier", translation_jp: "兵士" },
    { word: "ora", translation_en: "Now", translation_jp: "今" },
    { word: "un poliziotto", translation_en: "a policeman", translation_jp: "警察官" },
    { word: "un anfiteatro", translation_en: "an amphitheater", translation_jp: "円形劇場" },
    { word: "egli", translation_en: "they", translation_jp: "彼らは" },
    { word: "attento !", translation_en: "careful !", translation_jp: "注意深い ！" },
    { word: "il mare", translation_en: "the sea", translation_jp: "海" },
    { word: "rosa", translation_en: "rose", translation_jp: "薔薇" },
    { word: "adesso", translation_en: "Now", translation_jp: "今" },
    { word: "sapere", translation_en: "know", translation_jp: "知る" },
    { word: "pulire", translation_en: "clean", translation_jp: "クリーン" },
    { word: "tanto", translation_en: "a lot", translation_jp: "たくさん" },
    { word: "l'aceto", translation_en: "the vinegar", translation_jp: "酢" },
    { word: "le scarpe", translation_en: "the shoes", translation_jp: "靴" },
    { word: "l'economia", translation_en: "the economy", translation_jp: "経済" },
    { word: "ella", translation_en: "she", translation_jp: "彼女" },
    { word: "la cucina", translation_en: "the kitchen", translation_jp: "キッチン" },
    { word: "un coltello", translation_en: "a knife", translation_jp: "ナイフ" },
    { word: "gli occhi", translation_en: "the eyes", translation_jp: "目" },
    { word: "la società", translation_en: "the company", translation_jp: "会社" },
    { word: "un coniglio", translation_en: "a rabbit", translation_jp: "ウサギ" },
    { word: "non so", translation_en: "I don't know", translation_jp: "わからない" },
    { word: "rapido", translation_en: "quick", translation_jp: "素早い" },
    { word: "una pecora", translation_en: "a sheep", translation_jp: "羊" },
    { word: "comprare", translation_en: "buy", translation_jp: "買う" },
    { word: "svegliarsi", translation_en: "wake up", translation_jp: "起きろ" },
    { word: "una chiesa", translation_en: "a church", translation_jp: "教会" },
    { word: "uno Stato", translation_en: "a state", translation_jp: "状態" },
    { word: "chiamare", translation_en: "call", translation_jp: "電話" },
    { word: "il maiale", translation_en: "the pig", translation_jp: "豚" },
    { word: "l'esercito", translation_en: "the army", translation_jp: "軍隊" },
    { word: "rosso", translation_en: "red", translation_jp: "赤" },
    { word: "mettere", translation_en: "put", translation_jp: "置く" },
    { word: "un'ape", translation_en: "a bee", translation_jp: "蜂" },
    { word: "la vita", translation_en: "life", translation_jp: "人生" },
    { word: "la spiaggia", translation_en: "the beach", translation_jp: "ビーチ" },
    { word: "nessuno", translation_en: "Nobody", translation_jp: "誰でもない" },
    { word: "uno scrittore", translation_en: "a writer", translation_jp: "作家" },
    { word: "un taxi", translation_en: "a taxi", translation_jp: "タクシー" },
    { word: "un ministro", translation_en: "a minister", translation_jp: "大臣" },
    { word: "vicino", translation_en: "Neighbor", translation_jp: "近所の人" },
    { word: "una mucca", translation_en: "a cow", translation_jp: "牛" },
    { word: "l'entrata", translation_en: "the entrance", translation_jp: "入り口" },
    { word: "un fiume", translation_en: "a river", translation_jp: "川" },
    { word: "non posso", translation_en: "I cannot", translation_jp: "私はできません" },
    { word: "ciao !", translation_en: "HI !", translation_jp: "こんにちは ！" },
    { word: "tradurre", translation_en: "translate", translation_jp: "翻訳する" },
    { word: "a buon mercato", translation_en: "cheap", translation_jp: "安い" },
    { word: "il succo di frutta", translation_en: "fruit juice", translation_jp: "果汁" },
    { word: "la Storia", translation_en: "the History", translation_jp: "歴史" },
    { word: "lasciare", translation_en: "leave", translation_jp: "離れる" },
    { word: "la carta", translation_en: "the card", translation_jp: "カード" },
    { word: "gli occhiali", translation_en: "the glasses", translation_jp: "メガネ" },
    { word: "vendere", translation_en: "sell", translation_jp: "売る" },
    { word: "la cultura", translation_en: "the culture", translation_jp: "文化" },
    { word: "l'uva", translation_en: "the grapes", translation_jp: "ブドウ" },
    { word: "la terra", translation_en: "the earth", translation_jp: "地球" },
    { word: "una bottiglia", translation_en: "a bottle", translation_jp: "ボトル" },
    { word: "parlo italiano", translation_en: "I speak Italian", translation_jp: "私はイタリア語を話します" },
    { word: "largo", translation_en: "wide", translation_jp: "広い" },
    { word: "una legge", translation_en: "a law", translation_jp: "法律" },
    { word: "aspettare", translation_en: "wait", translation_jp: "待って" },
    { word: "tutti", translation_en: "everyone", translation_jp: "みんな" },
    { word: "lì", translation_en: "there", translation_jp: "そこには" },
    { word: "l'est", translation_en: "the east", translation_jp: "東" },
    { word: "assente", translation_en: "absent", translation_jp: "不在" },
    { word: "una settimana", translation_en: "a week", translation_jp: "一週間" },
    { word: "la campagna", translation_en: "the countryside", translation_jp: "田舎" },
    { word: "sentire", translation_en: "feel", translation_jp: "感じる" },
    { word: "vengo dall'Italia", translation_en: "I'm from Italy", translation_jp: "イタリア出身です" },
    { word: "abbastanza", translation_en: "Enough", translation_jp: "十分" },
    { word: "una gallina", translation_en: "a hen", translation_jp: "鶏" },
    { word: "il mais", translation_en: "the corn", translation_jp: "トウモロコシ" },
    { word: "una sedia", translation_en: "a chair", translation_jp: "椅子" },
    { word: "guidare", translation_en: "guide", translation_jp: "ガイド" },
    { word: "un bebè", translation_en: "a baby", translation_jp: "赤ちゃん" },
    { word: "un uomo", translation_en: "a man", translation_jp: "男" },
    { word: "una bibita", translation_en: "a drink", translation_jp: "飲み物" },
    { word: "qua", translation_en: "here", translation_jp: "ここ" },
    { word: "un vestito", translation_en: "a dress", translation_jp: "ドレス" },
    { word: "amare", translation_en: "love", translation_jp: "愛" },
    { word: "l'inquinamento", translation_en: "pollution", translation_jp: "汚染" },
    { word: "la pittura", translation_en: "painting", translation_jp: "絵画" },
    { word: "un giorno", translation_en: "one day", translation_jp: "ある日" },
    { word: "l'amore", translation_en: "love", translation_jp: "愛" },
    { word: "un letto", translation_en: "a bed", translation_jp: "ベッド" },
    { word: "una carta", translation_en: "a card", translation_jp: "カード" },
    { word: "a sinistra", translation_en: "left", translation_jp: "左" },
    { word: "una ragazzina", translation_en: "a little girl", translation_jp: "小さな女の子" },
    { word: "il burro", translation_en: "the butter", translation_jp: "バター" },
    { word: "l'affitto", translation_en: "the rent", translation_jp: "家賃" },
    { word: "un montone", translation_en: "a ram", translation_jp: "雄羊" },
    { word: "piazzare", translation_en: "place", translation_jp: "場所" },
    { word: "l'agricoltura", translation_en: "agriculture", translation_jp: "農業" },
    { word: "una tenda", translation_en: "a tent", translation_jp: "テント" },
    { word: "falso", translation_en: "false", translation_jp: "間違い" },
    { word: "una via", translation_en: "one way", translation_jp: "一方通行" },
    { word: "un libro", translation_en: "a book", translation_jp: "本" },
    { word: "qui", translation_en: "here", translation_jp: "ここ" },
    { word: "cominciare", translation_en: "start", translation_jp: "始める" },
    { word: "buongiorno", translation_en: "Good morning", translation_jp: "おはよう" },
    { word: "la fidanzata", translation_en: "the girlfriend", translation_jp: "ガールフレンド" },
    { word: "un biscotto", translation_en: "a biscuit", translation_jp: "ビスケット" },
    { word: "un bambino", translation_en: "a child", translation_jp: "子供" },
    { word: "sempre", translation_en: "Always", translation_jp: "いつも" },
    { word: "un esame", translation_en: "an exam", translation_jp: "試験" },
    { word: "l'ambiente", translation_en: "the environment", translation_jp: "環境" },
    { word: "entrare", translation_en: "enter", translation_jp: "入力" },
    { word: "un battello", translation_en: "a boat", translation_jp: "ボート" },
    { word: "un medico", translation_en: "a doctor", translation_jp: "医者" },
    { word: "un villaggio", translation_en: "a village", translation_jp: "村" },
    { word: "la lotta", translation_en: "the fight", translation_jp: "戦い" },
    { word: "la mostarda", translation_en: "the mustard", translation_jp: "マスタード" },
    { word: "studio a Parigi", translation_en: "I study in Paris", translation_jp: "私はパリで勉強しています" },
    { word: "sabato", translation_en: "Saturday", translation_jp: "土曜日" },
    { word: "un albero", translation_en: "a tree", translation_jp: "木" },
    { word: "la guerra", translation_en: "the war", translation_jp: "戦争" },
    { word: "verde", translation_en: "green", translation_jp: "緑" },
    { word: "vivere", translation_en: "live", translation_jp: "ライブ" },
    { word: "una chiave", translation_en: "a key", translation_jp: "鍵" },
    { word: "la stampa", translation_en: "the press", translation_jp: "報道陣" },
    { word: "il pane", translation_en: "the bread", translation_jp: "パン" },
    { word: "il cibo", translation_en: "the food", translation_jp: "食べ物" },
    { word: "mattina", translation_en: "morning", translation_jp: "朝" },
    { word: "un professore", translation_en: "a professor", translation_jp: "教授" },
    { word: "la rivoluzione", translation_en: "the revolution", translation_jp: "革命" },
    { word: "grande", translation_en: "big", translation_jp: "大きい" },
    { word: "la gente", translation_en: "the people", translation_jp: "人々" },
    { word: "la produzione", translation_en: "production", translation_jp: "生産" },
    { word: "le tasse", translation_en: "taxes", translation_jp: "税金" },
    { word: "occupato", translation_en: "busy", translation_jp: "忙しい" },
    { word: "forse", translation_en: "Perhaps", translation_jp: "多分" },
    { word: "una professione", translation_en: "a profession", translation_jp: "職業" },
    { word: "bere", translation_en: "drink", translation_jp: "飲む" },
    { word: "i capelli", translation_en: "the hair", translation_jp: "髪" },
    { word: "un pomodoro", translation_en: "a tomato", translation_jp: "トマト" },
    { word: "vero", translation_en: "True", translation_jp: "真実" },
    { word: "l'aglio", translation_en: "the garlic", translation_jp: "ニンニク" },
    { word: "Dio", translation_en: "God", translation_jp: "神" },
    { word: "una forchetta", translation_en: "a fork", translation_jp: "フォーク" },
    { word: "un amico", translation_en: "a friend", translation_jp: "友人" },
    { word: "una banca", translation_en: "a bank", translation_jp: "銀行" },
    { word: "giallo", translation_en: "yellow", translation_jp: "黄色" },
    { word: "un pasto", translation_en: "a meal", translation_jp: "食事" },
    { word: "la partenza", translation_en: "the departure", translation_jp: "出発" },
    { word: "l'aria", translation_en: "the air", translation_jp: "空気" },
    { word: "una bicicletta", translation_en: "a bicycle", translation_jp: "自転車" },
    { word: "vedere", translation_en: "see", translation_jp: "見る" },
    { word: "una televisione", translation_en: "a television", translation_jp: "テレビ" },
    { word: "un malato", translation_en: "a sick person", translation_jp: "病気の人" },
    { word: "l'inferno", translation_en: "hell", translation_jp: "地獄" },
    { word: "inviare", translation_en: "send", translation_jp: "送信" },
    { word: "davanti", translation_en: "in front of", translation_jp: "の前に" },
    { word: "insieme", translation_en: "Together", translation_jp: "一緒に" },
    { word: "il bagno", translation_en: "the bathroom", translation_jp: "バスルーム" },
    { word: "la morte", translation_en: "death", translation_jp: "死" },
    { word: "lunedì", translation_en: "Monday", translation_jp: "月曜日" },
    { word: "abitare", translation_en: "inhabit", translation_jp: "生息する" },
    { word: "costare", translation_en: "cost", translation_jp: "料金" },
    { word: "accendere", translation_en: "turn on", translation_jp: "オンにする" },
    { word: "brutto", translation_en: "bad", translation_jp: "悪い" },
    { word: "incontrare", translation_en: "encounter", translation_jp: "出会い" },
    { word: "un diploma", translation_en: "a diploma", translation_jp: "卒業証書" },
    { word: "la testa", translation_en: "the head", translation_jp: "頭" },
    { word: "il tabacco", translation_en: "tobacco", translation_jp: "タバコ" },
    { word: "cattivo", translation_en: "bad", translation_jp: "悪い" },
    { word: "una barca", translation_en: "a boat", translation_jp: "ボート" },
    { word: "una stazione", translation_en: "a station", translation_jp: "駅" },
    { word: "un cucchiaio", translation_en: "a spoon", translation_jp: "スプーン" },
    { word: "un limone", translation_en: "a lemon", translation_jp: "レモン" },
    { word: "una motocicletta", translation_en: "a motorcycle", translation_jp: "バイク" },
    { word: "una nazione", translation_en: "a nation", translation_jp: "国家" },
    { word: "il nord", translation_en: "the north", translation_jp: "北" },
    { word: "un'azienda", translation_en: "a company", translation_jp: "会社" },
    { word: "l'alcol", translation_en: "alcohol", translation_jp: "アルコール" },
    { word: "una fonte", translation_en: "a source", translation_jp: "情報源" },
    { word: "la salute", translation_en: "health", translation_jp: "健康" },
    { word: "il sole", translation_en: "the sun", translation_jp: "太陽" },
    { word: "un ponte", translation_en: "a bridge", translation_jp: "橋" },
    { word: "ho vent'anni", translation_en: "I'm twenty years old", translation_jp: "私は二十歳です" },
    { word: "aspetta mi !", translation_en: "wait for me!", translation_jp: "私を待っててください！" },
    { word: "il padre", translation_en: "the father", translation_jp: "父親" },
    { word: "stare", translation_en: "stay", translation_jp: "滞在する" },
    { word: "presto", translation_en: "Soon", translation_jp: "すぐ" },
    { word: "l'olio", translation_en: "the oil", translation_jp: "油" },
    { word: "mai", translation_en: "never", translation_jp: "一度もない" },
    { word: "un treno", translation_en: "a train", translation_jp: "電車" },
    { word: "le forbici", translation_en: "the scissors", translation_jp: "はさみ" },
    { word: "il corpo", translation_en: "the body", translation_jp: "体" },
    { word: "il sale", translation_en: "the salt", translation_jp: "塩" },
    { word: "una torta", translation_en: "a cake", translation_jp: "ケーキ" },
    { word: "signora", translation_en: "Lady", translation_jp: "レディ" },
    { word: "un templio", translation_en: "a temple", translation_jp: "寺院" },
    { word: "la patata", translation_en: "the potato", translation_jp: "ジャガイモ" },
    { word: "signore", translation_en: "Gentleman", translation_jp: "紳士" },
    { word: "dare", translation_en: "give", translation_jp: "与える" },
    { word: "una malattia", translation_en: "a disease", translation_jp: "病気" },
    { word: "buonanotte", translation_en: "Good night", translation_jp: "おやすみ" },
    { word: "piccolo", translation_en: "small", translation_jp: "小さい" },
    { word: "una mano", translation_en: "a hand", translation_jp: "手" },
    { word: "la famiglia", translation_en: "the family", translation_jp: "家族" },
    { word: "trovare", translation_en: "find", translation_jp: "探す" },
];

export default records;