export const records: { word: string, translation_en: string, translation_jp: string }[] = [
    { word: "и", translation_en: "and", translation_jp: "そして" },
    { word: "в", translation_en: "in, at, on, within", translation_jp: "で、上で、中で" },
    { word: "не", translation_en: "not", translation_jp: "ない" },
    { word: "он", translation_en: "he", translation_jp: "彼" },
    { word: "на", translation_en: "on (place)", translation_jp: "の上" },
    { word: "я", translation_en: "I, me, myself", translation_jp: "私" },
    { word: "что", translation_en: "what", translation_jp: "何" },
    { word: "тот", translation_en: "that, that one, those, the other", translation_jp: "それ" },
    { word: "быть", translation_en: "to be", translation_jp: "なれ" },
    { word: "с", translation_en: "with", translation_jp: "と" },
    { word: "а", translation_en: "and (as contrast)", translation_jp: "あ" },
    { word: "весь", translation_en: "village", translation_jp: "全て" },
    { word: "как", translation_en: "how", translation_jp: "どうやって" },
    { word: "по", translation_en: "along, down, through, across", translation_jp: "による" },
    { word: "но", translation_en: "but", translation_jp: "しかし" },
    { word: "к", translation_en: "towards", translation_jp: "に" },
    { word: "у", translation_en: "(possession)", translation_jp: "で" },
    { word: "из", translation_en: "from (the inside of)", translation_jp: "から" },
    { word: "за", translation_en: "behind", translation_jp: "のために" },
    { word: "так", translation_en: "so, thus, like this, this way, then", translation_jp: "それで" },
    { word: "же", translation_en: "same, again, already", translation_jp: "または" },
    { word: "сказать", translation_en: "to say, to tell, to speak, to talk", translation_jp: "言う" },
    { word: "этот", translation_en: "this", translation_jp: "これ" },
    { word: "который", translation_en: "which, that, what", translation_jp: "どれの" },
    { word: "о", translation_en: "about", translation_jp: "について" },
    { word: "человек", translation_en: "person, man, people", translation_jp: "人間" },
    { word: "один", translation_en: "one, 1", translation_jp: "1つ" },
    { word: "ещё", translation_en: "still, even, more, else", translation_jp: "もっと" },
    { word: "бы", translation_en: "would (be able to)", translation_jp: "するだろう" },
    { word: "такой", translation_en: "such, so, that sort of", translation_jp: "そのような" },
    { word: "только", translation_en: "only", translation_jp: "のみ" },
    { word: "себя", translation_en: "oneself, ourselves, yourselves, himself, herself, itself, yourself, myself, themselves", translation_jp: "自分自身" },
    { word: "какой", translation_en: "which, what, what kind of", translation_jp: "どれの" },
    { word: "для", translation_en: "for (the benefit of)", translation_jp: "のために" },
    { word: "уже", translation_en: "already, by this time, by now, ready, no longer", translation_jp: "すでに" },
    { word: "когда", translation_en: "when, while, as", translation_jp: "いつ" },
    { word: "кто", translation_en: "who", translation_jp: "誰が" },
    { word: "вот", translation_en: "here, there, there is", translation_jp: "ここ" },
    { word: "да", translation_en: "yes", translation_jp: "はい" },
    { word: "год", translation_en: "year", translation_jp: "年" },
    { word: "знать", translation_en: "know, be aware, be acquainted, it seems", translation_jp: "知る" },
    { word: "если", translation_en: "if", translation_jp: "もし" },
    { word: "до", translation_en: "to (direction)", translation_jp: "に" },
    { word: "говорить", translation_en: "speak, talk", translation_jp: "話す" },
    { word: "или", translation_en: "or", translation_jp: "または" },
    { word: "мой", translation_en: "my, mine, my people", translation_jp: "私の" },
    { word: "время", translation_en: "time, times, tense, weather", translation_jp: "時間" },
    { word: "самый", translation_en: "the most", translation_jp: "ほとんど" },
    { word: "нет", translation_en: "no", translation_jp: "いいえ" },
    { word: "ни", translation_en: "neither", translation_jp: "どちらでもない" },
    { word: "стать", translation_en: "article", translation_jp: "なる" },
    { word: "большой", translation_en: "big, large, great, important, grown-up", translation_jp: "大きい" },
    { word: "наш", translation_en: "our, ours, our lot", translation_jp: "私たちの" },
    { word: "даже", translation_en: "even", translation_jp: "平" },
    { word: "другой", translation_en: "other, another, another thing, something else, others, the rest", translation_jp: "別の" },
    { word: "свой", translation_en: "one's own (reflexive)", translation_jp: "私の" },
    { word: "дело", translation_en: "business, work", translation_jp: "場合" },
    { word: "под", translation_en: "under", translation_jp: "下" },
    { word: "где", translation_en: "where", translation_jp: "どこ" },
    { word: "чтобы", translation_en: "so that", translation_jp: "に" },
    { word: "ну", translation_en: "well", translation_jp: "良い" },
    { word: "сам", translation_en: "ourselves, yourself, oneself, yourselves, himself, herself, itself, themselves", translation_jp: "自分自身" },
    { word: "есть", translation_en: "to eat", translation_jp: "がある" },
    { word: "раз", translation_en: "time", translation_jp: "一度" },
    { word: "два", translation_en: "two, 2", translation_jp: "二" },
    { word: "там", translation_en: "there, later, by and by", translation_jp: "そこには" },
    { word: "глаз", translation_en: "eye", translation_jp: "目" },
    { word: "первый", translation_en: "first, front, former, earliest", translation_jp: "初め" },
    { word: "день", translation_en: "day, daytime", translation_jp: "日" },
    { word: "жизнь", translation_en: "life, existence", translation_jp: "人生" },
    { word: "тут", translation_en: "mulberry fruit", translation_jp: "ここ" },
    { word: "потом", translation_en: "afterwards, then, later on, later", translation_jp: "それから" },
    { word: "очень", translation_en: "very, very much, greatly", translation_jp: "とても" },
    { word: "ли", translation_en: "whether, if", translation_jp: "かどうか" },
    { word: "при", translation_en: "at", translation_jp: "で" },
    { word: "надо", translation_en: "need", translation_jp: "必要" },
    { word: "голова", translation_en: "head, mind, brains, chief, master", translation_jp: "頭" },
    { word: "без", translation_en: "without", translation_jp: "それなし" },
    { word: "видеть", translation_en: "see", translation_jp: "見る" },
    { word: "теперь", translation_en: "now, nowadays, today", translation_jp: "今" },
    { word: "идти", translation_en: "to go, to walk", translation_jp: "行く" },
    { word: "друг", translation_en: "friend", translation_jp: "友達" },
    { word: "сейчас", translation_en: "now, just now", translation_jp: "今" },
    { word: "дом", translation_en: "house, home, house-hold", translation_jp: "家" },
    { word: "тоже", translation_en: "also, as well, too", translation_jp: "同じ" },
    { word: "после", translation_en: "after, afterwards, later", translation_jp: "後" },
    { word: "можно", translation_en: "one can (it is possible)", translation_jp: "できる" },
    { word: "слово", translation_en: "word", translation_jp: "言葉" },
    { word: "через", translation_en: "across, over, at", translation_jp: "を通して" },
    { word: "место", translation_en: "place, spot, site, locality", translation_jp: "場所" },
    { word: "думать", translation_en: "think, consider, reflect, ponder, believe, intend", translation_jp: "考える" },
    { word: "здесь", translation_en: "here, with us, in this country, about it, in it, at this point", translation_jp: "ここ" },
    { word: "лицо", translation_en: "face, the right side, person, face to face", translation_jp: "顔" },
    { word: "тогда", translation_en: "then, while, at that time, at that moment", translation_jp: "それから" },
    { word: "ведь", translation_en: "in fact", translation_jp: "結局" },
    { word: "новый", translation_en: "new", translation_jp: "新しい" },
    { word: "каждый", translation_en: "each, every, everyone", translation_jp: "毎" },
    { word: "хороший", translation_en: "good, nice", translation_jp: "良い" },
    { word: "жить", translation_en: "live", translation_jp: "ライブ" },
    { word: "почему", translation_en: "why", translation_jp: "なぜ" },
    { word: "сторона", translation_en: "side, part", translation_jp: "側" },
    { word: "смотреть", translation_en: "to look, to watch", translation_jp: "見て" },
    { word: "иметь", translation_en: "to have, keep, hold, possess, carry, be, mean", translation_jp: "持っている" },
    { word: "просто", translation_en: "it is simple, it is easy, simply", translation_jp: "ただ" },
    { word: "понять", translation_en: "understand, comprehend, realize, realise", translation_jp: "理解する" },
    { word: "делать", translation_en: "make, do", translation_jp: "する" },
    { word: "сделать", translation_en: "make", translation_jp: "する" },
    { word: "вдруг", translation_en: "suddenly, all of a sudden, in case", translation_jp: "突然" },
    { word: "никто", translation_en: "nobody, no one", translation_jp: "誰でもない" },
    { word: "работа", translation_en: "work, working, job", translation_jp: "仕事" },
    { word: "перед", translation_en: "in front of", translation_jp: "前に" },
    { word: "ваш", translation_en: "your, yours", translation_jp: "あなたの" },
    { word: "над", translation_en: "above, over", translation_jp: "以上" },
    { word: "взять", translation_en: "to take", translation_jp: "取る" },
    { word: "конечно", translation_en: "certainly", translation_jp: "確かに" },
    { word: "понимать", translation_en: "understand, comprehend, realize", translation_jp: "理解する" },
    { word: "дверь", translation_en: "door", translation_jp: "ドア" },
    { word: "три", translation_en: "three", translation_jp: "三つ" },
    { word: "конец", translation_en: "end, ending", translation_jp: "終わり" },
    { word: "город", translation_en: "city, town", translation_jp: "市" },
    { word: "несколько", translation_en: "some a few several", translation_jp: "いくつかの" },
    { word: "начать", translation_en: "begin, start, commence", translation_jp: "始める" },
    { word: "голос", translation_en: "voice, part, vote", translation_jp: "声" },
    { word: "час", translation_en: "hour, time, hours", translation_jp: "時間" },
    { word: "пока", translation_en: "bye (informal)", translation_jp: "さよなら" },
    { word: "уж", translation_en: "grass snake", translation_jp: "本当に" },
    { word: "последний", translation_en: "last, latest, recent", translation_jp: "最後" },
    { word: "более", translation_en: "more", translation_jp: "もっと" },
    { word: "хорошо", translation_en: "it is good, it is pleasant, well, good", translation_jp: "大丈夫" },
    { word: "хотя", translation_en: "although, though, at least, despite", translation_jp: "それでも" },
    { word: "сила", translation_en: "power, might, strength, force", translation_jp: "強さ" },
    { word: "вода", translation_en: "water", translation_jp: "水" },
    { word: "второй", translation_en: "second, the latter", translation_jp: "2番" },
    { word: "увидеть", translation_en: "see", translation_jp: "見る" },
    { word: "всегда", translation_en: "always", translation_jp: "いつも" },
    { word: "давать", translation_en: "give, let", translation_jp: "与える" },
    { word: "случай", translation_en: "case or occasion, chance, opportunity, event, incident, occurrence", translation_jp: "ハプニング" },
    { word: "куда", translation_en: "where (to), whereto", translation_jp: "どこ" },
    { word: "пойти", translation_en: "(will) go on foot", translation_jp: "行く" },
    { word: "стол", translation_en: "table", translation_jp: "テーブル" },
    { word: "машина", translation_en: "car", translation_jp: "車" },
    { word: "мир", translation_en: "world", translation_jp: "世界" },
    { word: "ночь", translation_en: "night", translation_jp: "夜" },
    { word: "женщина", translation_en: "woman, women, womanfolk, womankind", translation_jp: "女性" },
    { word: "остаться", translation_en: "to remain or stay", translation_jp: "滞在する" },
    { word: "сразу", translation_en: "immediately, at once", translation_jp: "すぐに" },
    { word: "совсем", translation_en: "entirely, totally, completely, quite, at all", translation_jp: "全然" },
    { word: "выйти", translation_en: "leave, go out, get out", translation_jp: "出て行け" },
    { word: "вид", translation_en: "view", translation_jp: "ビュー" },
    { word: "отец", translation_en: "father", translation_jp: "父親" },
    { word: "вопрос", translation_en: "question", translation_jp: "質問" },
    { word: "дать", translation_en: "give, allocate", translation_jp: "与える" },
    { word: "работать", translation_en: "work, operate", translation_jp: "仕事" },
    { word: "оказаться", translation_en: "to turn out to be", translation_jp: "になることが判明" },
    { word: "ряд", translation_en: "row", translation_jp: "行" },
    { word: "почти", translation_en: "almost, nearly", translation_jp: "ほとんど" },
    { word: "снова", translation_en: "again (anew)", translation_jp: "また" },
    { word: "старый", translation_en: "old, ancient", translation_jp: "古い" },
    { word: "страна", translation_en: "country, ", translation_jp: "国" },
    { word: "твой", translation_en: "your, yours, thy, thine, your people", translation_jp: "あなたの" },
    { word: "между", translation_en: "between", translation_jp: "間" },
    { word: "ответить", translation_en: "answer", translation_jp: "答え" },
    { word: "много", translation_en: "much", translation_jp: "多くの" },
    { word: "война", translation_en: "war, warfare", translation_jp: "戦争" },
    { word: "подумать", translation_en: "to think a little, for a while", translation_jp: "考える" },
    { word: "любить", translation_en: "love", translation_jp: "愛" },
    { word: "белый", translation_en: "white", translation_jp: "白" },
    { word: "главный", translation_en: "main", translation_jp: "主要" },
    { word: "лишь", translation_en: "only, as soon as, merely, just", translation_jp: "のみ" },
    { word: "опять", translation_en: "again (occurring another time)", translation_jp: "また" },
    { word: "однако", translation_en: "however, though, but", translation_jp: "しかし" },
    { word: "правда", translation_en: "truth", translation_jp: "真実" },
    { word: "посмотреть", translation_en: "look, watch", translation_jp: "見て" },
    { word: "никогда", translation_en: "never, ever", translation_jp: "一度もない" },
    { word: "будто", translation_en: "as if, as though", translation_jp: "まるで" },
    { word: "часть", translation_en: "part", translation_jp: "一部" },
    { word: "именно", translation_en: "exactly, namely, to wit, that is, just", translation_jp: "その通り" },
    { word: "найти", translation_en: "find", translation_jp: "探す" },
    { word: "дорога", translation_en: "road, way, journey", translation_jp: "道" },
    { word: "свет", translation_en: "light", translation_jp: "ライト" },
    { word: "никакой", translation_en: "no...at all, no...whatsoever, none", translation_jp: "いいえ" },
    { word: "окно", translation_en: "window, casement-window, window-sill, gap, opening, port, slot", translation_jp: "ウィンドウ" },
    { word: "мать", translation_en: "mother", translation_jp: "母親" },
    { word: "решить", translation_en: "decide", translation_jp: "決める" },
    { word: "получить", translation_en: "receive, get, obtain", translation_jp: "得る" },
    { word: "улица", translation_en: "street", translation_jp: "通り" },
    { word: "вернуться", translation_en: "to return, come back (from)", translation_jp: "戻ってくる" },
    { word: "вообще", translation_en: "in general, generally", translation_jp: "全然" },
    { word: "маленький", translation_en: "little, small", translation_jp: "小さい" },
    { word: "считать", translation_en: "consider, deem, find, think", translation_jp: "カウント" },
    { word: "комната", translation_en: "room", translation_jp: "部屋" },
    { word: "вечер", translation_en: "evening", translation_jp: "夕方" },
    { word: "сегодня", translation_en: "today", translation_jp: "今日" },
    { word: "душа", translation_en: "soul", translation_jp: "魂" },
    { word: "книга", translation_en: "book, volume", translation_jp: "本" },
    { word: "вместе", translation_en: "together", translation_jp: "一緒に" },
    { word: "чуть", translation_en: "nearly", translation_jp: "少し" },
    { word: "пол", translation_en: "floor, ground", translation_jp: "床" },
    { word: "помнить", translation_en: "to remember, recollect, keep in mind", translation_jp: "覚えて" },
    { word: "сколько", translation_en: "how much, how many", translation_jp: "幾つか" },
    { word: "народ", translation_en: "people, nation", translation_jp: "人々" },
    { word: "хоть", translation_en: "though, even", translation_jp: "少なくとも" },
    { word: "взгляд", translation_en: "look, gaze, stare", translation_jp: "視力" },
    { word: "русский", translation_en: "Russian", translation_jp: "ロシア" },
    { word: "зачем", translation_en: "what for, why", translation_jp: "何のために" },
    { word: "история", translation_en: "history, story, event", translation_jp: "話" },
    { word: "полный", translation_en: "full, complete", translation_jp: "満杯" },
    { word: "узнать", translation_en: "learn", translation_jp: "知ること" },
    { word: "любой", translation_en: "any, every, anyone, either", translation_jp: "どれでも" },
    { word: "ходить", translation_en: "go, walk, move, pass", translation_jp: "歩く" },
    { word: "заметить", translation_en: "notice, note, observe, sight, catch sight, pay heed, remark", translation_jp: "知らせ" },
    { word: "известный", translation_en: "well-known", translation_jp: "有名な" },
    { word: "словно", translation_en: "as if like or seemingly", translation_jp: "まるで" },
    { word: "наконец", translation_en: "finally, at last", translation_jp: "ついに" },
    { word: "общий", translation_en: "common, general, overall", translation_jp: "一般的な" },
    { word: "имя", translation_en: "name, first name", translation_jp: "名前" },
    { word: "назад", translation_en: "back, backwards", translation_jp: "戻る" },
    { word: "мысль", translation_en: "thought", translation_jp: "考え" },
    { word: "уйти", translation_en: "leave, depart", translation_jp: "離れる" },
    { word: "быстро", translation_en: "fast, quickly, rapidly, with speed", translation_jp: "速い" },
    { word: "давно", translation_en: "how long, long ago", translation_jp: "長い間" },
    { word: "слушать", translation_en: "listen to, hear, attend, examine chest, auscultate, obey", translation_jp: "聞く" },
    { word: "прямо", translation_en: "straight", translation_jp: "直接" },
    { word: "разговор", translation_en: "conversation, talk", translation_jp: "話す" },
    { word: "долго", translation_en: "a long time, for a long time", translation_jp: "長い間" },
    { word: "нельзя", translation_en: "one cannot, you can't, it's impossible", translation_jp: "それは禁止されています" },
    { word: "право", translation_en: "right", translation_jp: "右" },
    { word: "лес", translation_en: "woods, forest", translation_jp: "森" },
    { word: "пять", translation_en: "five, 5", translation_jp: "五" },
    { word: "сын", translation_en: "son", translation_jp: "息子" },
    { word: "путь", translation_en: "way, track, path", translation_jp: "パス" },
    { word: "пора", translation_en: "it is time to", translation_jp: "時間です" },
    { word: "кроме", translation_en: "except, besides", translation_jp: "を除外する" },
    { word: "оставаться", translation_en: "remain, stay, be left", translation_jp: "滞在する" },
    { word: "совершенно", translation_en: "perfectly (adv)", translation_jp: "絶対に" },
    { word: "поэтому", translation_en: "that is why, therefore, so", translation_jp: "それが理由です" },
    { word: "написать", translation_en: "write", translation_jp: "書く" },
    { word: "пусть", translation_en: "let", translation_jp: "させて" },
    { word: "чувствовать", translation_en: "to feel, have a sensation, sense, taste", translation_jp: "感じる" },
    { word: "месяц", translation_en: "month", translation_jp: "月" },
    { word: "целый", translation_en: "whole, entire", translation_jp: "全体" },
    { word: "вести", translation_en: "to lead, conduct, direct", translation_jp: "鉛" },
    { word: "молодой", translation_en: "young, youthful", translation_jp: "若い" },
    { word: "огромный", translation_en: "enormous, huge, vast", translation_jp: "巨大な" },
    { word: "тело", translation_en: "body", translation_jp: "体" },
    { word: "настоящий", translation_en: "present, currently", translation_jp: "本物" },
    { word: "продолжать", translation_en: "to continue, go on, proceed, extend, prolong", translation_jp: "続く" },
    { word: "точно", translation_en: "exactly, precisely, right", translation_jp: "その通り" },
    { word: "язык", translation_en: "tongue", translation_jp: "言語" },
    { word: "мама", translation_en: "mom, mama, mommy, mummy", translation_jp: "母親" },
    { word: "смерть", translation_en: "death", translation_jp: "死" },
    { word: "власть", translation_en: "power", translation_jp: "力" },
    { word: "мальчик", translation_en: "boy", translation_jp: "男の子" },
    { word: "также", translation_en: "also, as well, too, either", translation_jp: "また" },
    { word: "брать", translation_en: "to take, to get", translation_jp: "取る" },
    { word: "образ", translation_en: "shape, form, image", translation_jp: "画像" },
    { word: "отношение", translation_en: "relationship", translation_jp: "態度" },
    { word: "сердце", translation_en: "heart", translation_jp: "心臓" },
    { word: "пройти", translation_en: "pass", translation_jp: "合格" },
    { word: "вокруг", translation_en: "around, round, about", translation_jp: "その周り" },
    { word: "девушка", translation_en: "girl, lass", translation_jp: "若い女性" },
    { word: "солдат", translation_en: "soldier, regular, private", translation_jp: "兵士" },
    { word: "иногда", translation_en: "sometimes, at times", translation_jp: "時々" },
    { word: "забыть", translation_en: "to forget [something]", translation_jp: "忘れる" },
    { word: "вспомнить", translation_en: "to recall, remember", translation_jp: "想起" },
    { word: "небо", translation_en: "sky", translation_jp: "空" },
    { word: "затем", translation_en: "then, after that, thereupon, upon which, subsequently, for that reason", translation_jp: "それから" },
    { word: "система", translation_en: "system", translation_jp: "システム" },
    { word: "воздух", translation_en: "air (usually uncountable)", translation_jp: "空気" },
    { word: "оба", translation_en: "both", translation_jp: "両方" },
    { word: "собственный", translation_en: "one's own", translation_jp: "自分の" },
    { word: "находиться", translation_en: "be situated", translation_jp: "なれ" },
    { word: "держать", translation_en: "to hold, keep, support", translation_jp: "所有" },
    { word: "показать", translation_en: "to show", translation_jp: "見せる" },
    { word: "ребята", translation_en: "lads, boys, guys", translation_jp: "みんな" },
    { word: "брат", translation_en: "brother", translation_jp: "兄弟" },
    { word: "квартира", translation_en: "flat, quarters", translation_jp: "アパート" },
    { word: "откуда", translation_en: "from where", translation_jp: "どこ" },
    { word: "четыре", translation_en: "four, 4", translation_jp: "4" },
    { word: "рассказать", translation_en: "to tell", translation_jp: "教えて" },
    { word: "особенно", translation_en: "particularly", translation_jp: "特に" },
    { word: "кровь", translation_en: "blood", translation_jp: "血" },
    { word: "внимание", translation_en: "attention, notice", translation_jp: "注意" },
    { word: "поставить", translation_en: "to put, place", translation_jp: "置く" },
    { word: "вроде", translation_en: "seem, think, like, sort of, kind of", translation_jp: "のように" },
    { word: "например", translation_en: "for example, for instance", translation_jp: "例えば" },
    { word: "оставить", translation_en: "to leave leave alone left", translation_jp: "離れる" },
    { word: "туда", translation_en: "there, to there", translation_jp: "そこには" },
    { word: "действительно", translation_en: "really, actually, indeed", translation_jp: "本当に" },
    { word: "мало", translation_en: "little, few, a little bit", translation_jp: "少し" },
    { word: "школа", translation_en: "school, schoolhouse", translation_jp: "学校" },
    { word: "равно", translation_en: "is indifferent, alike, in like manner, nor", translation_jp: "等しい" },
    { word: "труд", translation_en: "work, labor", translation_jp: "仕事" },
    { word: "сюда", translation_en: "here", translation_jp: "ここ" },
    { word: "слишком", translation_en: "too (much), too (more than enough)", translation_jp: "過度に" },
    { word: "следующий", translation_en: "following", translation_jp: "次" },
    { word: "парень", translation_en: "boy, guy, fellow, lad, chap, bloke", translation_jp: "男の子" },
    { word: "группа", translation_en: "group, cluster, clump", translation_jp: "グループ" },
    { word: "солнце", translation_en: "sun", translation_jp: "太陽" },
    { word: "любовь", translation_en: "love", translation_jp: "愛" },
    { word: "войти", translation_en: "enter, go in, come in, include", translation_jp: "ログイン" },
    { word: "ответ", translation_en: "answer, reply, response", translation_jp: "答え" },
    { word: "десять", translation_en: "ten, 10", translation_jp: "10" },
    { word: "спать", translation_en: "to sleep", translation_jp: "寝る" },
    { word: "двадцать", translation_en: "twenty", translation_jp: "二十" },
    { word: "берег", translation_en: "shore", translation_jp: "海岸" },
    { word: "помощь", translation_en: "help", translation_jp: "ヘルプ" },
    { word: "мужчина", translation_en: "man", translation_jp: "男" },
    { word: "момент", translation_en: "moment (time)", translation_jp: "一瞬" },
    { word: "искать", translation_en: "to look for, search, seek", translation_jp: "検索" },
    { word: "газета", translation_en: "newspaper, paper, daily paper, daily", translation_jp: "新聞" },
    { word: "против", translation_en: "against, opposite, facing, contrary to, to, as against", translation_jp: "に対して" },
    { word: "верить", translation_en: "to believe, trust", translation_jp: "信じる" },
    { word: "чувство", translation_en: "sense, feeling (sensation)", translation_jp: "フィーリング" },
    { word: "порядок", translation_en: "order of magnitude", translation_jp: "注文" },
    { word: "семья", translation_en: "family", translation_jp: "家族" },
    { word: "армия", translation_en: "army, forces, host", translation_jp: "軍" },
    { word: "играть", translation_en: "to play", translation_jp: "遊ぶ" },
    { word: "возможность", translation_en: "opportunity, chance, means, resources", translation_jp: "機会" },
    { word: "разве", translation_en: "Really...?", translation_jp: "そうじゃない？" },
    { word: "впрочем", translation_en: "however", translation_jp: "しかし" },
    { word: "движение", translation_en: "movement, motion, stirring", translation_jp: "動き" },
    { word: "муж", translation_en: "husband, man", translation_jp: "夫" },
    { word: "тихо", translation_en: "quietly, it is calm, it is quiet, softly, gently, faintly, silently", translation_jp: "静かな" },
    { word: "огонь", translation_en: "fire", translation_jp: "火" },
    { word: "иной", translation_en: "different, other, not the same as in another option or choice", translation_jp: "他の" },
    { word: "бежать", translation_en: "to run", translation_jp: "走る" },
    { word: "наверное", translation_en: "probably, maybe, most likely", translation_jp: "多分" },
    { word: "простой", translation_en: "simple, easy, common, plain, mere", translation_jp: "単純" },
    { word: "принять", translation_en: "to take", translation_jp: "受け入れる" },
    { word: "угол", translation_en: "corner, angle, home", translation_jp: "コーナー" },
    { word: "смысл", translation_en: "meaning, sense, significance", translation_jp: "意味" },
    { word: "открыть", translation_en: "to open, to unbar, to turn on", translation_jp: "開ける" },
    { word: "общество", translation_en: "society", translation_jp: "社会" },
    { word: "военный", translation_en: "(relational) war", translation_jp: "軍隊" },
    { word: "дерево", translation_en: "tree, wood", translation_jp: "木" },
    { word: "снег", translation_en: "snow", translation_jp: "雪" },
    { word: "либо", translation_en: "or", translation_jp: "または" },
    { word: "ехать", translation_en: "to go (by horse or vehicle), drive, ride", translation_jp: "ドライブ" },
    { word: "очередь", translation_en: "queue, line", translation_jp: "列" },
    { word: "форма", translation_en: "form, shape, mound", translation_jp: "形状" },
    { word: "закон", translation_en: "law, act, statute", translation_jp: "法" },
    { word: "собака", translation_en: "dog", translation_jp: "犬" },
    { word: "домой", translation_en: "homeward, home, to one's home", translation_jp: "家" },
    { word: "попасть", translation_en: "to get (to)", translation_jp: "入れ" },
    { word: "состояние", translation_en: "the state (the condition of somethings existence)", translation_jp: "州" },
    { word: "сон", translation_en: "dream", translation_jp: "夢" },
    { word: "часто", translation_en: "often, frequently", translation_jp: "頻繁" },
    { word: "девочка", translation_en: "girl, little girl, girlie", translation_jp: "女の子" },
    { word: "камень", translation_en: "stone, rock", translation_jp: "石" },
    { word: "сначала", translation_en: "firstly, at first, all over again, afresh", translation_jp: "初めに" },
    { word: "ветер", translation_en: "wind, breeze", translation_jp: "風" },
    { word: "проблема", translation_en: "problem", translation_jp: "問題" },
    { word: "связь", translation_en: "connection, link, bond, touch", translation_jp: "繋がり" },
    { word: "номер", translation_en: "number, size, room, issue, item on the programme, turn, trick", translation_jp: "番号" },
    { word: "средство", translation_en: "remedy", translation_jp: "手段" },
    { word: "единственный", translation_en: "only, the only", translation_jp: "唯一の人" },
    { word: "действие", translation_en: "action", translation_jp: "アクション" },
    { word: "ход", translation_en: "motion, run, speed, way, course, progress", translation_jp: "動く" },
    { word: "государство", translation_en: "State", translation_jp: "州" },
    { word: "российский", translation_en: "Russian (related to the state)", translation_jp: "ロシア" },
    { word: "глава", translation_en: "head, chief", translation_jp: "章" },
    { word: "партия", translation_en: "party, detachment, group, set", translation_jp: "パーティー" },
    { word: "край", translation_en: "edge (border, end), brim, brink, side, line", translation_jp: "角" },
    { word: "вперёд", translation_en: "forward (куда) about direction, ahead", translation_jp: "フォワード" },
    { word: "судьба", translation_en: "fate, fortune, destiny", translation_jp: "運命" },
    { word: "речь", translation_en: "Talk about, speech, enunciation, style of speaking, language, discourse, oration, address", translation_jp: "スピーチ" },
    { word: "заниматься", translation_en: "to be engaged", translation_jp: "勉強" },
    { word: "вполне", translation_en: "fully entirely or perfectly", translation_jp: "とても" },
    { word: "причина", translation_en: "reason", translation_jp: "原因" },
    { word: "никак", translation_en: "in no way", translation_jp: "とんでもない" },
    { word: "страх", translation_en: "fear", translation_jp: "恐れ" },
    { word: "едва", translation_en: "hardly, only just, scarcely, just, barely", translation_jp: "かろうじて" },
    { word: "море", translation_en: "sea, ocean", translation_jp: "海" },
    { word: "зал", translation_en: "hall, audience chamber, reception-room", translation_jp: "ホール" },
    { word: "врач", translation_en: "doctor", translation_jp: "医者" },
    { word: "возле", translation_en: "near, beside, by", translation_jp: "近く" },
    { word: "довольно", translation_en: "enough, sufficient", translation_jp: "十分" },
    { word: "основной", translation_en: "basic", translation_jp: "基本的な" },
    { word: "ясно", translation_en: "clearly", translation_jp: "それは明らかです" },
    { word: "боль", translation_en: "pain", translation_jp: "痛み" },
    { word: "вчера", translation_en: "yesterday", translation_jp: "昨日" },
    { word: "вещь", translation_en: "thing, things, belongings, clothes, work", translation_jp: "もの" },
    { word: "результат", translation_en: "result, outcome", translation_jp: "結果" },
    { word: "число", translation_en: "number, quantity", translation_jp: "番号" },
    { word: "цель", translation_en: "aim, goal, object, objective, target, mark", translation_jp: "ターゲット" },
    { word: "положение", translation_en: "situation", translation_jp: "位置" },
    { word: "бывший", translation_en: "former, late, quondam, ex-", translation_jp: "前者" },
    { word: "далеко", translation_en: "far, it is far, it is a long way, far off, a long way off, a great distance away", translation_jp: "遠い" },
    { word: "проходить", translation_en: "to pass, go to, to walk", translation_jp: "合格" },
    { word: "план", translation_en: "plan, scheme, map, target", translation_jp: "プラン" },
    { word: "около", translation_en: "near, about", translation_jp: "近く" },
    { word: "широкий", translation_en: "wide", translation_jp: "広い" },
    { word: "завтра", translation_en: "tomorrow", translation_jp: "明日" },
    { word: "снять", translation_en: "to take off (clothes), remove", translation_jp: "脱ぐ" },
    { word: "плохо", translation_en: "it is bad", translation_jp: "ひどく" },
    { word: "представить", translation_en: "to introduce, to place before [someone]", translation_jp: "導入" },
    { word: "небольшой", translation_en: "small, not great, short", translation_jp: "小さい" },
    { word: "обычно", translation_en: "usually, generally, commonly, as a rule", translation_jp: "いつもの" },
    { word: "волос", translation_en: "hair", translation_jp: "髪" },
    { word: "объяснить", translation_en: "explain, account", translation_jp: "説明する" },
    { word: "пара", translation_en: "couple, match", translation_jp: "ペア" },
    { word: "решение", translation_en: "decision", translation_jp: "解決" },
    { word: "купить", translation_en: "buy, purchase", translation_jp: "買う" },
    { word: "иначе", translation_en: "otherwise, or else, else", translation_jp: "さもないと" },
    { word: "класс", translation_en: "class, form, class-room", translation_jp: "クラス" },
    { word: "центр", translation_en: "center, centre", translation_jp: "中心" },
    { word: "скоро", translation_en: "quickly, fast, soon", translation_jp: "すぐ" },
    { word: "прежде", translation_en: "before, first, formerly, in former times", translation_jp: "前に" },
    { word: "пить", translation_en: "drink", translation_jp: "飲む" },
    { word: "встреча", translation_en: "meeting, reception, match, meet, appointment", translation_jp: "ミーティング" },
    { word: "однажды", translation_en: "one day", translation_jp: "ある日" },
    { word: "служба", translation_en: "service, work", translation_jp: "サービス" },
    { word: "процесс", translation_en: "process, trial, legal proceedings, legal action, cause, case, lawsuit, suit, active condition", translation_jp: "プロセス" },
    { word: "президент", translation_en: "president", translation_jp: "社長" },
    { word: "сквозь", translation_en: "through", translation_jp: "を通して" },
    { word: "сообщить", translation_en: "report, let know, communicate, impart, inform", translation_jp: "報告" },
    { word: "герой", translation_en: "hero", translation_jp: "ヒーロー" },
    { word: "дух", translation_en: "ghost spirit mind", translation_jp: "精神" },
    { word: "мимо", translation_en: "past, by", translation_jp: "による" },
    { word: "кстати", translation_en: "by the way, incidentally, besides, in fact", translation_jp: "ところで" },
    { word: "счастье", translation_en: "happiness, luck, good fortune", translation_jp: "幸せ" },
    { word: "удар", translation_en: "blow, kick, stroke, impact, stab, lash, slash, punch, cuff", translation_jp: "打つ" },
    { word: "старший", translation_en: "elder, oldest, eldest, senior, chief, man in charge, elders", translation_jp: "シニア" },
    { word: "вместо", translation_en: "instead of", translation_jp: "の代わりに" },
    { word: "самолёт", translation_en: "aircraft, aeroplane, airplane, plane, air-liner", translation_jp: "飛行機" },
    { word: "трудно", translation_en: "difficultly", translation_jp: "難しい" },
    { word: "деревня", translation_en: "village (small settlement), hamlet", translation_jp: "村" },
    { word: "картина", translation_en: "picture", translation_jp: "絵画" },
    { word: "ум", translation_en: "mind, brains, wit, intellect", translation_jp: "心" },
    { word: "менее", translation_en: "less", translation_jp: "少ない" },
    { word: "предложить", translation_en: "suggest", translation_jp: "オファー" },
    { word: "вызвать", translation_en: "to call, to send for", translation_jp: "電話" },
    { word: "многие", translation_en: "many", translation_jp: "多くの" },
    { word: "легко", translation_en: "lightly, slightly", translation_jp: "簡単に" },
    { word: "государственный", translation_en: "state", translation_jp: "州" },
    { word: "рабочий", translation_en: "a worker", translation_jp: "ワーカー" },
    { word: "телефон", translation_en: "telephone, phone", translation_jp: "電話" },
    { word: "компания", translation_en: "company", translation_jp: "会社" },
    { word: "принимать", translation_en: "take", translation_jp: "受け入れる" },
    { word: "вниз", translation_en: "down, downwards", translation_jp: "下" },
    { word: "автор", translation_en: "author, authoress, writer, composer, begetter", translation_jp: "著者" },
    { word: "интерес", translation_en: "interest", translation_jp: "興味" },
    { word: "провести", translation_en: "spend", translation_jp: "実行する" },
    { word: "двое", translation_en: "two", translation_jp: "二" },
    { word: "счёт", translation_en: "bill", translation_jp: "チェック" },
    { word: "спокойно", translation_en: "quietly, calmly", translation_jp: "冷静に" },
    { word: "местный", translation_en: "local, of a place", translation_jp: "地元" },
    { word: "игра", translation_en: "play", translation_jp: "ゲーム" },
    { word: "качество", translation_en: "quality, exchange", translation_jp: "品質" },
    { word: "родной", translation_en: "native, home, dear, darling, relatives, relations, kinsfolk, kin", translation_jp: "ネイティブ" },
    { word: "член", translation_en: "member", translation_jp: "メンバー" },
    { word: "достаточно", translation_en: "it is enough, sufficiently, enough", translation_jp: "十分" },
    { word: "золотой", translation_en: "golden", translation_jp: "金" },
    { word: "развитие", translation_en: "development, unfolding of events etc", translation_jp: "発達" },
    { word: "важный", translation_en: "important, significant, grand, pompous", translation_jp: "重要" },
    { word: "банк", translation_en: "bank (financial establishment), faro", translation_jp: "銀行" },
    { word: "столько", translation_en: "so much, so many, as much", translation_jp: "とてもたくさんの" },
    { word: "институт", translation_en: "institute, ", translation_jp: "研究所" },
    { word: "правительство", translation_en: "government", translation_jp: "政府" },
    { word: "уровень", translation_en: "level, standard", translation_jp: "レベル" },
    { word: "профессор", translation_en: "professor", translation_jp: "教授" },
    { word: "событие", translation_en: "event", translation_jp: "イベント" },
    { word: "союз", translation_en: "union, alliance, Union, league, agreement, conjunction", translation_jp: "連合" },
    { word: "король", translation_en: "king", translation_jp: "王" },
    { word: "половина", translation_en: "half", translation_jp: "半分" },
    { word: "область", translation_en: "area province region", translation_jp: "地域" },
    { word: "ситуация", translation_en: "situation", translation_jp: "状況" },
    { word: "кухня", translation_en: "kitchen, cook-house, galley, cooking, cuisine, machinations", translation_jp: "台所" },
    { word: "род", translation_en: "generation, birth, origin, stock, family, race, kin", translation_jp: "属" },
    { word: "течение", translation_en: "current, flow, stream", translation_jp: "流れ" },
    { word: "помочь", translation_en: "help, assist, aid, give sb. a hand", translation_jp: "ヘルプ" },
    { word: "немецкий", translation_en: "German", translation_jp: "ドイツ語" },
    { word: "создать", translation_en: "to found, to originate", translation_jp: "作成する" },
    { word: "поскольку", translation_en: "since", translation_jp: "なぜなら" },
    { word: "получать", translation_en: "Receive, get, obtain, getting", translation_jp: "受け取る" },
    { word: "шесть", translation_en: "six, 6", translation_jp: "六" },
    { word: "борьба", translation_en: "struggle", translation_jp: "闘争" },
    { word: "правило", translation_en: "rule, precept, principle, maxim, law, canon (regulation)", translation_jp: "ルール" },
    { word: "программа", translation_en: "program", translation_jp: "プログラム" },
    { word: "звук", translation_en: "sound", translation_jp: "音" },
    { word: "неожиданно", translation_en: "unexpectedly, suddenly", translation_jp: "突然" },
    { word: "чай", translation_en: "tea, tea-party, methinks, maybe", translation_jp: "お茶" },
    { word: "роль", translation_en: "role", translation_jp: "役割" },
    { word: "сознание", translation_en: "consciousness", translation_jp: "意識" },
    { word: "команда", translation_en: "team, crew, party", translation_jp: "チーム" },
    { word: "спасибо", translation_en: "thanks, thank you", translation_jp: "ありがとう" },
    { word: "прекрасный", translation_en: "wonderful, beautiful, fine, excellent", translation_jp: "美しい" },
    { word: "магазин", translation_en: "shop, store, magazine", translation_jp: "店" },
    { word: "впервые", translation_en: "for the first time", translation_jp: "初めて" },
    { word: "американский", translation_en: "American", translation_jp: "アメリカ人" },
    { word: "запах", translation_en: "smell", translation_jp: "匂い" },
    { word: "район", translation_en: "region, district, area, vicinity", translation_jp: "地区" },
    { word: "стекло", translation_en: "glass, glassware", translation_jp: "ガラス" },
    { word: "выше", translation_en: "above, higher, over, beyond", translation_jp: "より高い" },
    { word: "количество", translation_en: "quantity", translation_jp: "量" },
    { word: "этаж", translation_en: "floor, storey", translation_jp: "床" },
    { word: "тип", translation_en: "type, model", translation_jp: "タイプ" },
    { word: "суд", translation_en: "law-court, court, justice, judgment, trial, the judges, the bench", translation_jp: "裁判所" },
    { word: "выход", translation_en: "exit, way out, leaving, withdrawal", translation_jp: "出口" },
    { word: "дочь", translation_en: "daughter", translation_jp: "娘" },
    { word: "характер", translation_en: "character, temper, disposition", translation_jp: "キャラクター" },
    { word: "опыт", translation_en: "experience, expertise, skill", translation_jp: "経験" },
    { word: "площадь", translation_en: "area (geometry)", translation_jp: "四角" },
    { word: "управление", translation_en: "administration, direction, control", translation_jp: "コントロール" },
    { word: "мнение", translation_en: "opinion", translation_jp: "意見" },
    { word: "впереди", translation_en: "in front", translation_jp: "先に" },
    { word: "использовать", translation_en: "use", translation_jp: "使用" },
    { word: "рост", translation_en: "growth (in a living organism)", translation_jp: "身長" },
    { word: "лошадь", translation_en: "horse", translation_jp: "馬" },
    { word: "кожа", translation_en: "skin, leather", translation_jp: "レザー" },
    { word: "служить", translation_en: "to serve (eg. in the military)", translation_jp: "仕える" },
    { word: "сестра", translation_en: "sister", translation_jp: "妹" },
    { word: "пожалуйста", translation_en: "please", translation_jp: "お願いします" },
    { word: "нечего", translation_en: "nothing", translation_jp: "何もない" },
    { word: "дождь", translation_en: "rain", translation_jp: "雨" },
    { word: "желание", translation_en: "desire", translation_jp: "願い" },
    { word: "болезнь", translation_en: "illness, disease", translation_jp: "病気" },
    { word: "встретить", translation_en: "meet", translation_jp: "会う" },
    { word: "пример", translation_en: "example, instance", translation_jp: "例" },
    { word: "позволить", translation_en: "let or allow", translation_jp: "許可する" },
    { word: "поле", translation_en: "field", translation_jp: "分野" },
    { word: "цена", translation_en: "cost or price", translation_jp: "価格" },
    { word: "карта", translation_en: "card", translation_jp: "地図" },
    { word: "радость", translation_en: "gladness, joy", translation_jp: "喜び" },
    { word: "зато", translation_en: "for it, in return", translation_jp: "しかし" },
    { word: "действовать", translation_en: "act, take action", translation_jp: "活動" },
    { word: "музыка", translation_en: "music", translation_jp: "音楽" },
    { word: "завод", translation_en: "factory, plant", translation_jp: "工場" },
    { word: "добавить", translation_en: "add", translation_jp: "追加" },
    { word: "лето", translation_en: "summer", translation_jp: "夏" },
    { word: "станция", translation_en: "station", translation_jp: "駅" },
    { word: "детский", translation_en: "childish, infantile, puerile, childlike", translation_jp: "子供の" },
    { word: "приказ", translation_en: "an order/command", translation_jp: "注文" },
    { word: "гражданин", translation_en: "citizen", translation_jp: "市民" },
    { word: "цвет", translation_en: "color, colour", translation_jp: "色" },
    { word: "статья", translation_en: "article, item, clause, point, class, rating", translation_jp: "記事" },
    { word: "круг", translation_en: "circle, sphere, range, scope, reach, lap", translation_jp: "丸" },
    { word: "столь", translation_en: "so and such (literary)", translation_jp: "それで" },
    { word: "факт", translation_en: "fact", translation_jp: "事実" },
    { word: "причём", translation_en: "Moreover, in addition, besides, what's more, and, at that, with", translation_jp: "そして" },
    { word: "учиться", translation_en: "to study", translation_jp: "勉強" },
    { word: "средний", translation_en: "middle, average, mean, middling", translation_jp: "平均" },
    { word: "современный", translation_en: "modern/contemporary (adj)", translation_jp: "モダンな" },
    { word: "лагерь", translation_en: "camp", translation_jp: "キャンプ" },
    { word: "недавно", translation_en: "recently", translation_jp: "最近" },
    { word: "удовольствие", translation_en: "pleasure, amusement", translation_jp: "喜び" },
    { word: "возраст", translation_en: "age", translation_jp: "年" },
    { word: "передать", translation_en: "to transfer", translation_jp: "引き渡す" },
    { word: "сад", translation_en: "garden", translation_jp: "庭" },
    { word: "проводить", translation_en: "spend", translation_jp: "行為" },
    { word: "задача", translation_en: "task, exercise, problem", translation_jp: "タスク" },
    { word: "название", translation_en: "name title", translation_jp: "名前" },
    { word: "двигаться", translation_en: "to move, advance", translation_jp: "動く" },
    { word: "большинство", translation_en: "the majority, most", translation_jp: "過半数" },
    { word: "председатель", translation_en: "chairman, president, the Speaker", translation_jp: "会長" },
    { word: "прямой", translation_en: "straight, upright, erect, through, direct, straightforward, frank, sincere, real", translation_jp: "直接" },
    { word: "попробовать", translation_en: "attempt, try, endeavour, test, taste, feel", translation_jp: "試す" },
    { word: "вверх", translation_en: "up, upwards, upstream", translation_jp: "上" },
    { word: "знак", translation_en: "sign, token, symbol, mark, omen, signal", translation_jp: "サイン" },
    { word: "семь", translation_en: "seven, 7", translation_jp: "セブン" },
    { word: "мозг", translation_en: "brain, marrow, brains", translation_jp: "脳" },
    { word: "обязательно", translation_en: "necessarily", translation_jp: "必然的に" },
    { word: "очередной", translation_en: "another recurrent next (adj)", translation_jp: "別の" },
    { word: "деятельность", translation_en: "activity", translation_jp: "活動" },
    { word: "страшно", translation_en: "scarily, fearfully", translation_jp: "怖い" },
    { word: "ставить", translation_en: "to put or place", translation_jp: "置く" },
    { word: "здание", translation_en: "building, edifice", translation_jp: "建物" },
    { word: "искусство", translation_en: "art", translation_jp: "美術" },
    { word: "начало", translation_en: "beginning, commencement, start, onset", translation_jp: "始める" },
    { word: "срок", translation_en: "deadline", translation_jp: "学期" },
    { word: "одежда", translation_en: "clothing", translation_jp: "布" },
    { word: "корабль", translation_en: "ship, ferry", translation_jp: "船" },
    { word: "художник", translation_en: "artist, painter", translation_jp: "アーティスト" },
    { word: "курс", translation_en: "course, policy, rate of exchange", translation_jp: "良い" },
    { word: "дорогой", translation_en: "expensive, costly, precious", translation_jp: "高い" },
    { word: "оттуда", translation_en: "from there", translation_jp: "そこから" },
    { word: "фирма", translation_en: "firm", translation_jp: "固い" },
    { word: "тема", translation_en: "topic", translation_jp: "トピック" },
    { word: "мировой", translation_en: "first-rate, first-class", translation_jp: "世界" },
    { word: "линия", translation_en: "line", translation_jp: "ライン" },
    { word: "сутки", translation_en: "twenty-four hours, day, nychthemeron", translation_jp: "日" },
    { word: "ключ", translation_en: "key, clue, clef, source, spring", translation_jp: "鍵" },
    { word: "немедленно", translation_en: "immediately, at once", translation_jp: "すぐに" },
    { word: "остров", translation_en: "island, isle", translation_jp: "島" },
    { word: "театр", translation_en: "theatre, play-house, dramatic works, plays", translation_jp: "劇場" },
    { word: "производство", translation_en: "production", translation_jp: "生産" },
    { word: "трое", translation_en: "three of ...", translation_jp: "三つ" },
    { word: "материал", translation_en: "material, stuff, fabric", translation_jp: "材料" },
    { word: "значение", translation_en: "meaning, significance", translation_jp: "意味" },
    { word: "отказаться", translation_en: "refuse, decline, repudiate", translation_jp: "拒否する" },
    { word: "способ", translation_en: "way", translation_jp: "方法" },
    { word: "волна", translation_en: "wave", translation_jp: "波" },
    { word: "специальный", translation_en: "special", translation_jp: "特別" },
    { word: "представитель", translation_en: "representative", translation_jp: "代表" },
    { word: "рынок", translation_en: "market", translation_jp: "市場" },
    { word: "впечатление", translation_en: "impression, influence, effect", translation_jp: "印象" },
    { word: "отдел", translation_en: "department", translation_jp: "部門" },
    { word: "успех", translation_en: "success", translation_jp: "成功" },
    { word: "население", translation_en: "population, inhabitants, peopling, setting", translation_jp: "人口" },
    { word: "вдоль", translation_en: "along", translation_jp: "平行" },
    { word: "следить", translation_en: "watch, spy, shadow, follow", translation_jp: "追跡" },
    { word: "спасти", translation_en: "save, rescue, salvage", translation_jp: "保存" },
    { word: "знание", translation_en: "knowledge", translation_jp: "知識" },
    { word: "масса", translation_en: "weight", translation_jp: "重さ" },
    { word: "одновременно", translation_en: "simultaneously", translation_jp: "同時に" },
    { word: "естественно", translation_en: "naturally, of course", translation_jp: "当然" },
    { word: "направление", translation_en: "direction", translation_jp: "方向" },
    { word: "победа", translation_en: "victory/triumph", translation_jp: "勝利" },
    { word: "сотрудник", translation_en: "employee", translation_jp: "従業員" },
    { word: "городской", translation_en: "urban", translation_jp: "都会的な" },
    { word: "адрес", translation_en: "address", translation_jp: "住所" },
    { word: "обращаться", translation_en: "treat handle", translation_jp: "住所" },
    { word: "период", translation_en: "period", translation_jp: "期間" },
    { word: "пользоваться", translation_en: "make use of, profit, enjoy, use", translation_jp: "使用" },
    { word: "клуб", translation_en: "club, club-house, puff", translation_jp: "クラブ" },
    { word: "восемь", translation_en: "eight, 8", translation_jp: "八" },
    { word: "предмет", translation_en: "the subject, the item, the matter", translation_jp: "アイテム" },
    { word: "честь", translation_en: "to honour, to honor, to respect", translation_jp: "名誉" },
    { word: "наблюдать", translation_en: "observe, monitor, watch", translation_jp: "観察する" },
    { word: "наоборот", translation_en: "on the contrary, inside out, back to front, the wrong way, vice-versa", translation_jp: "逆に" },
    { word: "культура", translation_en: "culture", translation_jp: "文化" },
    { word: "территория", translation_en: "territory", translation_jp: "地域" },
    { word: "гораздо", translation_en: "much, far, by far, way", translation_jp: "多くの" },
    { word: "поздно", translation_en: "it is late, late", translation_jp: "遅い" },
    { word: "остановить", translation_en: "stop, bring to stop", translation_jp: "停止" },
    { word: "полностью", translation_en: "completely, utterly, in full", translation_jp: "完全に" },
    { word: "страница", translation_en: "page", translation_jp: "ページ" },
    { word: "размер", translation_en: "size", translation_jp: "サイズ" },
    { word: "предприятие", translation_en: "enterprise (doanh nghiệp)/venture", translation_jp: "企業" },
    { word: "английский", translation_en: "English, British", translation_jp: "英語" },
    { word: "принцип", translation_en: "principle", translation_jp: "原理" },
    { word: "платить", translation_en: "to pay", translation_jp: "支払う" },
    { word: "вероятно", translation_en: "likely, probably, perhaps", translation_jp: "おそらく" },
    { word: "руководитель", translation_en: "leader", translation_jp: "監督者" },
    { word: "наиболее", translation_en: "most, in advance", translation_jp: "ほとんど" },
    { word: "внутри", translation_en: "inside, within", translation_jp: "内部" },
    { word: "фильм", translation_en: "movie, film", translation_jp: "映画" },
    { word: "специалист", translation_en: "specialist, expert", translation_jp: "スペシャリスト" },
    { word: "образование", translation_en: "education", translation_jp: "教育" },
    { word: "выбрать", translation_en: "choose, select, pick out, elect, take out", translation_jp: "選ぶ" },
    { word: "тяжело", translation_en: "hard, difficult", translation_jp: "難しい" },
    { word: "продукт", translation_en: "product, produce", translation_jp: "製品" },
    { word: "постепенно", translation_en: "gradually, little by little, by degrees", translation_jp: "徐々に" },
    { word: "собрать", translation_en: "gather, collect, convoke, assemble, equip, make gathers", translation_jp: "集める" },
    { word: "внимательно", translation_en: "attentively, carefully, intently", translation_jp: "注意深く" },
    { word: "скорость", translation_en: "speed, rate, velocity", translation_jp: "スピード" },
    { word: "участок", translation_en: "region, lot, plot, strip, parcel", translation_jp: "プロット" },
    { word: "текст", translation_en: "text, words", translation_jp: "文章" },
    { word: "участие", translation_en: "participation", translation_jp: "参加" },
    { word: "мост", translation_en: "bridge", translation_jp: "橋" },
    { word: "примерно", translation_en: "around", translation_jp: "約" },
    { word: "здоровье", translation_en: "health", translation_jp: "健康" },
    { word: "морской", translation_en: "marine, maritime, naval, nautical", translation_jp: "航海用" },
    { word: "отсутствие", translation_en: "absence", translation_jp: "不在" },
    { word: "случайно", translation_en: "by chance, by accident, accidentally, by any chance", translation_jp: "偶然" },
    { word: "мясо", translation_en: "meat", translation_jp: "肉" },
    { word: "отметить", translation_en: "mark, note, mark off, mention, register", translation_jp: "注記" },
    { word: "доска", translation_en: "board, plank, slab", translation_jp: "ボード" },
    { word: "убийство", translation_en: "murder, assassination", translation_jp: "殺人" },
    { word: "настроение", translation_en: "mood, humour, sentiments, mindset", translation_jp: "気分" },
    { word: "постоянно", translation_en: "constantly, continually, always", translation_jp: "常に" },
    { word: "долг", translation_en: "debt", translation_jp: "義務" },
    { word: "настолько", translation_en: "so much", translation_jp: "それで" },
    { word: "предложение", translation_en: "proposal suggestion", translation_jp: "オファー" },
    { word: "внешний", translation_en: "external (adj)", translation_jp: "外部の" },
    { word: "проверить", translation_en: "check, verify, test, examine, audit", translation_jp: "チェック" },
    { word: "отправить", translation_en: "send", translation_jp: "送信" },
    { word: "оставлять", translation_en: "leave, leave alone", translation_jp: "離れる" },
    { word: "ресторан", translation_en: "restaurant", translation_jp: "レストラン" },
    { word: "список", translation_en: "list, record", translation_jp: "リスト" },
    { word: "праздник", translation_en: "holiday, feast, a festive occasion", translation_jp: "休日" },
    { word: "автобус", translation_en: "bus, coach", translation_jp: "バス" },
    { word: "организм", translation_en: "organism", translation_jp: "生物" },
    { word: "масло", translation_en: "butter / oil", translation_jp: "油" },
    { word: "международный", translation_en: "international", translation_jp: "国際的" },
    { word: "пиво", translation_en: "beer", translation_jp: "ビール" },
    { word: "полтора", translation_en: "one and a half", translation_jp: "１個半" },
    { word: "центральный", translation_en: "central, metropolitan", translation_jp: "中央" },
    { word: "защита", translation_en: "defence", translation_jp: "保護" },
    { word: "энергия", translation_en: "energy", translation_jp: "エネルギー" },
    { word: "тепло", translation_en: "warm, it is warm", translation_jp: "暖かい" },
    { word: "установить", translation_en: "set up install place", translation_jp: "インストール" },
    { word: "внезапно", translation_en: "suddenly, all of a sudden", translation_jp: "突然" },
    { word: "напротив", translation_en: "opposite, in front of, on the contrary", translation_jp: "に対して" },
    { word: "перейти", translation_en: "get across, get over, cross, get, pass on, pass, turn, move on", translation_jp: "行く" },
    { word: "практически", translation_en: "hardly", translation_jp: "実質的に" },
    { word: "существование", translation_en: "existence", translation_jp: "存在" },
    { word: "вход", translation_en: "entrance, entry", translation_jp: "入り口" },
    { word: "церковь", translation_en: "church", translation_jp: "教会" },
    { word: "музей", translation_en: "museum", translation_jp: "博物館" },
    { word: "опасность", translation_en: "danger, peril, jeopardy", translation_jp: "危険" },
    { word: "поиск", translation_en: "search", translation_jp: "検索" },
    { word: "источник", translation_en: "source, a place where something is born appears or begins to spread", translation_jp: "ソース" },
    { word: "выступать", translation_en: "oppose publicly", translation_jp: "実行する" },
    { word: "определить", translation_en: "define, determine", translation_jp: "定義する" },
    { word: "представление", translation_en: "notion, idea, conception", translation_jp: "パフォーマンス" },
    { word: "способность", translation_en: "ability", translation_jp: "能力" },
    { word: "понятие", translation_en: "concept", translation_jp: "コンセプト" },
    { word: "водитель", translation_en: "driver", translation_jp: "ドライバ" },
    { word: "изменение", translation_en: "a change", translation_jp: "変化" },
    { word: "вывод", translation_en: "conclusion", translation_jp: "結論" },
    { word: "комиссия", translation_en: "commission, committee", translation_jp: "手数料" },
    { word: "стоить", translation_en: "cost", translation_jp: "料金" },
    { word: "множество", translation_en: "tons of", translation_jp: "多くの" },
    { word: "явление", translation_en: "phenomenon", translation_jp: "現象" },
    { word: "очевидно", translation_en: "obviously, apparently, manifestly, evidently", translation_jp: "明らかに" },
    { word: "рано", translation_en: "it is early, it is too early, early", translation_jp: "早い" },
    { word: "строить", translation_en: "to build, construct", translation_jp: "建てる" },
    { word: "ниже", translation_en: "lower, below", translation_jp: "下に" },
    { word: "наверняка", translation_en: "for sure, certainly", translation_jp: "確かに" },
    { word: "озеро", translation_en: "lake", translation_jp: "湖" },
    { word: "разобраться", translation_en: "figure out, deal with", translation_jp: "把握する" },
    { word: "кино", translation_en: "cinema, pictures, movies", translation_jp: "映画" },
    { word: "должность", translation_en: "position (job)", translation_jp: "役職" },
    { word: "песня", translation_en: "song", translation_jp: "歌" },
    { word: "выполнять", translation_en: "to perform to carry out", translation_jp: "満たす" },
    { word: "проект", translation_en: "project, design, scheme, draft", translation_jp: "プロジェクト" },
    { word: "навсегда", translation_en: "forever, for good", translation_jp: "永遠に" },
    { word: "суть", translation_en: "essence", translation_jp: "エッセンス" },
    { word: "платье", translation_en: "dress, gown", translation_jp: "ドレス" },
    { word: "хозяйство", translation_en: "farm", translation_jp: "農業" },
    { word: "пункт", translation_en: "point, station, paragraph, item, plank", translation_jp: "段落" },
    { word: "вкус", translation_en: "taste, manner, style", translation_jp: "味" },
    { word: "спустя", translation_en: "after", translation_jp: "後で" },
    { word: "кофе", translation_en: "coffee", translation_jp: "コーヒー" },
    { word: "отделение", translation_en: "separation", translation_jp: "部門" },
    { word: "подать", translation_en: "tax", translation_jp: "提出する" },
    { word: "телевизор", translation_en: "television set, TV set", translation_jp: "テレビ" },
    { word: "помещение", translation_en: "room", translation_jp: "部屋" },
    { word: "поведение", translation_en: "behavior, behaviour", translation_jp: "行動" },
    { word: "создание", translation_en: "creation", translation_jp: "創造" },
    { word: "собрание", translation_en: "meeting, gathering, assembly, collection", translation_jp: "ミーティング" },
    { word: "безопасность", translation_en: "safety, security", translation_jp: "安全性" },
    { word: "заявление", translation_en: "statement, declaration, application, written request", translation_jp: "声明" },
    { word: "подарок", translation_en: "present, gift", translation_jp: "現在" },
    { word: "университет", translation_en: "university", translation_jp: "大学" },
    { word: "товар", translation_en: "commodity, article, goods, wares", translation_jp: "製品" },
    { word: "абсолютно", translation_en: "absolutely, perfectly, utterly", translation_jp: "絶対に" },
    { word: "политика", translation_en: "politics", translation_jp: "ポリシー" },
    { word: "вес", translation_en: "weight", translation_jp: "重さ" },
    { word: "поток", translation_en: "stream or flow", translation_jp: "流れ" },
    { word: "решать", translation_en: "decide, determine, resolve, be determined, solve", translation_jp: "決める" },
    { word: "выполнить", translation_en: "implement, accomplish, carry into effect, realize", translation_jp: "実行する" },
    { word: "корпус", translation_en: "body, corpus", translation_jp: "フレーム" },
    { word: "близко", translation_en: "near, close by, nearly", translation_jp: "近い" },
    { word: "редко", translation_en: "rarely", translation_jp: "めったに" },
    { word: "сеть", translation_en: "web, meshes, toils, system, circuit, net, fishnet", translation_jp: "ネット" },
    { word: "сообщение", translation_en: "message", translation_jp: "メッセージ" },
    { word: "парк", translation_en: "park, fleet, stock, yard, depot", translation_jp: "公園" },
    { word: "бороться", translation_en: "to fight (reflexive)", translation_jp: "戦い" },
    { word: "расстояние", translation_en: "distance, space", translation_jp: "距離" },
    { word: "официальный", translation_en: "official", translation_jp: "正式" },
    { word: "выбор", translation_en: "choice, selection, option, alternative, election", translation_jp: "選択" },
    { word: "содержание", translation_en: "content, matter, substance, table of contents", translation_jp: "コンテンツ" },
    { word: "участвовать", translation_en: "participate, to take part in", translation_jp: "参加する" },
    { word: "температура", translation_en: "temperature, high temperature", translation_jp: "温度" },
    { word: "создавать", translation_en: "create, originate, set up, establish, found", translation_jp: "作成する" },
    { word: "слой", translation_en: "layer", translation_jp: "層" },
    { word: "ровно", translation_en: "evenly", translation_jp: "スムーズ" },
    { word: "заместитель", translation_en: "deputy, vice-", translation_jp: "副" },
    { word: "отличие", translation_en: "distinction difference(from)", translation_jp: "違い" },
    { word: "исследование", translation_en: "research, investigation, analysis, exploration, paper, essay", translation_jp: "勉強" },
    { word: "научиться", translation_en: "learn", translation_jp: "学ぶ" },
    { word: "техника", translation_en: "technique", translation_jp: "技術" },
    { word: "контроль", translation_en: "control", translation_jp: "コントロール" },
    { word: "влияние", translation_en: "influence", translation_jp: "影響" },
    { word: "покупать", translation_en: "buy, purchase, bathe, bath", translation_jp: "買う" },
    { word: "следствие", translation_en: "consequence", translation_jp: "結果" },
    { word: "насколько", translation_en: "how much, as far as, so far as", translation_jp: "いくら" },
    { word: "выбирать", translation_en: "choose, select, pick out, take out", translation_jp: "選ぶ" },
    { word: "заранее", translation_en: "in advance", translation_jp: "あらかじめ" },
    { word: "сохранить", translation_en: "keep", translation_jp: "保存" },
    { word: "менять", translation_en: "change, exchange", translation_jp: "変化" },
    { word: "указать", translation_en: "to point out/at [something], indicate", translation_jp: "示す" },
    { word: "открытие", translation_en: "discovery, throwing open, opening", translation_jp: "オープニング" },
    { word: "храм", translation_en: "temple", translation_jp: "寺" },
    { word: "строительство", translation_en: "construction, building, project", translation_jp: "工事" },
    { word: "погода", translation_en: "weather", translation_jp: "天気" },
    { word: "шоссе", translation_en: "highway, macadam road", translation_jp: "高速道路" },
    { word: "уничтожить", translation_en: "destroy, annihilate, obliterate", translation_jp: "破壊する" },
    { word: "добиться", translation_en: "to achieve", translation_jp: "成し遂げる" },
    { word: "поддерживать", translation_en: "support, back, second, maintain, keep up, bear", translation_jp: "サポート" },
    { word: "отлично", translation_en: "excellently", translation_jp: "素晴らしい" },
    { word: "особенность", translation_en: "peculiarity", translation_jp: "特異性" },
    { word: "памятник", translation_en: "monument, memorial, tombstone, statue", translation_jp: "記念碑" },
    { word: "покинуть", translation_en: "leave, abandon, desert, forsake", translation_jp: "離れる" },
    { word: "везде", translation_en: "everywhere", translation_jp: "どこでも" },
    { word: "сегодняшний", translation_en: "today's (adj)", translation_jp: "今日の" },
    { word: "юг", translation_en: "south", translation_jp: "南" },
    { word: "новость", translation_en: "news", translation_jp: "ニュース" },
    { word: "поражение", translation_en: "defeat", translation_jp: "敗北" },
    { word: "компьютер", translation_en: "computer", translation_jp: "コンピューター" },
    { word: "договор", translation_en: "agreement", translation_jp: "合意" },
    { word: "библиотека", translation_en: "library, lending library, reference library", translation_jp: "図書館" },
    { word: "согласно", translation_en: "according to", translation_jp: "によると" },
    { word: "депутат", translation_en: "government official, deputy", translation_jp: "副" },
    { word: "удобный", translation_en: "comfortable, handy, cosy", translation_jp: "快適" },
    { word: "ответственность", translation_en: "responsibility, amenability", translation_jp: "責任" },
    { word: "переход", translation_en: "passing, crossing, transition, change, crossing, march, passing", translation_jp: "遷移" },
    { word: "услуга", translation_en: "service", translation_jp: "サービス" },
    { word: "модель", translation_en: "model, pattern", translation_jp: "モデル" },
    { word: "отдых", translation_en: "rest", translation_jp: "休む" },
    { word: "поддержка", translation_en: "backing, seconding, encouragement, support", translation_jp: "サポート" },
    { word: "разрешение", translation_en: "permission, permit, authorization, authorisation, licence, solution, settlement", translation_jp: "許可" },
    { word: "производить", translation_en: "to produce/to make", translation_jp: "生産する" },
    { word: "кладбище", translation_en: "cemetery, burial-ground, graveyard, church yard", translation_jp: "墓地" },
    { word: "шанс", translation_en: "chance", translation_jp: "チャンス" },
    { word: "исключительно", translation_en: "exclusively", translation_jp: "独占的に" },
    { word: "прекратить", translation_en: "stop, cease, discontinue, put an end, make an end, bring to a stop, break off, sever", translation_jp: "停止" },
    { word: "обеспечить", translation_en: "to provide", translation_jp: "提供する" },
    { word: "организовать", translation_en: "organize, to organise", translation_jp: "整理する" },
    { word: "стиль", translation_en: "style", translation_jp: "スタイル" },
    { word: "концерт", translation_en: "concert, recital, concerto", translation_jp: "コンサート" },
    { word: "приобрести", translation_en: "acquire, gain, ", translation_jp: "購入" },
    { word: "особо", translation_en: "really, particularly", translation_jp: "特に" },
    { word: "поддержать", translation_en: "support", translation_jp: "サポート" },
    { word: "якобы", translation_en: "as if /as though / allegedly / supposedly", translation_jp: "おそらく" },
    { word: "продолжить", translation_en: "continue, go on, proceed, keep on, extend, prolong", translation_jp: "続く" },
    { word: "метро", translation_en: "metro", translation_jp: "地下鉄" },
    { word: "отдохнуть", translation_en: "rest, be resting, be on holiday, relax", translation_jp: "リラックス" },
    { word: "бизнес", translation_en: "business", translation_jp: "仕事" },
    { word: "вовремя", translation_en: "on time, in time", translation_jp: "その間" },
    { word: "оценка", translation_en: "grade", translation_jp: "学年" },
    { word: "использование", translation_en: "utilization, usage, using, utilisation", translation_jp: "使用法" },
    { word: "наличие", translation_en: "availability presence", translation_jp: "可用性" },
    { word: "применять", translation_en: "apply employ use", translation_jp: "適用する" },
    { word: "путешествие", translation_en: "journey, voyage, trip, travels", translation_jp: "旅" },
    { word: "давление", translation_en: "pressure", translation_jp: "プレッシャー" },
    { word: "дважды", translation_en: "twice, two times", translation_jp: "二度" },
    { word: "вне", translation_en: "out of, outside, off", translation_jp: "外" },
    { word: "воспользоваться", translation_en: "avail oneself, profit, take advantage, appropriate", translation_jp: "利用する" },
    { word: "штат", translation_en: "state", translation_jp: "州" },
    { word: "продажа", translation_en: "sale, selling", translation_jp: "販売" },
    { word: "отличный", translation_en: "excellent, awesome, first-class, great", translation_jp: "素晴らしい" },
    { word: "относительно", translation_en: "relatively, about, quite", translation_jp: "比較的" },
    { word: "переговоры", translation_en: "negotiations, talks, parley", translation_jp: "交渉" },
    { word: "выступление", translation_en: "performance", translation_jp: "パフォーマンス" },
    { word: "торговля", translation_en: "trade, commerce", translation_jp: "貿易" },
    { word: "транспорт", translation_en: "transport, transportation, consignment, train, supply ship, troop transport, troopship, troop-carrier, carrying forward", translation_jp: "輸送" },
    { word: "недалеко", translation_en: "not far, close", translation_jp: "近く" },
    { word: "обмен", translation_en: "exchange, interchange, barter", translation_jp: "交換" },
    { word: "перевод", translation_en: "translation, interpretation", translation_jp: "翻訳" },
    { word: "кафе", translation_en: "café, coffee-house", translation_jp: "カフェ" },
    { word: "режиссёр", translation_en: "producer", translation_jp: "監督" },
    { word: "воскресенье", translation_en: "Sunday", translation_jp: "日曜日" },
    { word: "проверка", translation_en: "check-up control or examination", translation_jp: "検査" },
    { word: "питание", translation_en: "nourishment or nutrition", translation_jp: "栄養" },
    { word: "накануне", translation_en: "the day before, on the eve, just before", translation_jp: "前日" },
    { word: "выставка", translation_en: "exhibition", translation_jp: "展示" },
    { word: "помимо", translation_en: "in addition to", translation_jp: "その上" },
    { word: "брак", translation_en: "marriage", translation_jp: "結婚" },
    { word: "соответствовать", translation_en: "suit conform be consistent with", translation_jp: "対応する" },
    { word: "заменить", translation_en: "to replace", translation_jp: "交換する" },
    { word: "нормально", translation_en: "normally", translation_jp: "大丈夫" },
    { word: "корреспондент", translation_en: "correspondent, reporter", translation_jp: "特派員" },
    { word: "стоимость", translation_en: "cost, value", translation_jp: "価格" },
    { word: "впоследствии", translation_en: "afterwards, later, later on, subsequently", translation_jp: "その後" },
    { word: "вина", translation_en: "fault", translation_jp: "罪悪感" },
    { word: "объём", translation_en: "volume, capacity, size, extend, scope", translation_jp: "音量" },
    { word: "флот", translation_en: "fleet", translation_jp: "艦隊" },
    { word: "налог", translation_en: "tax", translation_jp: "税" },
    { word: "выделить", translation_en: "allocate, pick out, choose, single out, allot, ear-mark, detach, find, provide, apportion, mark out, distinguish, secrete, excrete, discharge, exude, educe, isolate", translation_jp: "ハイライト" },
    { word: "задать", translation_en: "ask, give, set", translation_jp: "セット" },
    { word: "плюс", translation_en: "plus, advantage", translation_jp: "プラス" },
    { word: "сопротивление", translation_en: "resistance", translation_jp: "抵抗" },
    { word: "доход", translation_en: "income, revenue, profit, return, receipts, earnings", translation_jp: "所得" },
    { word: "проспект", translation_en: "avenue, prospectus, booklet, folder", translation_jp: "大通り" },
    { word: "заказать", translation_en: "order", translation_jp: "注文" },
    { word: "мебель", translation_en: "furniture", translation_jp: "家具" },
    { word: "общение", translation_en: "communication", translation_jp: "コミュニケーション" },
    { word: "ремонт", translation_en: "repair, maintenance, remount service", translation_jp: "修理" },
    { word: "заказ", translation_en: "order, prohibition, interdict", translation_jp: "注文" },
    { word: "практика", translation_en: "practice", translation_jp: "練習する" },
    { word: "наступление", translation_en: "arrival or onset", translation_jp: "攻撃" },
    { word: "привлечь", translation_en: "to attract", translation_jp: "引きつける" },
    { word: "выполнение", translation_en: "implementation, fulfilment, carrying-out", translation_jp: "実行" },
    { word: "имущество", translation_en: "property, belongings, stock, stores, equipment", translation_jp: "財産" },
    { word: "сюжет", translation_en: "plot", translation_jp: "プロット" },
    { word: "монастырь", translation_en: "monastery", translation_jp: "修道院" },
    { word: "аэропорт", translation_en: "airport", translation_jp: "空港" },
    { word: "рис", translation_en: "rice, paddy", translation_jp: "米" },
    { word: "крепость", translation_en: "stronghold", translation_jp: "要塞" },
    { word: "интервью", translation_en: "interview", translation_jp: "インタビュー" },
    { word: "адвокат", translation_en: "advocate, counsellor, ", translation_jp: "提唱する" },
    { word: "восстановить", translation_en: "to restore", translation_jp: "復元する" },
    { word: "внести", translation_en: "to bring in, carry in, make", translation_jp: "貢献する" },
    { word: "непосредственно", translation_en: "immediately, directly", translation_jp: "直接" },
    { word: "реклама", translation_en: "advertisement, publicity, advertising", translation_jp: "広告" },
    { word: "премьера", translation_en: "premiere, new production", translation_jp: "プレミア" },
    { word: "предоставить", translation_en: "to grant, to provide", translation_jp: "提供する" },
    { word: "приговор", translation_en: "sentence, verdict, condemnation", translation_jp: "文" },
    { word: "избавиться", translation_en: "to get rid of", translation_jp: "取り除く" },
    { word: "преимущество", translation_en: "advantage, vantage", translation_jp: "アドバンテージ" },
    { word: "мусор", translation_en: "garbage, trash, debris, rubbish, sweepings, dust, refuse, police (slang)", translation_jp: "ごみ" },
    { word: "салон", translation_en: "salon cabin", translation_jp: "サロン" },
    { word: "бюро", translation_en: "bureau", translation_jp: "局" },
    { word: "подробно", translation_en: "in detail, at length, minutely", translation_jp: "詳細に" },
    { word: "село", translation_en: "village", translation_jp: "村" },
    { word: "уточнить", translation_en: "to clarify", translation_jp: "特定" },
    { word: "набор", translation_en: "set/kit range assortment collection", translation_jp: "キット" },
    { word: "украинский", translation_en: "Ukrainian", translation_jp: "ウクライナ語" },
    { word: "объявление", translation_en: "advertisement or announcement", translation_jp: "発表" },
    { word: "общаться", translation_en: "communicate socialise converse deal with", translation_jp: "通信する" },
    { word: "управлять", translation_en: "control", translation_jp: "管理" },
    { word: "ежедневно", translation_en: "daily, every day", translation_jp: "毎日" },
    { word: "официально", translation_en: "officially", translation_jp: "正式に" },
    { word: "бесплатно", translation_en: "free of charge, gratis", translation_jp: "無料で" },
    { word: "мэр", translation_en: "mayor", translation_jp: "市長" },
    { word: "уникальный", translation_en: "unique", translation_jp: "個性的" },
    { word: "мяч", translation_en: "ball", translation_jp: "ボール" },
    { word: "матч", translation_en: "match", translation_jp: "マッチ" },
    { word: "игрок", translation_en: "player, gambler", translation_jp: "プレーヤー" },
    { word: "сотрудничество", translation_en: "cooperation", translation_jp: "協力" },
    { word: "соглашение", translation_en: "agreement, understanding, covenant", translation_jp: "合意" },
    { word: "выпуск", translation_en: "graduation: release", translation_jp: "リリース" },
    { word: "избежать", translation_en: "to escape, to run from", translation_jp: "避ける" },
    { word: "понедельник", translation_en: "Monday", translation_jp: "月曜日" },
    { word: "увеличить", translation_en: "increase, enlarge, extend, augment, magnify", translation_jp: "増加" },
    { word: "посетить", translation_en: "visit", translation_jp: "訪問" },
    { word: "контракт", translation_en: "contract, agreement", translation_jp: "契約" },
    { word: "офис", translation_en: "office", translation_jp: "オフィス" },
    { word: "обувь", translation_en: "shoes", translation_jp: "靴" },
    { word: "факультет", translation_en: "faculty, department", translation_jp: "学部" },
    { word: "сравнительно", translation_en: "comparatively, relatively", translation_jp: "比較的" },
    { word: "агентство", translation_en: "agency", translation_jp: "代理店" },
    { word: "вероятность", translation_en: "likelihood", translation_jp: "確率" },
    { word: "оформить", translation_en: "formalize, form, formalise", translation_jp: "デザイン" },
    { word: "стандартный", translation_en: "standard", translation_jp: "標準" },
    { word: "чемпион", translation_en: "champion, title-holder", translation_jp: "チャンピオン" },
    { word: "сочетание", translation_en: "combination", translation_jp: "組み合わせ" },
    { word: "ущерб", translation_en: "damage, loss, detriment, prejudice", translation_jp: "ダメージ" },
    { word: "вследствие", translation_en: "as a result of, owing to, on account of, in consequence of", translation_jp: "により" },
    { word: "побережье", translation_en: "sea-coast, coast, seaboard, littoral, shore", translation_jp: "海岸" },
    { word: "развивать", translation_en: "to develop", translation_jp: "開発する" },
    { word: "обслуживание", translation_en: "service", translation_jp: "サービス" },
    { word: "приблизительно", translation_en: "approximately, roughly", translation_jp: "約" },
    { word: "частично", translation_en: "in part, partially", translation_jp: "部分的に" },
    { word: "оформление", translation_en: "paperwork, appearance, design, official registration, legalization", translation_jp: "登録" },
    { word: "штраф", translation_en: "finе", translation_jp: "大丈夫" },
    { word: "турнир", translation_en: "tournament", translation_jp: "トーナメント" },
    { word: "жительство", translation_en: "residence", translation_jp: "住居" },
    { word: "финал", translation_en: "finale, ending, denouement, final", translation_jp: "ファイナル" },
    { word: "менеджер", translation_en: "manager", translation_jp: "マネージャー" },
    { word: "четверг", translation_en: "Thursday", translation_jp: "木曜日" },
    { word: "меню", translation_en: "menu, bill of fare", translation_jp: "メニュー" },
    { word: "вторник", translation_en: "Tuesday", translation_jp: "火曜日" },
    { word: "экспорт", translation_en: "export", translation_jp: "輸出" },
    { word: "отопление", translation_en: "heating", translation_jp: "加熱" },
    { word: "достичь", translation_en: "to reach", translation_jp: "到着" },
    { word: "банка", translation_en: "jar", translation_jp: "瓶" },
    { word: "недвижимость", translation_en: "real estatе", translation_jp: "不動産" },
    { word: "скидка", translation_en: "discount", translation_jp: "割引" },
    { word: "улучшить", translation_en: "improve, make better, ameliorate, amend, grade up, better, improve on", translation_jp: "改善する" },
    { word: "доставка", translation_en: "delivery", translation_jp: "配達" },
    { word: "комфорт", translation_en: "comfort", translation_jp: "快適" },
    { word: "кондиционер", translation_en: "air-conditioner", translation_jp: "エアコン" },
    { word: "удалять", translation_en: "delete", translation_jp: "消去" },
    { word: "мор", translation_en: "pestilence, wholesale deaths", translation_jp: "疫病" },
    { word: "ассортимент", translation_en: "assortment, set", translation_jp: "品揃え" },
    { word: "порекомендовать", translation_en: "recommend, advise", translation_jp: "推薦する" },
    { word: "деньги", translation_en: "money, funds, cash", translation_jp: "お金" },
    { word: "всё", translation_en: "always, all the time, the whole time, still, only, all, all the same, however, nevertheless", translation_jp: "全て" },
    { word: "должен", translation_en: "must, have to, be bound, ought, should", translation_jp: "しなければならない" },
    { word: "что-то", translation_en: "something, somehow, it looks as if", translation_jp: "何か" },
    { word: "больше", translation_en: "more", translation_jp: "もっと" },
    { word: "нужно", translation_en: "it is necessary, must, one should, one ought, you should, you ought, should", translation_jp: "する必要がある" },
    { word: "кто-то", translation_en: "somebody, someone", translation_jp: "誰か" },
    { word: "рядом", translation_en: "near, next to, side by side, beside, by, next, next door", translation_jp: "近く" },
    { word: "всего", translation_en: "in all, only, in total, merely", translation_jp: "合計" },
    { word: "дома", translation_en: "at home", translation_jp: "住宅" },
    { word: "что-нибудь", translation_en: "anything, something", translation_jp: "何でも" },
    { word: "где-то", translation_en: "somewhere, anywhere", translation_jp: "どこかで" },
    { word: "лучше", translation_en: "better, it is better", translation_jp: "より良い" },
    { word: "пожалуй", translation_en: "perhaps, very likely, maybe, I think", translation_jp: "多分" },
    { word: "лично", translation_en: "personally", translation_jp: "個人的に" },
    { word: "меньше", translation_en: "less", translation_jp: "少ない" },
    { word: "по-прежнему", translation_en: "as before, as usual", translation_jp: "まだ" },
    { word: "часы", translation_en: "watch, wrist-watch, clock", translation_jp: "時計" },
    { word: "ворота", translation_en: "gate, gates, goal, hoop", translation_jp: "ゲート" },
    { word: "очки", translation_en: "glasses, spectacles, goggles", translation_jp: "眼鏡" },
    { word: "чего", translation_en: "what", translation_jp: "何" },
    { word: "неизвестно", translation_en: "unknown, it is not known", translation_jp: "未知" },
    { word: "полка", translation_en: "the shelf, the rack", translation_jp: "棚" },
    { word: "угодно", translation_en: "wanted, needed", translation_jp: "何でも" },
    { word: "тур", translation_en: "turn, round, gabion, aurochs, Caucasian goat", translation_jp: "ツアー" },
    { word: "желательно", translation_en: "preferable (adv)", translation_jp: "できれば" },
    { word: "раньше", translation_en: "before", translation_jp: "以前" },
    { word: "дальше", translation_en: "farther, further, next, then, any longer", translation_jp: "さらに遠く" },
    { word: "дети", translation_en: "children, kids, babies", translation_jp: "子供たち" },
    { word: "легче", translation_en: "it is easier", translation_jp: "より簡単に" },
    { word: "люди", translation_en: "people, servants, men", translation_jp: "人々" },
    { word: "позже", translation_en: "later", translation_jp: "後で" },
    { word: "родители", translation_en: "parents", translation_jp: "両親" },
    { word: "скорее", translation_en: "rather, sooner", translation_jp: "より速く" },
    { word: "дверь", translation_en: "door", translation_jp: "ドア" },
    { word: "позднее", translation_en: "later", translation_jp: "後で" },
    { word: "вина", translation_en: "fault, guilt", translation_jp: "罪悪感" },
    { word: "замок", translation_en: "castle", translation_jp: "ロック" },
    { word: "замок", translation_en: "lock", translation_jp: "ロック" },
];